---- MODULE Checkout ----
\* GENERATED by machinery compose from checkout.composition.yaml,
\* VALIDATED against FulfillmentSaga.machine.json: the step order below IS the coordinator's
\* forward onDone chain, and every failure route matches the machine.
\* Models the full branching: step failures, per-obligation compensation
\* in any order, and the FailedDirty stall with obligations still held.
\* Residual assumption: each aggregate conforms to its abstract states,
\* discharged per aggregate by its own machine, oracle, and tests.

ReservationStates == {"Free", "Held", "Released"}
PaymentStates == {"NotCaptured", "Captured", "Refunded"}
ShipmentStates == {"NotDispatched", "Dispatched"}
SagaStates == {"Reserving", "Paying", "Shipping", "Compensating", "Completed", "Failed", "FailedDirty"}
VARIABLES saga, reservation, payment, shipment
vars == << saga, reservation, payment, shipment >>

TypeOK == saga \in SagaStates /\ reservation \in ReservationStates /\ payment \in PaymentStates /\ shipment \in ShipmentStates
Init == saga = "Reserving" /\ reservation = "Free" /\ payment = "NotCaptured" /\ shipment = "NotDispatched"

Done_Reserving == saga = "Reserving" /\ saga' = "Paying" /\ reservation' = "Held" /\ UNCHANGED << payment, shipment >>
Fail_Reserving == saga = "Reserving" /\ saga' = "Failed" /\ UNCHANGED << reservation, payment, shipment >>
Done_Paying == saga = "Paying" /\ saga' = "Shipping" /\ payment' = "Captured" /\ UNCHANGED << reservation, shipment >>
Fail_Paying == saga = "Paying" /\ saga' = "Compensating" /\ UNCHANGED << reservation, payment, shipment >>
Done_Shipping == saga = "Shipping" /\ saga' = "Completed" /\ shipment' = "Dispatched" /\ UNCHANGED << reservation, payment >>
Fail_Shipping == saga = "Shipping" /\ saga' = "Compensating" /\ UNCHANGED << reservation, payment, shipment >>
Undo_reservation == saga = "Compensating" /\ reservation = "Held" /\ reservation' = "Released" /\ saga' = saga /\ UNCHANGED << payment, shipment >>
Undo_payment == saga = "Compensating" /\ payment = "Captured" /\ payment' = "Refunded" /\ saga' = saga /\ UNCHANGED << reservation, shipment >>
CompensateDone == saga = "Compensating" /\ (reservation # "Held" /\ payment # "Captured") /\ saga' = "Failed" /\ UNCHANGED << reservation, payment, shipment >>
CompensateStall == saga = "Compensating" /\ (reservation = "Held" \/ payment = "Captured") /\ saga' = "FailedDirty" /\ UNCHANGED << reservation, payment, shipment >>
Done == saga \in {"Completed", "Failed", "FailedDirty"} /\ UNCHANGED vars
Next == Done_Reserving \/ Fail_Reserving \/ Done_Paying \/ Fail_Paying \/ Done_Shipping \/ Fail_Shipping \/ Undo_reservation \/ Undo_payment \/ CompensateDone \/ CompensateStall \/ Done
Spec == Init /\ [][Next]_vars /\ WF_vars(Next)

\* auto-generated: a clean Failed end has undone every committed obligation;
\* only the explicit FailedDirty residual may still hold one
Inv_CleanCompensation == (saga = "Failed") => (reservation # "Held" /\ payment # "Captured")
Inv_ReserveBeforePay == payment = "Captured" => reservation # "Free"
Inv_NoShipBeforePay == shipment = "Dispatched" => payment = "Captured"
Live_Terminates == TRUE ~> (saga \in {"Completed", "Failed", "FailedDirty"})
====
