---- MODULE FulfillmentSagaData ----
\* machinery-version: v0.3.5-dev
\* GENERATED by machinery refine (saga pattern) from FulfillmentSaga.machine.json + FulfillmentSaga.semantics.yaml.
\* Proves money and stock are never silently lost: a terminal saga has undone
\* every obligation it committed, or ends FailedDirty as an explicit residual.
\*
\* RECONCILED against the machine before emission: step order, failure routing,
\* the compensation loop, and the final states all match the machine JSON.
\* Compensation here is PER OBLIGATION (each undo its own step), refining the
\* machine's single idempotent compensate invoke, so partial compensation is
\* representable. STILL ASSUMED: the obligation flags mirror what the real
\* actors commit and undo, and single-instance execution.
\* MaxRetries = 3 (source: semantics max_retries, matching the machine default (no _max_retries declared)).
EXTENDS Naturals

CONSTANT MaxRetries
Steps == {"Reserving", "Paying", "Shipping", "Compensating", "compensateRetry"}
Final == {"Completed", "Failed", "FailedDirty"}
VARIABLES st, rc, reserved, released, captured, refunded, shipped
vars == << st, rc, reserved, released, captured, refunded, shipped >>

TypeOK == st \in (Steps \cup Final) /\ rc \in 0..MaxRetries /\ reserved \in BOOLEAN /\ released \in BOOLEAN /\ captured \in BOOLEAN /\ refunded \in BOOLEAN /\ shipped \in BOOLEAN
Init == st = "Reserving" /\ rc = 0 /\ reserved = FALSE /\ released = FALSE /\ captured = FALSE /\ refunded = FALSE /\ shipped = FALSE

Done_Reserving == st = "Reserving" /\ st' = "Paying" /\ reserved' = TRUE /\ UNCHANGED << rc, released, captured, refunded, shipped >>
Fail_Reserving == st = "Reserving" /\ st' = "Failed" /\ UNCHANGED << rc, reserved, released, captured, refunded, shipped >>
Done_Paying == st = "Paying" /\ st' = "Shipping" /\ captured' = TRUE /\ UNCHANGED << rc, reserved, released, refunded, shipped >>
Fail_Paying == st = "Paying" /\ st' = "Compensating" /\ UNCHANGED << rc, reserved, released, captured, refunded, shipped >>
Done_Shipping == st = "Shipping" /\ st' = "Completed" /\ shipped' = TRUE /\ UNCHANGED << rc, reserved, released, captured, refunded >>
Fail_Shipping == st = "Shipping" /\ st' = "Compensating" /\ UNCHANGED << rc, reserved, released, captured, refunded, shipped >>
Undo_released == st = "Compensating" /\ reserved /\ ~released /\ released' = TRUE /\ st' = st /\ UNCHANGED << rc, reserved, captured, refunded, shipped >>
Undo_refunded == st = "Compensating" /\ captured /\ ~refunded /\ refunded' = TRUE /\ st' = st /\ UNCHANGED << rc, reserved, released, captured, shipped >>
CompensateDone == st = "Compensating" /\ ((reserved => released) /\ (captured => refunded)) /\ st' = "Failed" /\ UNCHANGED << rc, reserved, released, captured, refunded, shipped >>
CompensateErr == st = "Compensating" /\ ((reserved /\ ~released) \/ (captured /\ ~refunded)) /\ st' = "compensateRetry" /\ UNCHANGED << rc, reserved, released, captured, refunded, shipped >>
RetryExhausted == st = "compensateRetry" /\ rc >= MaxRetries /\ st' = "FailedDirty" /\ UNCHANGED << rc, reserved, released, captured, refunded, shipped >>
RetryAgain == st = "compensateRetry" /\ rc < MaxRetries /\ st' = "Compensating" /\ rc' = rc + 1 /\ UNCHANGED << reserved, released, captured, refunded, shipped >>

OverlayNext == Done_Reserving \/ Fail_Reserving \/ Done_Paying \/ Fail_Paying \/ Done_Shipping \/ Fail_Shipping \/ Undo_released \/ Undo_refunded \/ CompensateDone \/ CompensateErr \/ RetryExhausted \/ RetryAgain
Terminated == st \in Final /\ UNCHANGED vars
Next == OverlayNext \/ Terminated
Spec == Init /\ [][Next]_vars /\ WF_vars(OverlayNext)

Inv_NoSilentLoss == (st \in Final) => (((reserved /\ st # "Completed") => (released \/ st = "FailedDirty")) /\ ((captured /\ st # "Completed") => (refunded \/ st = "FailedDirty")))
Inv_CleanCompensation == (st = "Failed") => ((reserved => released) /\ (captured => refunded))
Live_Terminates == (st \notin Final) ~> (st \in Final)
====
