---- MODULE Checkout ----
\* GENERATED by tools/compose_gen.py from checkout.composition.yaml.
\* Proves cross-aggregate invariants by composing the subsystem contracts under the
\* coordinator ordering. No single aggregate can prove these; the composition can.

ReservationStates == {"Free", "Held"}
PaymentStates == {"NotCaptured", "Captured"}
ShipmentStates == {"NotDispatched", "Dispatched"}
Steps == {"s0", "s1", "s2", "s3"}
VARIABLES step, reservation, payment, shipment
vars == << step, reservation, payment, shipment >>

TypeOK == step \in Steps /\ reservation \in ReservationStates /\ payment \in PaymentStates /\ shipment \in ShipmentStates
Init == step = "s0" /\ reservation = "Free" /\ payment = "NotCaptured" /\ shipment = "NotDispatched"

Step0 == step = "s0" /\ step' = "s1" /\ reservation' = "Held" /\ UNCHANGED << payment, shipment >>
Step1 == step = "s1" /\ step' = "s2" /\ payment' = "Captured" /\ UNCHANGED << reservation, shipment >>
Step2 == step = "s2" /\ step' = "s3" /\ shipment' = "Dispatched" /\ UNCHANGED << reservation, payment >>
Done == step = "s3" /\ UNCHANGED vars
Next == Step0 \/ Step1 \/ Step2 \/ Done
Spec == Init /\ [][Next]_vars

Inv_ReserveBeforePay == payment = "Captured" => reservation = "Held"
Inv_NoShipBeforePay == shipment = "Dispatched" => payment = "Captured"
====
