---- MODULE FulfillmentSagaData ----
\* GENERATED by tools/refine_gen.py (saga pattern) from fulfillmentSaga.semantics.yaml.
\* Proves money and stock are never silently lost: a compensated saga refunds what it
\* captured and releases what it reserved, or ends FailedDirty as an explicit residual.
EXTENDS Naturals

CONSTANT MaxRetries
Steps == {"Reserving", "Paying", "Shipping", "Compensating", "compensateRetry"}
Final == {"Completed", "Failed", "FailedDirty"}
VARIABLES st, rc, reserved, released, captured, refunded, shipped
vars == << st, rc, reserved, released, captured, refunded, shipped >>

TypeOK == st \in (Steps \cup Final) /\ rc \in 0..MaxRetries /\ reserved \in BOOLEAN /\ released \in BOOLEAN /\ captured \in BOOLEAN /\ refunded \in BOOLEAN /\ shipped \in BOOLEAN
Init == st = "Reserving" /\ rc = 0 /\ reserved = FALSE /\ released = FALSE /\ captured = FALSE /\ refunded = FALSE /\ shipped = FALSE

Done_Reserving == st = "Reserving" /\ st' = "Paying" /\ reserved' = TRUE /\ UNCHANGED << rc, released, captured, refunded, shipped >>
Fail_Reserving == st = "Reserving" /\ st' = "Failed" /\ UNCHANGED << rc, reserved, released, captured, refunded, shipped >>
Done_Paying == st = "Paying" /\ st' = "Shipping" /\ captured' = TRUE /\ UNCHANGED << rc, reserved, released, refunded, shipped >>
Fail_Paying == st = "Paying" /\ st' = "Compensating" /\ UNCHANGED << rc, reserved, released, captured, refunded, shipped >>
Done_Shipping == st = "Shipping" /\ st' = "Completed" /\ shipped' = TRUE /\ UNCHANGED << rc, reserved, released, captured, refunded >>
Fail_Shipping == st = "Shipping" /\ st' = "Compensating" /\ UNCHANGED << rc, reserved, released, captured, refunded, shipped >>
CompensateDone == st = "Compensating" /\ st' = "Failed" /\ released' = reserved /\ refunded' = captured /\ UNCHANGED << rc, reserved, captured, shipped >>
CompensateErr == st = "Compensating" /\ st' = "compensateRetry" /\ UNCHANGED << rc, reserved, released, captured, refunded, shipped >>
RetryExhausted == st = "compensateRetry" /\ rc >= MaxRetries /\ st' = "FailedDirty" /\ UNCHANGED << rc, reserved, released, captured, refunded, shipped >>
RetryAgain == st = "compensateRetry" /\ rc < MaxRetries /\ st' = "Compensating" /\ rc' = rc + 1 /\ UNCHANGED << reserved, released, captured, refunded, shipped >>

OverlayNext == Done_Reserving \/ Fail_Reserving \/ Done_Paying \/ Fail_Paying \/ Done_Shipping \/ Fail_Shipping \/ CompensateDone \/ CompensateErr \/ RetryExhausted \/ RetryAgain
Terminated == st \in Final /\ UNCHANGED vars
Next == OverlayNext \/ Terminated
Spec == Init /\ [][Next]_vars /\ WF_vars(OverlayNext)

Inv_NoSilentLoss == (st \in Final) => (((reserved /\ st # "Completed") => (released \/ st = "FailedDirty")) /\ ((captured /\ st # "Completed") => (refunded \/ st = "FailedDirty")))
Inv_CleanCompensation == (st = "Failed") => ((reserved => released) /\ (captured => refunded))
Live_Terminates == (st \notin Final) ~> (st \in Final)
====
