---- MODULE PortfolioData ----
\* machinery-version: v0.3.5-dev
\* GENERATED by machinery refine from Portfolio.machine.json + Portfolio.semantics.yaml.
\* Data-refined model: proves the real domain invariants, not just control flow.
\*
\* RECONCILED against the machine before emission: domain states, initial, the
\* advance/win/lose/reopen transition structure, the overlay shape, and the
\* rollback routing all match the machine JSON; a drifted semantics file is a
\* hard generation error.
\* STILL ASSUMED (outside the machine JSON, carried by the named-unit contracts
\* and the implementation tests): the pending/prior context updates the actions
\* perform, and single-instance execution.
\* MaxRetries = 3 (source: semantics max_retries, matching the machine default (no _max_retries declared)).
EXTENDS Naturals

CONSTANT MaxRetries

Open == {"Proposed", "UnderReview"}
Terminal == {"Accepted", "Rejected"}
Domain == Open \cup Terminal
Overlay == {"committing", "commitRetry", "reverted"}
None == "none"
Rank == [Proposed |-> 0, UnderReview |-> 1, Accepted |-> 2, Rejected |-> 2]
NextStage == [Proposed |-> "UnderReview"]

VARIABLES st, rc, stage, pending, prior, closeSet
vars == << st, rc, stage, pending, prior, closeSet >>

TypeOK ==
  /\ st \in (Domain \cup Overlay)
  /\ rc \in 0..MaxRetries
  /\ stage \in Domain
  /\ pending \in (Domain \cup {None})
  /\ prior \in (Domain \cup {None})
  /\ closeSet \in BOOLEAN

Init ==
  /\ st = "Proposed" /\ stage = "Proposed"
  /\ rc = 0 /\ pending = None /\ prior = None /\ closeSet = FALSE

StartAdvance ==
  /\ st \in {"Proposed"}
  /\ st' = "committing" /\ pending' = NextStage[st] /\ prior' = st
  /\ rc' = 0 /\ stage' = stage /\ closeSet' = closeSet

StartWin ==
  /\ st \in Open
  /\ st' = "committing" /\ pending' = "Accepted" /\ prior' = st
  /\ rc' = 0 /\ stage' = stage /\ closeSet' = closeSet

StartLose ==
  /\ st \in Open
  /\ st' = "committing" /\ pending' = "Rejected" /\ prior' = st
  /\ rc' = 0 /\ stage' = stage /\ closeSet' = closeSet

StartReopen ==
  /\ st \in Terminal
  /\ st' = "committing" /\ pending' = "UnderReview" /\ prior' = st
  /\ rc' = 0 /\ stage' = stage /\ closeSet' = closeSet

SaveDone ==
  /\ st = "committing"
  /\ st' = pending /\ stage' = pending
  /\ closeSet' = (closeSet \/ (pending = "Accepted"))
  /\ pending' = None /\ prior' = None /\ rc' = 0

SaveLocked ==
  /\ st = "committing" /\ st' = "commitRetry"
  /\ UNCHANGED << rc, stage, pending, prior, closeSet >>

SaveFail ==
  /\ st = "committing" /\ st' = "reverted"
  /\ UNCHANGED << rc, stage, pending, prior, closeSet >>

RetryExhausted ==
  /\ st = "commitRetry" /\ rc >= MaxRetries /\ st' = "reverted"
  /\ UNCHANGED << rc, stage, pending, prior, closeSet >>

RetryAgain ==
  /\ st = "commitRetry" /\ rc < MaxRetries /\ st' = "committing" /\ rc' = rc + 1
  /\ UNCHANGED << stage, pending, prior, closeSet >>

RolledBack ==
  /\ st = "reverted"
  /\ st' = prior /\ stage' = prior
  /\ pending' = None /\ prior' = None /\ rc' = 0 /\ closeSet' = closeSet

Domain_Next == StartAdvance \/ StartWin \/ StartLose \/ StartReopen
Overlay_Next == SaveDone \/ SaveLocked \/ SaveFail \/ RetryExhausted \/ RetryAgain \/ RolledBack
Next == Domain_Next \/ Overlay_Next

Spec == Init /\ [][Next]_vars /\ WF_vars(Overlay_Next)

Inv_StageValid == stage \in Domain
Inv_Atomic == (st \in Overlay) => (stage = prior)
Inv_DomainConsistent == (st \in Domain) => (st = stage /\ pending = None /\ prior = None)
Inv_CloseDate == (stage = "Accepted") => closeSet

StageForward ==
  [][ (stage' # stage) =>
        \/ Rank[stage'] > Rank[stage]
        \/ (stage \in Terminal /\ stage' = "UnderReview") ]_stage

Live_OverlayResolves == (st \in Overlay) ~> (st \in Domain)
====
