---- MODULE RecommendationRunData ----
\* GENERATED by tools/refine_gen.py (terminal-lifecycle) from RecommendationRun.machine.json + RecommendationRun.semantics.yaml.
\* Data-refined model of a forward pipeline: invoking phases advance to a success
\* terminal or fail (directly or after bounded retries) to a failure terminal.
\*
\* RECONCILED against the machine before emission: the phase order, the onDone
\* forward chain, every failure route, the terminal states, and each retry
\* overlay all match the machine JSON. All state names come from the annotation;
\* nothing is hardcoded to a domain.
\* Proves: completeness (a success terminal implies its completion flag; there is
\* no partial success), terminal absorption, and termination. The domain-progress
\* proof is separate from the persistence mechanism: no persist overlay is baked in.
\* STILL ASSUMED: the effect the completion flag stands for is really established
\* on the success path, MaxRetries = 3, and single-instance execution.
EXTENDS Naturals

CONSTANT MaxRetries
Phases == {"Collecting", "Optimizing"}
Success == {"Ready"}
Failure == {"Failed"}
Terminal == Success \cup Failure
Retry == {"collectRetry"}
VARIABLES st, rc, portfolioReady
vars == << st, rc, portfolioReady >>

TypeOK == st \in (Phases \cup Retry \cup Terminal) /\ rc \in 0..MaxRetries /\ portfolioReady \in BOOLEAN
Init == st = "Collecting" /\ rc = 0 /\ portfolioReady = FALSE

Done_Collecting == st = "Collecting" /\ st' = "Optimizing" /\ UNCHANGED << rc, portfolioReady >>
Fail_Collecting == st = "Collecting" /\ st' = "collectRetry" /\ UNCHANGED << rc, portfolioReady >>
Done_Optimizing == st = "Optimizing" /\ st' = "Ready" /\ portfolioReady' = TRUE /\ UNCHANGED << rc >>
Fail_Optimizing == st = "Optimizing" /\ st' = "Failed" /\ UNCHANGED << rc, portfolioReady >>
RetryAgain_collectRetry == st = "collectRetry" /\ rc < MaxRetries /\ st' = "Collecting" /\ rc' = rc + 1 /\ UNCHANGED << portfolioReady >>
RetryExhausted_collectRetry == st = "collectRetry" /\ rc >= MaxRetries /\ st' = "Failed" /\ UNCHANGED << rc, portfolioReady >>
Terminated == st \in Terminal /\ UNCHANGED vars
Prog == Done_Collecting \/ Fail_Collecting \/ Done_Optimizing \/ Fail_Optimizing \/ RetryAgain_collectRetry \/ RetryExhausted_collectRetry
Next == Prog \/ Terminated
Spec == Init /\ [][Next]_vars /\ WF_vars(Prog)

Inv_Complete == (st \in Success) => portfolioReady
Inv_TerminalAbsorbing == [][ (st \in Terminal) => (st' = st) ]_st
Live_Terminates == (st \notin Terminal) ~> (st \in Terminal)
====
