// Package version carries the machinery build version into the generated
// artifacts. Committed artifacts record which machinery version produced them
// (one stamp line per file, in the file format's comment syntax), so a
// mid-build binary upgrade is visible as a version skew instead of
// masquerading as design drift. Freshness gates strip the stamp line from
// both sides of every byte diff: a version-only skew is never DRIFT.
package version

import "strings"

// Version is the machinery build version stamped into generated artifacts.
// cmd/machinery overwrites it at startup with the ldflags-injected binary
// version; the default here mirrors the binary's own -dev default so
// in-process library use (tests, gates) stamps what a bare build reports.
// A contract test in cmd/machinery pins the two defaults together.
var Version = "v0.3.4-dev"

// marker is the stamp key: every stamp line contains exactly
// "machinery-version: <version>" inside the format's comment syntax.
const marker = "machinery-version:"

// MarkdownStamp is the stamp line for generated markdown artifacts
// (transition oracles, authz/tenant oracles).
func MarkdownStamp() string { return "<!-- " + marker + " " + Version + " -->" }

// TLAStamp is the stamp line for generated .tla and .cfg artifacts.
func TLAStamp() string { return `\* ` + marker + " " + Version }

// AlloyStamp is the stamp line for generated .als artifacts.
func AlloyStamp() string { return "// " + marker + " " + Version }

// StampTLAModule inserts the TLA stamp directly after the leading
// "---- MODULE ----" line (a module file must open with it); a body that
// does not start with a module line gets the stamp prepended.
func StampTLAModule(doc string) string {
	if !strings.HasPrefix(doc, "---- MODULE") {
		return TLAStamp() + "\n" + doc
	}
	i := strings.Index(doc, "\n")
	if i < 0 {
		return doc + "\n" + TLAStamp() + "\n"
	}
	return doc[:i+1] + TLAStamp() + "\n" + doc[i+1:]
}

// StampCfg prepends the stamp line to a .cfg body (TLC's config parser
// accepts \* line comments).
func StampCfg(doc string) string { return TLAStamp() + "\n" + doc }

// Strip removes every stamp line from artifact text. Both sides of a
// freshness byte-diff go through it, so artifacts generated by different
// machinery versions still compare equal when their content matches.
func Strip(doc string) string {
	if !strings.Contains(doc, marker) {
		return doc
	}
	lines := strings.Split(doc, "\n")
	kept := make([]string, 0, len(lines))
	for _, l := range lines {
		if strings.Contains(l, marker) {
			continue
		}
		kept = append(kept, l)
	}
	return strings.Join(kept, "\n")
}

// StampOf extracts the stamped version from artifact text; "" when the text
// carries no stamp (a pre-stamp artifact, which is not a skew).
func StampOf(doc string) string {
	i := strings.Index(doc, marker)
	if i < 0 {
		return ""
	}
	rest := doc[i+len(marker):]
	if j := strings.IndexByte(rest, '\n'); j >= 0 {
		rest = rest[:j]
	}
	rest = strings.TrimSpace(rest)
	rest = strings.TrimSpace(strings.TrimSuffix(rest, "-->"))
	return rest
}
