// Package version carries the machinery build version into the generated
// artifacts. Committed artifacts record which machinery version produced them
// (one stamp line per file, in the file format's comment syntax), so a
// mid-build binary upgrade is visible as a version skew instead of
// masquerading as design drift. Freshness gates strip the stamp line from
// both sides of every byte diff: a version-only skew is never DRIFT.
package version

import "strings"

// Version is the machinery build version stamped into generated artifacts.
// cmd/machinery overwrites it at startup with the ldflags-injected binary
// version; the default here mirrors the binary's own default so in-process
// library use (tests, gates) stamps what a bare build reports. Versions are
// numeric only (no -dev or other pre-release suffix): a local build reports
// the same plain version as the release it corresponds to. A contract test
// in cmd/machinery pins the two defaults together.
var Version = "v0.6.11"

// StructurizrVersion is the exact CLI engine identity supported by this
// binary. It is embedded so installed binaries can verify arbitrary user
// projects without depending on the source repository's .structurizr-pin.
const StructurizrVersion = "2025.11.09"

// StructurizrLinuxZipSHA256 is the official release archive identity. The
// release ZIP is platform-independent despite the historical pin name.
const StructurizrLinuxZipSHA256 = "f5365a463fc44d539ed19bec00c48ba1e1ecda0ccfd1ba40d2e7472d264eb79a"

// marker is the stamp key: every stamp line contains exactly
// "machinery-version: <version>" inside the format's comment syntax.
const marker = "machinery-version:"

// MarkdownStamp is the stamp line for generated markdown artifacts
// (transition oracles, authz/tenant oracles).
func MarkdownStamp() string { return "<!-- " + marker + " " + Version + " -->" }

// TLAStamp is the stamp line for generated .tla and .cfg artifacts.
func TLAStamp() string { return `\* ` + marker + " " + Version }

// AlloyStamp is the stamp line for generated .als artifacts.
func AlloyStamp() string { return "// " + marker + " " + Version }

// StampTLAModule inserts the TLA stamp directly after the leading
// "---- MODULE ----" line (a module file must open with it); a body that
// does not start with a module line gets the stamp prepended.
func StampTLAModule(doc string) string {
	if !strings.HasPrefix(doc, "---- MODULE") {
		return TLAStamp() + "\n" + doc
	}
	i := strings.Index(doc, "\n")
	if i < 0 {
		return doc + "\n" + TLAStamp() + "\n"
	}
	return doc[:i+1] + TLAStamp() + "\n" + doc[i+1:]
}

// StampCfg prepends the stamp line to a .cfg body (TLC's config parser
// accepts \* line comments).
func StampCfg(doc string) string { return TLAStamp() + "\n" + doc }

// canonicalStampVersion recognizes only a comment-only stamp line.  It is
// deliberately strict: freshness comparisons must never erase executable
// content merely because it contains the marker in a trailing comment.
func canonicalStampVersion(line string) (string, bool) {
	line = strings.TrimSuffix(line, "\r")
	var body string
	switch {
	case strings.HasPrefix(line, "<!-- ") && strings.HasSuffix(line, " -->"):
		body = strings.TrimSuffix(strings.TrimPrefix(line, "<!-- "), " -->")
	case strings.HasPrefix(line, `\* `):
		body = strings.TrimPrefix(line, `\* `)
	case strings.HasPrefix(line, "// "):
		body = strings.TrimPrefix(line, "// ")
	default:
		return "", false
	}
	if !strings.HasPrefix(body, marker+" ") {
		return "", false
	}
	v := strings.TrimPrefix(body, marker+" ")
	if v == "" || strings.TrimSpace(v) != v || strings.ContainsAny(v, " \t") {
		return "", false
	}
	return v, true
}

// Strip removes canonical comment-only stamp lines from artifact text. Both
// sides of a freshness byte-diff go through it, so artifacts generated by
// different machinery versions still compare equal when their content
// matches. A marker embedded in executable content is retained and therefore
// causes freshness drift.
func Strip(doc string) string {
	if !strings.Contains(doc, marker) {
		return doc
	}
	lines := strings.Split(doc, "\n")
	kept := make([]string, 0, len(lines))
	for _, l := range lines {
		if _, ok := canonicalStampVersion(l); ok {
			continue
		}
		kept = append(kept, l)
	}
	return strings.Join(kept, "\n")
}

// StampOf extracts the version from the first canonical comment-only stamp;
// "" when the text carries no such stamp (a pre-stamp artifact, which is not
// a skew). Marker text embedded in executable content is not a stamp.
func StampOf(doc string) string {
	for _, line := range strings.Split(doc, "\n") {
		if v, ok := canonicalStampVersion(line); ok {
			return v
		}
	}
	return ""
}
