package checker

import (
	"errors"
	"fmt"
	"os"
	"strings"

	"github.com/RamXX/machinery/internal/designlock"
	"github.com/RamXX/machinery/internal/filelock"
)

// ProjectResult records one manifest's generated projection.
type ProjectResult struct {
	CheckerID string
	Path      string // projection file written, relative to the design
}

type plannedProjection struct {
	result   ProjectResult
	dest     string
	rendered []byte
}

// ProjectAll generates and writes the committed projection for every checker
// manifest in the design. It is the write side of the gk contract: the gate
// reads exactly what this produced, so `machinery project` then `git commit` is
// the loop a builder runs before the checker's adapter consumes the projection.
func ProjectAll(design, machineryVersion string) (results []ProjectResult, retErr error) {
	snapshot, err := designlock.Acquire(design)
	if err != nil {
		return nil, err
	}
	defer func() { retErr = snapshot.LogicalError(errors.Join(retErr, snapshot.Release())) }()
	if err := snapshot.ResumeExpected("checker-project", "rerun `machinery project` with the same arguments"); err != nil {
		return nil, err
	}
	lock, err := filelock.Acquire(design)
	if err != nil {
		return nil, fmt.Errorf("lock checker projection transaction: %w", err)
	}
	defer func() {
		retErr = errors.Join(retErr, lock.Release())
	}()
	rootHandle, err := snapshot.OpenRoot(design)
	if err != nil {
		return nil, err
	}
	designAbs, err := cleanDesignRoot(design)
	if err != nil {
		_ = rootHandle.Close()
		return nil, err
	}
	root := &designRoot{abs: designAbs, root: rootHandle}
	defer closeRoot(&retErr, root)
	if err := recoverProjectionTransactionRoot(root); err != nil {
		return nil, fmt.Errorf("recover checker projection transaction: %w", err)
	}
	sourceRoot, err := openDesignRoot(snapshot.SourceRoot())
	if err != nil {
		return nil, fmt.Errorf("open immutable checker design source: %w", err)
	}
	defer closeRoot(&retErr, sourceRoot)
	modelPaths, err := sourceRoot.modelPaths()
	if err != nil {
		return nil, err
	}
	if len(modelPaths) != 1 {
		return nil, fmt.Errorf("expected exactly one *.modelith.yaml in %s, found %d", design, len(modelPaths))
	}
	modelPath := modelPaths[0]
	model, modelBytes, err := sourceRoot.loadModel(modelPath)
	if err != nil {
		return nil, err
	}
	designID := designIDBytes(modelBytes)
	manifestPaths, err := sourceRoot.manifestPaths()
	if err != nil {
		return nil, err
	}
	manifests := make([]*Manifest, 0, len(manifestPaths))
	for _, mp := range manifestPaths {
		man, err := sourceRoot.loadManifest(mp)
		if err != nil {
			return nil, err
		}
		manifests = append(manifests, man)
	}
	if err := ValidateManifestSet(manifests); err != nil {
		return nil, err
	}
	if problems := InventoryProblems(design, manifests); len(problems) != 0 {
		return nil, fmt.Errorf("checker inventory is not exact: %s", strings.Join(problems, "; "))
	}
	if len(manifests) == 0 {
		return nil, fmt.Errorf("no checkers/*.checker.yaml in %s", design)
	}
	plans := make([]plannedProjection, 0, len(manifests))
	for _, man := range manifests {
		proj, err := Generate(model, man, designID, machineryVersion)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", man.Checker.ID, err)
		}
		rendered, err := proj.Render()
		if err != nil {
			return nil, err
		}
		destRel, err := root.confinedRel(man.Evidence.ProjectionOut)
		if err != nil {
			return nil, fmt.Errorf("%s: projection_out: %w", man.Checker.ID, err)
		}
		plans = append(plans, plannedProjection{
			result:   ProjectResult{CheckerID: man.Checker.ID, Path: man.Evidence.ProjectionOut},
			dest:     root.display(destRel),
			rendered: rendered,
		})
	}
	// All manifests, global identities, paths, and generated bytes have been
	// validated before the first filesystem mutation. Stage every output and
	// replace the set transactionally so a later failure cannot leave an earlier
	// projection updated.
	expected := make([]designlock.OutputExpectation, 0, len(plans))
	for _, plan := range plans {
		expected = append(expected, designlock.ExpectFile(plan.dest, plan.rendered, 0o644))
	}
	if err := snapshot.PublishExpectedRooted("checker-project", "rerun `machinery project` with the same arguments", expected, func(outputs *designlock.OutputScope) error {
		return outputs.WithRoot(design, func(outputRoot *os.Root) error {
			publishRoot := &designRoot{abs: designAbs, root: outputRoot}
			return commitProjectionPlansRoot(publishRoot, plans, projectionTransactionHooks{})
		})
	}); err != nil {
		return nil, err
	}
	out := make([]ProjectResult, 0, len(plans))
	for _, plan := range plans {
		out = append(out, plan.result)
	}
	return out, nil
}
