package checker

// The published 2.0 schema is regenerated here, so the contract test stays
// the one authority over it. Its hand-written parts (the header, the model
// block and $defs) are read back from the committed file in key order; the
// generated parts (every layers.<layer> object and the defining-relation list
// in the description) are rebuilt from the relation catalog. After a catalog
// change:
//
//	go test ./internal/checker -run TestProjectionV2SchemaIsGenerated -update
//
// and review the schema diff. Without -update the test fails when the
// committed file differs from the regenerated bytes.

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

var updateSchema = flag.Bool("update", false, "regenerate schemas/projection-v2.schema.json from the relation catalog")

// jsonNode is an order-preserving JSON value: an object keeps its members in
// source order, so a round trip reproduces the committed layout.
type jsonNode struct {
	object []jsonMember
	isObj  bool
	array  []*jsonNode
	isArr  bool
	scalar json.RawMessage
}

type jsonMember struct {
	key   string
	value *jsonNode
}

func decodeOrdered(dec *json.Decoder) (*jsonNode, error) {
	tok, err := dec.Token()
	if err != nil {
		return nil, err
	}
	switch v := tok.(type) {
	case json.Delim:
		switch v {
		case '{':
			n := &jsonNode{isObj: true}
			for dec.More() {
				kt, err := dec.Token()
				if err != nil {
					return nil, err
				}
				child, err := decodeOrdered(dec)
				if err != nil {
					return nil, err
				}
				n.object = append(n.object, jsonMember{key: kt.(string), value: child})
			}
			_, err = dec.Token()
			return n, err
		case '[':
			n := &jsonNode{isArr: true}
			for dec.More() {
				child, err := decodeOrdered(dec)
				if err != nil {
					return nil, err
				}
				n.array = append(n.array, child)
			}
			_, err = dec.Token()
			return n, err
		}
		return nil, fmt.Errorf("unexpected delimiter %v", v)
	case json.Number:
		return &jsonNode{scalar: json.RawMessage(v.String())}, nil
	default:
		raw, err := marshalNoEscape(v)
		return &jsonNode{scalar: raw}, err
	}
}

func marshalNoEscape(v any) ([]byte, error) {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	return bytes.TrimRight(b.Bytes(), "\n"), nil
}

func (n *jsonNode) get(key string) *jsonNode {
	if n == nil {
		return nil
	}
	for _, m := range n.object {
		if m.key == key {
			return m.value
		}
	}
	return nil
}

func (n *jsonNode) write(b *bytes.Buffer, depth int) {
	pad := strings.Repeat("  ", depth+1)
	closing := strings.Repeat("  ", depth)
	switch {
	case n.isObj:
		if len(n.object) == 0 {
			b.WriteString("{}")
			return
		}
		b.WriteString("{\n")
		for i, m := range n.object {
			key, _ := marshalNoEscape(m.key)
			b.WriteString(pad)
			b.Write(key)
			b.WriteString(": ")
			m.value.write(b, depth+1)
			if i < len(n.object)-1 {
				b.WriteByte(',')
			}
			b.WriteByte('\n')
		}
		b.WriteString(closing + "}")
	case n.isArr:
		if len(n.array) == 0 {
			b.WriteString("[]")
			return
		}
		b.WriteString("[\n")
		for i, v := range n.array {
			b.WriteString(pad)
			v.write(b, depth+1)
			if i < len(n.array)-1 {
				b.WriteByte(',')
			}
			b.WriteByte('\n')
		}
		b.WriteString(closing + "]")
	default:
		b.Write(n.scalar)
	}
}

func scalarNode(v any) *jsonNode {
	raw, err := marshalNoEscape(v)
	if err != nil {
		panic(err)
	}
	return &jsonNode{scalar: raw}
}

func objectNode(members ...jsonMember) *jsonNode { return &jsonNode{isObj: true, object: members} }

func stringArrayNode(values []string) *jsonNode {
	n := &jsonNode{isArr: true}
	for _, v := range values {
		n.array = append(n.array, scalarNode(v))
	}
	return n
}

func refNode(def string) *jsonNode {
	return objectNode(jsonMember{"$ref", scalarNode("#/$defs/" + def)})
}

// layerSchema renders one layers.<layer> object from the catalog.
func layerSchema(layer string) *jsonNode {
	names := LayerRelations(layer)
	props := objectNode()
	for _, name := range names {
		spec := relationByName[name]
		rowProps := objectNode(jsonMember{"stable_id", refNode("stableId")}, jsonMember{"source", refNode("source")})
		for _, column := range spec.Columns {
			rowProps.object = append(rowProps.object, jsonMember{column, refNode("symbol")})
		}
		props.object = append(props.object, jsonMember{name, objectNode(
			jsonMember{"type", scalarNode("array")},
			jsonMember{"items", objectNode(
				jsonMember{"type", scalarNode("object")},
				jsonMember{"required", stringArrayNode(append([]string{"stable_id", "source"}, spec.Columns...))},
				jsonMember{"additionalProperties", scalarNode(false)},
				jsonMember{"properties", rowProps},
			)},
		)})
	}
	return objectNode(
		jsonMember{"type", scalarNode("object")},
		jsonMember{"required", stringArrayNode(names)},
		jsonMember{"additionalProperties", scalarNode(false)},
		jsonMember{"properties", props},
	)
}

var definingList = regexp.MustCompile(`defining relation \([^)]*\)`)

// regenerateProjectionV2Schema rebuilds the generated parts of the committed
// schema from the catalog and returns the full file bytes.
func regenerateProjectionV2Schema(committed []byte) ([]byte, error) {
	dec := json.NewDecoder(bytes.NewReader(committed))
	dec.UseNumber()
	root, err := decodeOrdered(dec)
	if err != nil {
		return nil, err
	}
	var defining []string
	for _, spec := range relationCatalog {
		if spec.Defines {
			defining = append(defining, spec.Name)
		}
	}
	descNode := root.get("description")
	if descNode == nil {
		return nil, fmt.Errorf("the schema has no description")
	}
	var description string
	if err := json.Unmarshal(descNode.scalar, &description); err != nil {
		return nil, err
	}
	if !definingList.MatchString(description) {
		return nil, fmt.Errorf("the schema description lost its defining relation (...) list")
	}
	*descNode = *scalarNode(definingList.ReplaceAllLiteralString(description, "defining relation ("+strings.Join(defining, ", ")+")"))
	layers := root.get("properties").get("layers").get("properties")
	if layers == nil {
		return nil, fmt.Errorf("the schema has no properties.layers.properties")
	}
	fresh := objectNode()
	for _, layer := range includeOrder {
		if !unsupportedLayers[layer] {
			fresh.object = append(fresh.object, jsonMember{layer, layerSchema(layer)})
		}
	}
	*layers = *fresh
	var b bytes.Buffer
	root.write(&b, 0)
	b.WriteByte('\n')
	return b.Bytes(), nil
}

func TestProjectionV2SchemaIsGenerated(t *testing.T) {
	path := filepath.Join("..", "..", "schemas", "projection-v2.schema.json")
	committed, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want, err := regenerateProjectionV2Schema(committed)
	if err != nil {
		t.Fatal(err)
	}
	if *updateSchema {
		if err := os.WriteFile(path, want, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	if !bytes.Equal(committed, want) {
		t.Fatal("schemas/projection-v2.schema.json is stale against the relation catalog; regenerate with: go test ./internal/checker -run TestProjectionV2SchemaIsGenerated -update")
	}
}

// The serializer reproduces a hand-written document byte for byte, so the
// non-generated parts of the schema survive regeneration untouched.
func TestOrderedJSONRoundTrip(t *testing.T) {
	src := "{\n  \"b\": 1,\n  \"a\": [\n    \"x\\\\y\",\n    {\n      \"z\": false\n    }\n  ],\n  \"e\": [],\n  \"o\": {}\n}\n"
	dec := json.NewDecoder(strings.NewReader(src))
	dec.UseNumber()
	root, err := decodeOrdered(dec)
	if err != nil {
		t.Fatal(err)
	}
	var b bytes.Buffer
	root.write(&b, 0)
	b.WriteByte('\n')
	if b.String() != src {
		t.Fatalf("round trip changed the document:\n%s", b.String())
	}
}

// A regeneration of the committed file with the catalog as it was when the
// file was written reproduces it exactly: the generator emits no layout of its
// own beyond what the committed file already has.
func TestProjectionV2SchemaRegenerationIsIdempotent(t *testing.T) {
	committed, err := os.ReadFile(filepath.Join("..", "..", "schemas", "projection-v2.schema.json"))
	if err != nil {
		t.Fatal(err)
	}
	once, err := regenerateProjectionV2Schema(committed)
	if err != nil {
		t.Fatal(err)
	}
	twice, err := regenerateProjectionV2Schema(once)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(once, twice) {
		t.Fatal("regenerating a regenerated schema changed it")
	}
}
