package designlock

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatedPackHeader = "# GENERATED by machinery pack. The frozen interface between the parent\n"
const packCapabilityMaxEntries = 32
const packCapabilityFileMaxBytes int64 = 16 << 20
const packCapabilityTotalMaxBytes int64 = 64 << 20

func strictYAMLMapping(path string, body []byte) (map[string]*yaml.Node, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal(body, &doc); err != nil || len(doc.Content) != 1 || doc.Content[0].Kind != yaml.MappingNode {
		return nil, fmt.Errorf("%s must be one YAML mapping: %w", path, err)
	}
	root := doc.Content[0]
	fields := make(map[string]*yaml.Node, len(root.Content)/2)
	for i := 0; i < len(root.Content); i += 2 {
		key := root.Content[i]
		if key.Kind != yaml.ScalarNode || key.Tag != "!!str" || strings.TrimSpace(key.Value) == "" {
			return nil, fmt.Errorf("%s contains a non-string or empty key", path)
		}
		if _, exists := fields[key.Value]; exists {
			return nil, fmt.Errorf("%s contains duplicate key %q", path, key.Value)
		}
		fields[key.Value] = root.Content[i+1]
	}
	return fields, nil
}

func exactKeys(path string, fields map[string]*yaml.Node, allowed []string) error {
	allow := make(map[string]bool, len(allowed))
	for _, key := range allowed {
		allow[key] = true
	}
	var unknown []string
	for key := range fields {
		if !allow[key] {
			unknown = append(unknown, key)
		}
	}
	sort.Strings(unknown)
	if len(unknown) > 0 {
		return fmt.Errorf("%s contains unknown key %q", path, unknown[0])
	}
	return nil
}

func requiredString(path string, fields map[string]*yaml.Node, key string) (string, error) {
	node := fields[key]
	if node == nil || node.Kind != yaml.ScalarNode || node.Tag != "!!str" || strings.TrimSpace(node.Value) == "" {
		return "", fmt.Errorf("%s %s must be a non-empty string", path, key)
	}
	return node.Value, nil
}

func requiredStringSequence(path string, fields map[string]*yaml.Node, key string) error {
	node := fields[key]
	if node == nil || node.Kind != yaml.SequenceNode {
		return fmt.Errorf("%s %s must be an array of strings", path, key)
	}
	for i, item := range node.Content {
		if item.Kind != yaml.ScalarNode || item.Tag != "!!str" || strings.TrimSpace(item.Value) == "" {
			return fmt.Errorf("%s %s[%d] must be a non-empty string", path, key, i)
		}
	}
	return nil
}

func stripPackContentHash(body string) string {
	lines := strings.Split(body, "\n")
	kept := lines[:0]
	for _, line := range lines {
		if !strings.HasPrefix(line, "content_hash:") {
			kept = append(kept, line)
		}
	}
	return strings.Join(kept, "\n")
}

func hashPackFiles(files map[string]string) string {
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	hash := sha256.New()
	for _, name := range names {
		body := files[name]
		if name == "pack.yaml" {
			body = stripPackContentHash(body)
		}
		_, _ = fmt.Fprintf(hash, "%s\n%d\n%s\n", name, len(body), body)
	}
	return hex.EncodeToString(hash.Sum(nil))
}

func readStrictPackFiles(packDir string) (map[string]string, error) {
	before, err := os.Lstat(packDir)
	if err != nil {
		return nil, err
	}
	if before.Mode()&os.ModeSymlink != 0 || !before.IsDir() {
		return nil, fmt.Errorf("child pack capability must be a real directory")
	}
	root, err := os.OpenRoot(packDir)
	if err != nil {
		return nil, err
	}
	defer root.Close()
	opened, err := root.Lstat(".")
	if err != nil || !os.SameFile(before, opened) {
		return nil, fmt.Errorf("child pack capability changed identity while opening")
	}
	dir, err := root.Open(".")
	if err != nil {
		return nil, err
	}
	budget := snapshotBudget{maxEntries: packCapabilityMaxEntries, maxBytes: packCapabilityTotalMaxBytes}
	entries, readErr := readSnapshotDir(dir, "child pack capability", &budget)
	closeErr := dir.Close()
	if err := errors.Join(readErr, closeErr); err != nil {
		return nil, err
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name() < entries[j].Name() })
	files := make(map[string]string, len(entries))
	for _, entry := range entries {
		info, err := root.Lstat(entry.Name())
		if err != nil {
			return nil, err
		}
		if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
			return nil, fmt.Errorf("child pack member %s must be a regular file", entry.Name())
		}
		if info.Size() > packCapabilityFileMaxBytes {
			return nil, fmt.Errorf("child pack member %s exceeds %d-byte limit", entry.Name(), packCapabilityFileMaxBytes)
		}
		if err := budget.addFile(entry.Name(), info); err != nil {
			return nil, err
		}
		body, err := readSnapshotRegularRoot(root, entry.Name(), "child pack member "+entry.Name(), packCapabilityFileMaxBytes)
		if err != nil {
			return nil, err
		}
		files[entry.Name()] = string(body)
	}
	after, err := root.Lstat(".")
	if err != nil || !os.SameFile(before, after) || before.Mode() != after.Mode() {
		return nil, fmt.Errorf("child pack capability changed while reading")
	}
	return files, nil
}

// hasChildPackCapability validates the complete non-circular authorization
// proof before allowing a design to reach its grandparent workspace. Mere
// pack.yaml presence is never authority: the canonical generated inventory
// must hash correctly and a strict packmap must bind the same subsystem/hash.
func hasChildPackCapability(design string) (bool, error) {
	packDir := filepath.Join(design, "pack")
	info, err := os.Lstat(packDir)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("inspect child pack capability: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
		return false, fmt.Errorf("child pack capability %s must be a real directory", packDir)
	}
	files, err := readStrictPackFiles(packDir)
	if err != nil {
		return false, fmt.Errorf("read child pack capability: %w", err)
	}
	manifestBody, exists := files["pack.yaml"]
	if !exists {
		return false, fmt.Errorf("child pack capability has no pack/pack.yaml")
	}
	if !strings.HasPrefix(manifestBody, generatedPackHeader) {
		return false, fmt.Errorf("child pack capability pack/pack.yaml lacks the canonical generated header")
	}
	manifestPath := filepath.Join(packDir, "pack.yaml")
	manifest, err := strictYAMLMapping(manifestPath, []byte(manifestBody))
	if err != nil {
		return false, err
	}
	manifestKeys := []string{"pack_version", "pack_revision", "subsystem", "contract_module", "owns", "components", "boundaries", "delegated_invariants", "content_hash"}
	if err := exactKeys(manifestPath, manifest, manifestKeys); err != nil {
		return false, err
	}
	for _, field := range []struct {
		key     string
		minimum int
	}{{"pack_version", 1}, {"pack_revision", 1}} {
		key, minimum := field.key, field.minimum
		node := manifest[key]
		value, parseErr := strconv.Atoi(nodeValue(node, "!!int"))
		if parseErr != nil || value < minimum || key == "pack_version" && value != 1 {
			return false, fmt.Errorf("%s %s is invalid", manifestPath, key)
		}
	}
	subsystem, err := requiredString(manifestPath, manifest, "subsystem")
	if err != nil {
		return false, err
	}
	module, err := requiredString(manifestPath, manifest, "contract_module")
	if err != nil {
		return false, err
	}
	wantHash, err := requiredString(manifestPath, manifest, "content_hash")
	if err != nil || len(wantHash) != 64 || strings.ToLower(wantHash) != wantHash {
		return false, fmt.Errorf("%s content_hash must be 64 lowercase hexadecimal characters", manifestPath)
	}
	if _, err := hex.DecodeString(wantHash); err != nil {
		return false, fmt.Errorf("%s content_hash must be 64 lowercase hexadecimal characters", manifestPath)
	}
	for _, key := range []string{"owns", "components", "boundaries", "delegated_invariants"} {
		if err := requiredStringSequence(manifestPath, manifest, key); err != nil {
			return false, err
		}
	}
	wantNames := []string{"pack.yaml", "domain.modelith.yaml", "events.md", module + ".machine.json", module + ".tla", module + ".cfg"}
	sort.Strings(wantNames)
	gotNames := make([]string, 0, len(files))
	for name := range files {
		gotNames = append(gotNames, name)
	}
	sort.Strings(gotNames)
	if strings.Join(gotNames, "\x00") != strings.Join(wantNames, "\x00") {
		return false, fmt.Errorf("child pack capability inventory %v is not canonical %v", gotNames, wantNames)
	}
	if got := hashPackFiles(files); got != wantHash {
		return false, fmt.Errorf("child pack capability content hash mismatch")
	}

	mapPath := filepath.Join(design, "packmap.yaml")
	mapBody, err := readSnapshotRegularPath(mapPath, "child pack capability packmap.yaml", packCapabilityFileMaxBytes)
	if err != nil {
		return false, fmt.Errorf("read child pack capability packmap.yaml: %w", err)
	}
	mapInfo, err := os.Lstat(mapPath)
	if err != nil || mapInfo.Mode()&os.ModeSymlink != 0 || !mapInfo.Mode().IsRegular() {
		return false, fmt.Errorf("child pack capability packmap.yaml must be a regular file")
	}
	packmap, err := strictYAMLMapping(mapPath, mapBody)
	if err != nil {
		return false, err
	}
	if err := exactKeys(mapPath, packmap, []string{"subsystem", "pack_hash", "machine", "mapping"}); err != nil {
		return false, err
	}
	mapSubsystem, err := requiredString(mapPath, packmap, "subsystem")
	if err != nil || mapSubsystem != subsystem {
		return false, fmt.Errorf("child pack capability packmap subsystem does not match pack manifest")
	}
	mapHash, err := requiredString(mapPath, packmap, "pack_hash")
	if err != nil || mapHash != wantHash {
		return false, fmt.Errorf("child pack capability packmap hash does not match pack manifest")
	}
	if _, err := requiredString(mapPath, packmap, "machine"); err != nil {
		return false, err
	}
	mapping := packmap["mapping"]
	if mapping == nil || mapping.Kind != yaml.MappingNode || len(mapping.Content) == 0 {
		return false, fmt.Errorf("child pack capability packmap mapping must be a non-empty mapping")
	}
	seenMapping := map[string]bool{}
	for i := 0; i < len(mapping.Content); i += 2 {
		if mapping.Content[i].Tag != "!!str" || strings.TrimSpace(mapping.Content[i].Value) == "" || mapping.Content[i+1].Tag != "!!str" || strings.TrimSpace(mapping.Content[i+1].Value) == "" {
			return false, fmt.Errorf("child pack capability packmap mapping must contain non-empty string pairs")
		}
		if seenMapping[mapping.Content[i].Value] {
			return false, fmt.Errorf("child pack capability packmap mapping contains duplicate key %q", mapping.Content[i].Value)
		}
		seenMapping[mapping.Content[i].Value] = true
	}
	return true, nil
}

func nodeValue(node *yaml.Node, tag string) string {
	if node == nil || node.Kind != yaml.ScalarNode || node.Tag != tag {
		return ""
	}
	return node.Value
}
