package designlock

// Recovery inspection contract for interrupted design publications.
//
// RED phase (MAC-2n83): the crash helpers and control tests below compile
// against the existing hardened contract only. TestRecoveryReaderGuidance*
// pin the DESIGNED user surface: an interrupted publication must advertise
// the read-only `machinery recover` inspection path in addition to the
// writer-rerun instruction. The guidance test asserting the recover command
// fails on unmodified production; the rerun guidance and reader fail-closed
// controls pass today and must keep passing.

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

const recoveryFixtureWriter = "recover-fixture"
const recoveryFixtureRecovery = "rerun `machinery example-writer` with the same arguments"

func recoveryFixtureSeed(t *testing.T, design string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(design, "source.md"), []byte("design inputs must survive every recovery path\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(design, "stale.txt"), []byte("obsolete output\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(design, "generated.txt"), []byte("obsolete output\n"), 0o644); err != nil {
		t.Fatal(err)
	}
}

func recoveryFixtureExpected(design string) ([]OutputExpectation, error) {
	tree, err := ExpectTree(filepath.Join(design, "generated-tree"), map[string][]byte{"nested/report.txt": []byte("tree output body\n")}, 0o755, 0o644)
	if err != nil {
		return nil, err
	}
	return []OutputExpectation{
		ExpectFile(filepath.Join(design, "generated.txt"), []byte("generated by the interrupted writer\n"), 0o644),
		tree,
		ExpectAbsent(filepath.Join(design, "stale.txt")),
	}, nil
}

func recoveryWriteExact(path string, body []byte, mode os.FileMode) error {
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err := os.WriteFile(path, body, mode); err != nil {
		return err
	}
	return os.Chmod(path, mode)
}

func recoveryFixtureWriteAll(design string) error {
	if err := recoveryWriteExact(filepath.Join(design, "generated.txt"), []byte("generated by the interrupted writer\n"), 0o644); err != nil {
		return err
	}
	treeDir := filepath.Join(design, "generated-tree", "nested")
	if err := os.MkdirAll(treeDir, 0o755); err != nil {
		return err
	}
	if err := os.Chmod(filepath.Join(design, "generated-tree"), 0o755); err != nil {
		return err
	}
	if err := os.Chmod(treeDir, 0o755); err != nil {
		return err
	}
	if err := recoveryWriteExact(filepath.Join(treeDir, "report.txt"), []byte("tree output body\n"), 0o644); err != nil {
		return err
	}
	return os.Remove(filepath.Join(design, "stale.txt"))
}

func recoveryFixtureWritePartial(design string) error {
	return recoveryWriteExact(filepath.Join(design, "generated.txt"), []byte("generated by the interrupted writer\n"), 0o644)
}

// TestRecoveryCrashPublishHelper is a subprocess fixture. The parent test
// re-executes the package test binary with MACHINERY_RECOVERY_CRASH_DESIGN
// and MACHINERY_RECOVERY_CRASH_BOUNDARY set; this helper then performs one
// real designlock publication that dies by real process death
// (os.Exit(9), no deferred cleanup, no sentinel clear) at the requested
// meaningful publication boundary:
//
//	callback-start  sentinel installed, zero outputs written
//	mid-callback    first output exact, tree and deletion missing
//	pre-validation  every output exact, directly before post-callback proof
//	pre-clear       every output exact and twice validated, directly before
//	                the durable sentinel clear
//
// The same helper executes inside the Docker bind-mount integration lane
// container (linux cross-compiled) to reproduce a cross-identity publication.
func TestRecoveryCrashPublishHelper(t *testing.T) {
	design := os.Getenv("MACHINERY_RECOVERY_CRASH_DESIGN")
	boundary := os.Getenv("MACHINERY_RECOVERY_CRASH_BOUNDARY")
	if design == "" || boundary == "" {
		return
	}
	die := func() {
		syncDirectory(design)
		os.Exit(9)
	}
	switch boundary {
	case "pre-clear":
		testBeforeFinalOutputValidation = func() error { die(); return nil }
	case "pre-validation":
		testAfterPublishCallback = func() { die() }
	case "callback-start", "mid-callback":
	default:
		fmt.Fprintf(os.Stderr, "unknown recovery crash boundary %q\n", boundary)
		os.Exit(3)
	}
	expected, err := recoveryFixtureExpected(design)
	if err != nil {
		fmt.Fprintf(os.Stderr, "fixture expectations: %v\n", err)
		os.Exit(3)
	}
	lock, err := Acquire(design)
	if err != nil {
		fmt.Fprintf(os.Stderr, "fixture acquire: %v\n", err)
		os.Exit(3)
	}
	callbackErr := lock.PublishExpectedRooted(recoveryFixtureWriter, recoveryFixtureRecovery, expected, func(*OutputScope) error {
		if boundary == "callback-start" {
			die()
		}
		if boundary == "mid-callback" {
			if err := recoveryFixtureWritePartial(design); err != nil {
				return err
			}
			die()
		}
		if err := recoveryFixtureWriteAll(design); err != nil {
			return err
		}
		die()
		return nil
	})
	fmt.Fprintf(os.Stderr, "recovery crash helper completed without dying: callback=%v\n", callbackErr)
	os.Exit(3)
}

func recoveryCrashSubprocess(t *testing.T, boundary string) string {
	t.Helper()
	design := t.TempDir()
	recoveryFixtureSeed(t, design)
	executable, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()
	cmd := exec.CommandContext(ctx, executable, "-test.run=^TestRecoveryCrashPublishHelper$")
	cmd.Env = append(os.Environ(), "MACHINERY_RECOVERY_CRASH_DESIGN="+design, "MACHINERY_RECOVERY_CRASH_BOUNDARY="+boundary)
	out, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("recovery crash helper at %s completed without crashing: %s", boundary, out)
	}
	var exit *exec.ExitError
	if !errors.As(err, &exit) || exit.ExitCode() != 9 {
		t.Fatalf("recovery crash helper at %s did not die by process death: %v %s", boundary, err, out)
	}
	return design
}

// TestRecoverySubprocessCrashBoundariesBlockReaders is the fail-closed
// control: every real subprocess crash boundary above must leave residue that
// AcquireReader rejects before any gate read. This passes on unmodified
// production and must keep passing after recovery lands.
func TestRecoverySubprocessCrashBoundariesBlockReaders(t *testing.T) {
	for _, boundary := range []string{"callback-start", "mid-callback", "pre-validation", "pre-clear"} {
		t.Run(boundary, func(t *testing.T) {
			design := recoveryCrashSubprocess(t, boundary)
			if reader, err := AcquireReader(design); err == nil {
				_ = reader.Release()
				t.Fatal("reader acquired a design with interrupted publication residue")
			} else if !strings.Contains(err.Error(), "no gate reads were performed") {
				t.Fatalf("reader failure must be fail-closed before reads: %v", err)
			}
		})
	}
}

// TestRecoveryWriterResumeCompletesAfterSubprocessCrash is the writer-rerun
// control: the interrupted writer itself still recovers by re-entry with its
// exact identity. Passes on unmodified production; must keep passing.
func TestRecoveryWriterResumeCompletesAfterSubprocessCrash(t *testing.T) {
	design := recoveryCrashSubprocess(t, "pre-clear")
	lock, err := Acquire(design)
	if err != nil {
		t.Fatal(err)
	}
	if err := lock.ResumeExpected(recoveryFixtureWriter, recoveryFixtureRecovery); err != nil {
		t.Fatalf("writer resume after real subprocess crash: %v", err)
	}
	if err := lock.Release(); err != nil {
		t.Fatal(err)
	}
	reader, err := AcquireReader(design)
	if err != nil {
		t.Fatalf("reader remained blocked after writer resume: %v", err)
	}
	if err := reader.Release(); err != nil {
		t.Fatal(err)
	}
}

// TestRecoveryReaderGuidanceStillNamesWriterRerun is the rerun-guidance
// control: the fail-closed reader error keeps instructing the writer rerun.
// Passes on unmodified production.
func TestRecoveryReaderGuidanceStillNamesWriterRerun(t *testing.T) {
	design := recoveryCrashSubprocess(t, "pre-clear")
	_, err := AcquireReader(design)
	if err == nil {
		t.Fatal("reader acquired across an interrupted publication")
	}
	if !strings.Contains(err.Error(), "rerun") || !strings.Contains(err.Error(), recoveryFixtureRecovery) {
		t.Fatalf("reader guidance lost the writer rerun instruction: %v", err)
	}
}

// TestRecoveryReaderGuidanceAdvertisesRecoverCommand pins the DESIGNED
// surface (RED on unmodified production): a user facing an interrupted
// publication must be pointed at the read-only inspection command
// `machinery recover` for a safe diagnosis instead of manual sentinel
// deletion. Both the installed publication sentinel and the inner journal
// variants must advertise it.
func TestRecoveryReaderGuidanceAdvertisesRecoverCommand(t *testing.T) {
	t.Run("publication sentinel", func(t *testing.T) {
		design := recoveryCrashSubprocess(t, "pre-clear")
		_, err := AcquireReader(design)
		if err == nil {
			t.Fatal("reader acquired across an interrupted publication")
		}
		if !strings.Contains(err.Error(), "machinery recover") {
			t.Fatalf("reader guidance does not advertise the recover inspection command: %v", err)
		}
	})
	t.Run("inner transaction journal", func(t *testing.T) {
		design := t.TempDir()
		if err := os.MkdirAll(filepath.Join(design, "formal"), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(design, "formal/.machinery-formal-transaction.jsonl"), []byte("{}\n"), 0o600); err != nil {
			t.Fatal(err)
		}
		_, err := AcquireReader(design)
		if err == nil {
			t.Fatal("reader acquired across an interrupted inner transaction")
		}
		if !strings.Contains(err.Error(), "machinery recover") {
			t.Fatalf("journal guidance does not advertise the recover inspection command: %v", err)
		}
	})
}

// GREEN phase (MAC-2n83): contract tests for InspectRecovery and
// RecoverInterrupted themselves, exercising the exported recovery surface
// over the same real-subprocess crash fixtures defined above.

func recoveryReadSentinelBytes(t *testing.T, design string) []byte {
	t.Helper()
	body, err := os.ReadFile(filepath.Join(design, publishSentinel))
	if err != nil {
		t.Fatal(err)
	}
	return body
}

func recoveryDesignFingerprint(t *testing.T, design string) map[string]string {
	t.Helper()
	values, err := fingerprint(design)
	if err != nil {
		t.Fatal(err)
	}
	return values
}

func recoveryAssertEqualFingerprints(t *testing.T, before, after map[string]string) {
	t.Helper()
	if len(before) != len(after) {
		t.Fatalf("design inventory changed: %d -> %d entries", len(before), len(after))
	}
	if changed := firstFingerprintChange(before, after); changed != "" {
		t.Fatalf("design changed at %s", changed)
	}
}

func TestInspectRecoveryReportsFullyPublishedTransaction(t *testing.T) {
	design := recoveryCrashSubprocess(t, "pre-clear")
	report, err := InspectRecovery(design)
	if err != nil {
		t.Fatal(err)
	}
	if report.Action != RecoveryActionFinalize {
		t.Fatalf("action %s, want finalize; reasons=%v", report.Action, report.Reasons)
	}
	if report.Writer != recoveryFixtureWriter || report.RecoveryCommand != recoveryFixtureRecovery {
		t.Fatalf("writer identity wrong: %q %q", report.Writer, report.RecoveryCommand)
	}
	if report.InputInventory != "verified" || report.DesignInputDigest != report.InputFingerprint {
		t.Fatalf("input inventory %s digest %s recorded %s", report.InputInventory, report.DesignInputDigest, report.InputFingerprint)
	}
	if report.LiveWriter {
		t.Fatal("no writer is live after a real subprocess crash")
	}
	if len(report.Outputs) != 3 {
		t.Fatalf("expected the three declared outputs, got %v", report.Outputs)
	}
	for _, output := range report.Outputs {
		if output.Status != "match" {
			t.Fatalf("output %s status %s (%s)", output.Path, output.Status, output.Detail)
		}
	}
	if len(report.Journals) != 1 || report.Journals[0].Path != publishSentinel || report.Journals[0].Role != "publish-sentinel" || report.Journals[0].Status != "present" {
		t.Fatalf("journal inventory wrong: %v", report.Journals)
	}
}

func TestInspectRecoveryIsReadOnlyAcrossBoundaries(t *testing.T) {
	for _, boundary := range []string{"callback-start", "mid-callback", "pre-validation", "pre-clear"} {
		t.Run(boundary, func(t *testing.T) {
			design := recoveryCrashSubprocess(t, boundary)
			before := recoveryDesignFingerprint(t, design)
			sentinelBefore := recoveryReadSentinelBytes(t, design)
			report, err := InspectRecovery(design)
			if err != nil {
				t.Fatal(err)
			}
			if report.Action != RecoveryActionRerun && report.Action != RecoveryActionFinalize {
				t.Fatalf("boundary %s classified %s", boundary, report.Action)
			}
			recoveryAssertEqualFingerprints(t, before, recoveryDesignFingerprint(t, design))
			if !bytes.Equal(sentinelBefore, recoveryReadSentinelBytes(t, design)) {
				t.Fatal("inspection rewrote the publication sentinel")
			}
		})
	}
}

func TestInspectRecoveryClassifiesIncompletePublicationsForWriterRerun(t *testing.T) {
	for _, tc := range []struct {
		boundary string
		keyword  string
	}{
		{"callback-start", "digest"},
		{"mid-callback", "missing"},
	} {
		t.Run(tc.boundary, func(t *testing.T) {
			design := recoveryCrashSubprocess(t, tc.boundary)
			report, err := InspectRecovery(design)
			if err != nil {
				t.Fatal(err)
			}
			if report.Action != RecoveryActionRerun {
				t.Fatalf("action %s, want rerun-writer; reasons=%v", report.Action, report.Reasons)
			}
			joined := strings.Join(report.Reasons, "\n")
			if !strings.Contains(joined, tc.keyword) {
				t.Fatalf("reasons missing %q: %v", tc.keyword, report.Reasons)
			}
			if report.InputInventory != "verified" {
				t.Fatalf("inputs must still verify for an incomplete publication: %s", report.InputInventory)
			}
		})
	}
}

func TestInspectRecoveryRejectsTamperedSentinelAsConflict(t *testing.T) {
	design := recoveryCrashSubprocess(t, "pre-clear")
	sentinel := filepath.Join(design, publishSentinel)
	body := recoveryReadSentinelBytes(t, design)
	if err := os.WriteFile(sentinel, append(append([]byte(nil), body...), ' ', '\n'), 0o600); err != nil {
		t.Fatal(err)
	}
	report, err := InspectRecovery(design)
	if err != nil {
		t.Fatal(err)
	}
	if report.Action != RecoveryActionConflict {
		t.Fatalf("action %s, want conflict; reasons=%v", report.Action, report.Reasons)
	}
	if !strings.Contains(strings.Join(report.Reasons, "\n"), "invalid") {
		t.Fatalf("conflict reason must name the invalid sentinel: %v", report.Reasons)
	}
	if _, err := os.Stat(sentinel); err != nil {
		t.Fatalf("inspection must preserve even tampered evidence: %v", err)
	}
}

func TestInspectRecoveryDetectsInputInventoryMismatch(t *testing.T) {
	design := recoveryCrashSubprocess(t, "pre-clear")
	if err := os.WriteFile(filepath.Join(design, "source.md"), []byte("edited after the crash\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	report, err := InspectRecovery(design)
	if err != nil {
		t.Fatal(err)
	}
	if report.InputInventory != "mismatch" {
		t.Fatalf("input inventory %s, want mismatch", report.InputInventory)
	}
	if report.Action != RecoveryActionRerun {
		t.Fatalf("action %s, want rerun-writer", report.Action)
	}
}

func TestInspectRecoveryRefusesExternalTrackedInputAsUnwitnessable(t *testing.T) {
	design := t.TempDir()
	recoveryFixtureSeed(t, design)
	external := filepath.Join(t.TempDir(), "ext-input.txt")
	if err := os.WriteFile(external, []byte("tracked external input\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	lock, err := Acquire(design)
	if err != nil {
		t.Fatal(err)
	}
	if err := lock.TrackExternal(external); err != nil {
		t.Fatal(err)
	}
	expected, err := recoveryFixtureExpected(design)
	if err != nil {
		t.Fatal(err)
	}
	testBeforeFinalOutputValidation = func() error { return errors.New("simulated crash with tracked externals") }
	publishErr := lock.PublishExpectedRooted(recoveryFixtureWriter, recoveryFixtureRecovery, expected, func(*OutputScope) error {
		return recoveryFixtureWriteAll(design)
	})
	testBeforeFinalOutputValidation = nil
	if publishErr == nil {
		t.Fatal("simulated crash succeeded")
	}
	if err := lock.Release(); err != nil {
		t.Fatal(err)
	}
	report, err := InspectRecovery(design)
	if err != nil {
		t.Fatal(err)
	}
	if report.InputInventory != "mismatch" || report.Action != RecoveryActionRerun {
		t.Fatalf("tracked external input must be refused as unwitnessable: inventory=%s action=%s reasons=%v", report.InputInventory, report.Action, report.Reasons)
	}
}

func TestInspectRecoveryReportsLiveWriter(t *testing.T) {
	design := recoveryCrashSubprocess(t, "pre-clear")
	lock, err := Acquire(design)
	if err != nil {
		t.Fatal(err)
	}
	report, err := InspectRecovery(design)
	if err != nil {
		t.Fatal(err)
	}
	if !report.LiveWriter || report.Action != RecoveryActionRerun {
		t.Fatalf("live holder not detected: live=%t action=%s", report.LiveWriter, report.Action)
	}
	if !strings.Contains(strings.Join(report.Reasons, "\n"), "another process holds the design snapshot lock") {
		t.Fatalf("live-writer reason missing: %v", report.Reasons)
	}
	if err := lock.Release(); err != nil {
		t.Fatal(err)
	}
	report, err = InspectRecovery(design)
	if err != nil {
		t.Fatal(err)
	}
	if report.LiveWriter || report.Action != RecoveryActionFinalize {
		t.Fatalf("released holder still reported: live=%t action=%s", report.LiveWriter, report.Action)
	}
}

func TestInspectRecoveryReportsCleanAndInnerJournalDesigns(t *testing.T) {
	clean := t.TempDir()
	report, err := InspectRecovery(clean)
	if err != nil {
		t.Fatal(err)
	}
	if report.Action != RecoveryActionNone || len(report.Journals) != 0 {
		t.Fatalf("clean design misreported: %s %v", report.Action, report.Journals)
	}
	journaled := t.TempDir()
	if err := os.MkdirAll(filepath.Join(journaled, "formal"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(journaled, "formal/.machinery-formal-transaction.jsonl"), []byte("{}\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	report, err = InspectRecovery(journaled)
	if err != nil {
		t.Fatal(err)
	}
	if report.Action != RecoveryActionRerun || len(report.Journals) != 1 || report.Journals[0].Role != "interrupted-transaction-journal" {
		t.Fatalf("inner journal design misreported: %s %v", report.Action, report.Journals)
	}
}

func TestRecoverInterruptedCompletesAndIsIdempotent(t *testing.T) {
	for _, boundary := range []string{"pre-validation", "pre-clear"} {
		t.Run(boundary, func(t *testing.T) {
			design := recoveryCrashSubprocess(t, boundary)
			report, err := RecoverInterrupted(design)
			if err != nil {
				t.Fatalf("recovery of a fully published %s transaction failed: %v; reasons=%v", boundary, err, report.Reasons)
			}
			if report.Action != RecoveryActionNone {
				t.Fatalf("post-recovery action %s, want none", report.Action)
			}
			if _, err := os.Stat(filepath.Join(design, publishSentinel)); !errors.Is(err, os.ErrNotExist) {
				t.Fatalf("sentinel survived recovery: %v", err)
			}
			reader, err := AcquireReader(design)
			if err != nil {
				t.Fatalf("reader remained blocked after recovery: %v", err)
			}
			if err := reader.Release(); err != nil {
				t.Fatal(err)
			}
			report, err = RecoverInterrupted(design)
			if err != nil || report.Action != RecoveryActionNone {
				t.Fatalf("second recovery not a harmless no-op: %v %s", err, report.Action)
			}
		})
	}
}

func TestRecoverInterruptedRefusesAndPreservesEvidence(t *testing.T) {
	t.Run("partial publication", func(t *testing.T) {
		design := recoveryCrashSubprocess(t, "mid-callback")
		before := recoveryDesignFingerprint(t, design)
		sentinelBefore := recoveryReadSentinelBytes(t, design)
		report, err := RecoverInterrupted(design)
		if err == nil {
			t.Fatalf("partial publication recovered: %+v", report)
		}
		if !strings.Contains(err.Error(), "nothing was modified") {
			t.Fatalf("refusal must state preservation: %v", err)
		}
		if !strings.Contains(err.Error(), "missing") {
			t.Fatalf("refusal must explain the incomplete output: %v", err)
		}
		recoveryAssertEqualFingerprints(t, before, recoveryDesignFingerprint(t, design))
		if !bytes.Equal(sentinelBefore, recoveryReadSentinelBytes(t, design)) {
			t.Fatal("refusal rewrote the publication sentinel")
		}
	})
	t.Run("staged residue", func(t *testing.T) {
		design := recoveryCrashSubprocess(t, "pre-clear")
		stage := filepath.Join(design, publishSentinelStage)
		if err := os.WriteFile(stage, []byte("{\"version\":1}\n"), 0o600); err != nil {
			t.Fatal(err)
		}
		before := recoveryDesignFingerprint(t, design)
		report, err := RecoverInterrupted(design)
		if err == nil {
			t.Fatalf("staged residue recovered: %+v", report)
		}
		if report.Action != RecoveryActionRerun {
			t.Fatalf("staged residue classified %s", report.Action)
		}
		recoveryAssertEqualFingerprints(t, before, recoveryDesignFingerprint(t, design))
		if _, err := os.Stat(stage); err != nil {
			t.Fatalf("refusal discarded the staged evidence instead of leaving it to the writer rerun: %v", err)
		}
	})
	t.Run("symlink swap", func(t *testing.T) {
		design := recoveryCrashSubprocess(t, "pre-clear")
		outside := filepath.Join(t.TempDir(), "decoy.txt")
		if err := os.WriteFile(outside, []byte("generated by the interrupted writer\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		target := filepath.Join(design, "generated.txt")
		if err := os.Remove(target); err != nil {
			t.Fatal(err)
		}
		if err := os.Symlink(outside, target); err != nil {
			t.Fatal(err)
		}
		// The governed fingerprint refuses to witness a symlinked design (as
		// it must), so this subtest witnesses the evidence directly.
		witness := func() (string, os.FileInfo) {
			info, err := os.Lstat(target)
			if err != nil {
				t.Fatal(err)
			}
			link, err := os.Readlink(target)
			if err != nil {
				t.Fatal(err)
			}
			return link, info
		}
		linkBefore, infoBefore := witness()
		sentinelBefore := recoveryReadSentinelBytes(t, design)
		sourceBefore, err := os.ReadFile(filepath.Join(design, "source.md"))
		if err != nil {
			t.Fatal(err)
		}
		report, err := RecoverInterrupted(design)
		if err == nil {
			t.Fatalf("symlink swap recovered: %+v", report)
		}
		if !strings.Contains(err.Error(), "symlink") {
			t.Fatalf("refusal must name the symlink: %v", err)
		}
		linkAfter, infoAfter := witness()
		if linkBefore != linkAfter || !os.SameFile(infoBefore, infoAfter) {
			t.Fatal("refusal disturbed the swapped symlink evidence")
		}
		if !bytes.Equal(sentinelBefore, recoveryReadSentinelBytes(t, design)) {
			t.Fatal("refusal rewrote the publication sentinel")
		}
		if sourceAfter, err := os.ReadFile(filepath.Join(design, "source.md")); err != nil || !bytes.Equal(sourceAfter, sourceBefore) {
			t.Fatalf("refusal damaged design inputs: %v", err)
		}
	})
	t.Run("live writer", func(t *testing.T) {
		design := recoveryCrashSubprocess(t, "pre-clear")
		lock, err := Acquire(design)
		if err != nil {
			t.Fatal(err)
		}
		report, err := RecoverInterrupted(design)
		if err == nil {
			_ = lock.Release()
			t.Fatalf("live writer publication recovered: %+v", report)
		}
		if !strings.Contains(err.Error(), "another process holds the design snapshot lock") {
			t.Fatalf("refusal must name the concurrent writer: %v", err)
		}
		if err := lock.Release(); err != nil {
			t.Fatal(err)
		}
	})
}
