package designlock

// Recovery inspection contract for interrupted design publications.
//
// RED phase (MAC-2n83): the crash helpers and control tests below compile
// against the existing hardened contract only. TestRecoveryReaderGuidance*
// pin the DESIGNED user surface: an interrupted publication must advertise
// the read-only `machinery recover` inspection path in addition to the
// writer-rerun instruction. The guidance test asserting the recover command
// fails on unmodified production; the rerun guidance and reader fail-closed
// controls pass today and must keep passing.

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

const recoveryFixtureWriter = "recover-fixture"
const recoveryFixtureRecovery = "rerun `machinery example-writer` with the same arguments"

func recoveryFixtureSeed(t *testing.T, design string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(design, "source.md"), []byte("design inputs must survive every recovery path\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(design, "stale.txt"), []byte("obsolete output\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(design, "generated.txt"), []byte("obsolete output\n"), 0o644); err != nil {
		t.Fatal(err)
	}
}

func recoveryFixtureExpected(design string) ([]OutputExpectation, error) {
	tree, err := ExpectTree(filepath.Join(design, "generated-tree"), map[string][]byte{"nested/report.txt": []byte("tree output body\n")}, 0o755, 0o644)
	if err != nil {
		return nil, err
	}
	return []OutputExpectation{
		ExpectFile(filepath.Join(design, "generated.txt"), []byte("generated by the interrupted writer\n"), 0o644),
		tree,
		ExpectAbsent(filepath.Join(design, "stale.txt")),
	}, nil
}

func recoveryWriteExact(path string, body []byte, mode os.FileMode) error {
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err := os.WriteFile(path, body, mode); err != nil {
		return err
	}
	return os.Chmod(path, mode)
}

func recoveryFixtureWriteAll(design string) error {
	if err := recoveryWriteExact(filepath.Join(design, "generated.txt"), []byte("generated by the interrupted writer\n"), 0o644); err != nil {
		return err
	}
	treeDir := filepath.Join(design, "generated-tree", "nested")
	if err := os.MkdirAll(treeDir, 0o755); err != nil {
		return err
	}
	if err := os.Chmod(filepath.Join(design, "generated-tree"), 0o755); err != nil {
		return err
	}
	if err := os.Chmod(treeDir, 0o755); err != nil {
		return err
	}
	if err := recoveryWriteExact(filepath.Join(treeDir, "report.txt"), []byte("tree output body\n"), 0o644); err != nil {
		return err
	}
	return os.Remove(filepath.Join(design, "stale.txt"))
}

func recoveryFixtureWritePartial(design string) error {
	return recoveryWriteExact(filepath.Join(design, "generated.txt"), []byte("generated by the interrupted writer\n"), 0o644)
}

// TestRecoveryCrashPublishHelper is a subprocess fixture. The parent test
// re-executes the package test binary with MACHINERY_RECOVERY_CRASH_DESIGN
// and MACHINERY_RECOVERY_CRASH_BOUNDARY set; this helper then performs one
// real designlock publication that dies by real process death
// (os.Exit(9), no deferred cleanup, no sentinel clear) at the requested
// meaningful publication boundary:
//
//	callback-start  sentinel installed, zero outputs written
//	mid-callback    first output exact, tree and deletion missing
//	pre-validation  every output exact, directly before post-callback proof
//	pre-clear       every output exact and twice validated, directly before
//	                the durable sentinel clear
//
// The same helper executes inside the Docker bind-mount integration lane
// container (linux cross-compiled) to reproduce a cross-identity publication.
func TestRecoveryCrashPublishHelper(t *testing.T) {
	design := os.Getenv("MACHINERY_RECOVERY_CRASH_DESIGN")
	boundary := os.Getenv("MACHINERY_RECOVERY_CRASH_BOUNDARY")
	if design == "" || boundary == "" {
		return
	}
	die := func() {
		syncDirectory(design)
		os.Exit(9)
	}
	switch boundary {
	case "pre-clear":
		testBeforeFinalOutputValidation = func() error { die(); return nil }
	case "pre-validation":
		testAfterPublishCallback = func() { die() }
	case "callback-start", "mid-callback":
	default:
		fmt.Fprintf(os.Stderr, "unknown recovery crash boundary %q\n", boundary)
		os.Exit(3)
	}
	expected, err := recoveryFixtureExpected(design)
	if err != nil {
		fmt.Fprintf(os.Stderr, "fixture expectations: %v\n", err)
		os.Exit(3)
	}
	lock, err := Acquire(design)
	if err != nil {
		fmt.Fprintf(os.Stderr, "fixture acquire: %v\n", err)
		os.Exit(3)
	}
	callbackErr := lock.PublishExpectedRooted(recoveryFixtureWriter, recoveryFixtureRecovery, expected, func(*OutputScope) error {
		if boundary == "callback-start" {
			die()
		}
		if boundary == "mid-callback" {
			if err := recoveryFixtureWritePartial(design); err != nil {
				return err
			}
			die()
		}
		if err := recoveryFixtureWriteAll(design); err != nil {
			return err
		}
		die()
		return nil
	})
	fmt.Fprintf(os.Stderr, "recovery crash helper completed without dying: callback=%v\n", callbackErr)
	os.Exit(3)
}

func recoveryCrashSubprocess(t *testing.T, boundary string) string {
	t.Helper()
	design := t.TempDir()
	recoveryFixtureSeed(t, design)
	executable, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()
	cmd := exec.CommandContext(ctx, executable, "-test.run=^TestRecoveryCrashPublishHelper$")
	cmd.Env = append(os.Environ(), "MACHINERY_RECOVERY_CRASH_DESIGN="+design, "MACHINERY_RECOVERY_CRASH_BOUNDARY="+boundary)
	out, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("recovery crash helper at %s completed without crashing: %s", boundary, out)
	}
	var exit *exec.ExitError
	if !errors.As(err, &exit) || exit.ExitCode() != 9 {
		t.Fatalf("recovery crash helper at %s did not die by process death: %v %s", boundary, err, out)
	}
	return design
}

// TestRecoverySubprocessCrashBoundariesBlockReaders is the fail-closed
// control: every real subprocess crash boundary above must leave residue that
// AcquireReader rejects before any gate read. This passes on unmodified
// production and must keep passing after recovery lands.
func TestRecoverySubprocessCrashBoundariesBlockReaders(t *testing.T) {
	for _, boundary := range []string{"callback-start", "mid-callback", "pre-validation", "pre-clear"} {
		t.Run(boundary, func(t *testing.T) {
			design := recoveryCrashSubprocess(t, boundary)
			if reader, err := AcquireReader(design); err == nil {
				_ = reader.Release()
				t.Fatal("reader acquired a design with interrupted publication residue")
			} else if !strings.Contains(err.Error(), "no gate reads were performed") {
				t.Fatalf("reader failure must be fail-closed before reads: %v", err)
			}
		})
	}
}

// TestRecoveryWriterResumeCompletesAfterSubprocessCrash is the writer-rerun
// control: the interrupted writer itself still recovers by re-entry with its
// exact identity. Passes on unmodified production; must keep passing.
func TestRecoveryWriterResumeCompletesAfterSubprocessCrash(t *testing.T) {
	design := recoveryCrashSubprocess(t, "pre-clear")
	lock, err := Acquire(design)
	if err != nil {
		t.Fatal(err)
	}
	if err := lock.ResumeExpected(recoveryFixtureWriter, recoveryFixtureRecovery); err != nil {
		t.Fatalf("writer resume after real subprocess crash: %v", err)
	}
	if err := lock.Release(); err != nil {
		t.Fatal(err)
	}
	reader, err := AcquireReader(design)
	if err != nil {
		t.Fatalf("reader remained blocked after writer resume: %v", err)
	}
	if err := reader.Release(); err != nil {
		t.Fatal(err)
	}
}

// TestRecoveryReaderGuidanceStillNamesWriterRerun is the rerun-guidance
// control: the fail-closed reader error keeps instructing the writer rerun.
// Passes on unmodified production.
func TestRecoveryReaderGuidanceStillNamesWriterRerun(t *testing.T) {
	design := recoveryCrashSubprocess(t, "pre-clear")
	_, err := AcquireReader(design)
	if err == nil {
		t.Fatal("reader acquired across an interrupted publication")
	}
	if !strings.Contains(err.Error(), "rerun") || !strings.Contains(err.Error(), recoveryFixtureRecovery) {
		t.Fatalf("reader guidance lost the writer rerun instruction: %v", err)
	}
}

// TestRecoveryReaderGuidanceAdvertisesRecoverCommand pins the DESIGNED
// surface (RED on unmodified production): a user facing an interrupted
// publication must be pointed at the read-only inspection command
// `machinery recover` for a safe diagnosis instead of manual sentinel
// deletion. Both the installed publication sentinel and the inner journal
// variants must advertise it.
func TestRecoveryReaderGuidanceAdvertisesRecoverCommand(t *testing.T) {
	t.Run("publication sentinel", func(t *testing.T) {
		design := recoveryCrashSubprocess(t, "pre-clear")
		_, err := AcquireReader(design)
		if err == nil {
			t.Fatal("reader acquired across an interrupted publication")
		}
		if !strings.Contains(err.Error(), "machinery recover") {
			t.Fatalf("reader guidance does not advertise the recover inspection command: %v", err)
		}
	})
	t.Run("inner transaction journal", func(t *testing.T) {
		design := t.TempDir()
		if err := os.MkdirAll(filepath.Join(design, "formal"), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(design, "formal/.machinery-formal-transaction.jsonl"), []byte("{}\n"), 0o600); err != nil {
			t.Fatal(err)
		}
		_, err := AcquireReader(design)
		if err == nil {
			t.Fatal("reader acquired across an interrupted inner transaction")
		}
		if !strings.Contains(err.Error(), "machinery recover") {
			t.Fatalf("journal guidance does not advertise the recover inspection command: %v", err)
		}
	})
}
