---- MODULE PaymentPackRefinement ----
\* machinery-version: v0.3.4-dev
\* GENERATED by machinery pack refine. RECONCILED against the child machine
\* and the pack's contract machine; a drifted packmap fails generation.
\* Obligation: Payment (child) refines PaymentsContract (the contract the parent composition
\* instances). TLC checks Spec => C!Spec under the state mapping below.
EXTENDS Payment

Map(s) ==
  CASE s = "Requested" -> "Settling"
    [] s = "Captured" -> "Done"
    [] s = "Declined" -> "Done"
    [] s = "Refunded" -> "Done"

C == INSTANCE PaymentsContract WITH st <- Map(st)
CSpecHolds == C!Spec
====
