// The Stage-1 baseline generator behind `machinery baseline`, and the ratchet
// snapshot it writes. The generator reuses G4's own import scan (one discovery
// implementation, so the gate and the generator can never disagree), turns
// today's violations into ready-to-paste baseline: rules, and records every
// tolerated edge's offender files in design/ratchet.json. G4 then holds each
// baselined edge to that snapshot: a new offender file on an amnestied edge is
// an ERROR, which closes the classic "an allow rule amnesties the whole edge
// forever" hole in brownfield adoption.

package gates

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/RamXX/machinery/internal/artifactset"
)

// RatchetFile is the snapshot's filename inside the design directory. It is
// generated by `machinery baseline` and committed; hand edits defeat the
// ratchet, so the machinery plugin denies them.
const RatchetFile = "ratchet.json"

// Ratchet is the committed set-based snapshot: the offender files of every
// baselined (tolerated-violation) edge at the moment the baseline was taken.
type Ratchet struct {
	Date  string              `json:"date"`
	Edges map[string][]string `json:"edges"`
}

// LoadRatchet reads design/ratchet.json. A missing file is (nil, nil): the
// ratchet is optional until the contract carries baseline: rules.
func LoadRatchet(design string) (*Ratchet, error) {
	raw, err := readDesignFile(design, filepath.Join(design, RatchetFile))
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("%s is unreadable: %w", RatchetFile, err)
	}
	r, err := decodeRatchet(raw)
	if err != nil {
		return nil, fmt.Errorf("%s does not parse (rerun 'machinery baseline' rather than editing it): %w", RatchetFile, err)
	}
	return r, nil
}

func decodeRatchet(raw []byte) (*Ratchet, error) {
	dec := json.NewDecoder(bytes.NewReader(raw))
	start, err := dec.Token()
	if err != nil {
		return nil, err
	}
	if delim, ok := start.(json.Delim); !ok || delim != '{' {
		return nil, fmt.Errorf("root must be a JSON object")
	}
	r := &Ratchet{Edges: map[string][]string{}}
	seen := map[string]bool{}
	for dec.More() {
		tok, err := dec.Token()
		if err != nil {
			return nil, err
		}
		key, ok := tok.(string)
		if !ok {
			return nil, fmt.Errorf("object key must be a string")
		}
		if seen[key] {
			return nil, fmt.Errorf("duplicate root key %q", key)
		}
		seen[key] = true
		switch key {
		case "date":
			value, err := dec.Token()
			if err != nil {
				return nil, err
			}
			date, ok := value.(string)
			if !ok {
				return nil, fmt.Errorf("date must be a string")
			}
			r.Date = date
		case "edges":
			edges, err := decodeRatchetEdges(dec)
			if err != nil {
				return nil, err
			}
			r.Edges = edges
		default:
			return nil, fmt.Errorf("unknown root key %q (supported: date, edges)", key)
		}
	}
	if _, err := dec.Token(); err != nil {
		return nil, err
	}
	for _, required := range []string{"date", "edges"} {
		if !seen[required] {
			return nil, fmt.Errorf("missing required root key %q", required)
		}
	}
	var trailing any
	if err := dec.Decode(&trailing); err != io.EOF {
		if err == nil {
			return nil, fmt.Errorf("trailing JSON value after root object")
		}
		return nil, err
	}
	return r, nil
}

func decodeRatchetEdges(dec *json.Decoder) (map[string][]string, error) {
	start, err := dec.Token()
	if err != nil {
		return nil, fmt.Errorf("edges must be an object: %w", err)
	}
	if delim, ok := start.(json.Delim); !ok || delim != '{' {
		return nil, fmt.Errorf("edges must be an object of string arrays")
	}
	edges := map[string][]string{}
	for dec.More() {
		tok, err := dec.Token()
		if err != nil {
			return nil, err
		}
		edge, ok := tok.(string)
		if !ok {
			return nil, fmt.Errorf("edge key must be a string")
		}
		if _, duplicate := edges[edge]; duplicate {
			return nil, fmt.Errorf("duplicate edge key %q", edge)
		}
		start, err := dec.Token()
		if err != nil {
			return nil, err
		}
		if delim, ok := start.(json.Delim); !ok || delim != '[' {
			return nil, fmt.Errorf("edge %q must be an array of strings", edge)
		}
		files := []string{}
		for dec.More() {
			value, err := dec.Token()
			if err != nil {
				return nil, err
			}
			file, ok := value.(string)
			if !ok {
				return nil, fmt.Errorf("edge %q entries must be strings", edge)
			}
			files = append(files, file)
		}
		if _, err := dec.Token(); err != nil {
			return nil, err
		}
		edges[edge] = files
	}
	if _, err := dec.Token(); err != nil {
		return nil, err
	}
	return edges, nil
}

// WriteRatchet writes the snapshot deterministically (sorted keys via
// encoding/json, sorted file lists, trailing newline) so it diffs cleanly.
func WriteRatchet(design string, r *Ratchet) error {
	data, err := RenderRatchet(r)
	if err != nil {
		return err
	}
	return artifactset.CommitScoped(design, design, map[string][]byte{RatchetFile: data})
}

// WriteRatchetInSnapshot publishes a ratchet while the caller holds the
// design snapshot across BuildBaseline and this write.
func WriteRatchetInSnapshot(design string, r *Ratchet) error {
	data, err := RenderRatchet(r)
	if err != nil {
		return err
	}
	return artifactset.Commit(design, map[string][]byte{RatchetFile: data})
}

// RenderRatchet returns the exact deterministic bytes written by WriteRatchet.
func RenderRatchet(r *Ratchet) ([]byte, error) {
	for _, files := range r.Edges {
		sort.Strings(files)
	}
	data, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

// ProposedRule is one baseline: entry the generator suggests, with enough
// context for the dated comment a human pastes alongside it.
type ProposedRule struct {
	Edge    string // "src -> dst"
	Witness string
	More    int // offender files beyond the witness
}

// OrphanRef is a module-internal import that maps to no contract boundary,
// grouped for the external.rest_of_monolith suggestion.
type OrphanRef struct {
	Ref   string
	Files int
}

// BaselineReport is what `machinery baseline` prints and writes.
type BaselineReport struct {
	Date          string
	EdgesObserved int
	Proposed      []ProposedRule // edges violating today (undeclared or denied)
	Ratchet       *Ratchet       // snapshot of every tolerated-violation edge
	IgnoreGlobs   []string       // suggestions for source files outside every boundary
	Orphans       []OrphanRef    // imports that map to no boundary
	UnmappedFiles int
}

// BuildBaseline runs G4's scan and assembles the Stage-1 report. It does not
// write anything; the caller decides (the CLI writes the ratchet and prints
// the contract additions for a human to review and paste).
func BuildBaseline(design, impl, date string) (*BaselineReport, error) {
	scan := &importScan{}
	g := checkImports(design, impl, scan)
	if !scan.Complete {
		return nil, fmt.Errorf("baseline needs a scannable design and impl: %s", strings.Join(g.Errs, "; "))
	}
	if len(scan.WalkWarns) > 0 {
		// a ratchet snapshotted from a truncated corpus would amnesty less
		// than the real debt and then scream on the next full walk
		return nil, fmt.Errorf("baseline refuses a partial scan; make these subtrees readable or add them to the contract ignore list: %s", strings.Join(scan.WalkWarns, "; "))
	}
	rep := &BaselineReport{
		Date:          date,
		EdgesObserved: len(scan.Edges),
		Ratchet:       &Ratchet{Date: date, Edges: map[string][]string{}},
		UnmappedFiles: len(scan.UnmappedFiles),
	}
	for _, e := range scan.Edges {
		key := e.Src + " -> " + e.Dst
		switch e.Status {
		case "undeclared", "denied":
			rep.Proposed = append(rep.Proposed, ProposedRule{Edge: key, Witness: e.Witness, More: len(e.Files) - 1})
			rep.Ratchet.Edges[key] = e.Files
		case "baselined":
			// re-snapshot: an already-baselined edge stays ratcheted at its
			// CURRENT files (this is how a shrunk baseline is tightened)
			rep.Ratchet.Edges[key] = e.Files
		}
	}
	sort.Slice(rep.Proposed, func(i, j int) bool { return rep.Proposed[i].Edge < rep.Proposed[j].Edge })

	globs := map[string]bool{}
	for _, rel := range scan.UnmappedFiles {
		if i := strings.IndexByte(rel, '/'); i > 0 {
			globs[rel[:i]+"/**"] = true
		} else {
			globs[rel] = true
		}
	}
	for gl := range globs {
		rep.IgnoreGlobs = append(rep.IgnoreGlobs, gl)
	}
	sort.Strings(rep.IgnoreGlobs)

	for ref, files := range scan.OrphanRefs {
		rep.Orphans = append(rep.Orphans, OrphanRef{Ref: ref, Files: len(setOf(files))})
	}
	sort.Slice(rep.Orphans, func(i, j int) bool { return rep.Orphans[i].Ref < rep.Orphans[j].Ref })
	return rep, nil
}
