// The Stage-1 baseline generator behind `machinery baseline`, and the ratchet
// snapshot it writes. The generator reuses G4's own import scan (one discovery
// implementation, so the gate and the generator can never disagree), turns
// today's violations into ready-to-paste baseline: rules, and records every
// tolerated edge's offender files in design/ratchet.json. G4 then holds each
// baselined edge to that snapshot: a new offender file on an amnestied edge is
// an ERROR, which closes the classic "an allow rule amnesties the whole edge
// forever" hole in brownfield adoption.

package gates

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// RatchetFile is the snapshot's filename inside the design directory. It is
// generated by `machinery baseline` and committed; hand edits defeat the
// ratchet, so the machinery plugin denies them.
const RatchetFile = "ratchet.json"

// Ratchet is the committed set-based snapshot: the offender files of every
// baselined (tolerated-violation) edge at the moment the baseline was taken.
type Ratchet struct {
	Date  string              `json:"date"`
	Edges map[string][]string `json:"edges"`
}

// LoadRatchet reads design/ratchet.json. A missing file is (nil, nil): the
// ratchet is optional until the contract carries baseline: rules.
func LoadRatchet(design string) (*Ratchet, error) {
	raw, err := os.ReadFile(filepath.Join(design, RatchetFile))
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("%s is unreadable: %w", RatchetFile, err)
	}
	var r Ratchet
	if err := json.Unmarshal(raw, &r); err != nil {
		return nil, fmt.Errorf("%s does not parse (rerun 'machinery baseline' rather than editing it): %w", RatchetFile, err)
	}
	if r.Edges == nil {
		r.Edges = map[string][]string{}
	}
	return &r, nil
}

// WriteRatchet writes the snapshot deterministically (sorted keys via
// encoding/json, sorted file lists, trailing newline) so it diffs cleanly.
func WriteRatchet(design string, r *Ratchet) error {
	for _, files := range r.Edges {
		sort.Strings(files)
	}
	data, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(design, RatchetFile), append(data, '\n'), 0o644)
}

// ProposedRule is one baseline: entry the generator suggests, with enough
// context for the dated comment a human pastes alongside it.
type ProposedRule struct {
	Edge    string // "src -> dst"
	Witness string
	More    int // offender files beyond the witness
}

// OrphanRef is a module-internal import that maps to no contract boundary,
// grouped for the external.rest_of_monolith suggestion.
type OrphanRef struct {
	Ref   string
	Files int
}

// BaselineReport is what `machinery baseline` prints and writes.
type BaselineReport struct {
	Date          string
	EdgesObserved int
	Proposed      []ProposedRule // edges violating today (undeclared or denied)
	Ratchet       *Ratchet       // snapshot of every tolerated-violation edge
	IgnoreGlobs   []string       // suggestions for source files outside every boundary
	Orphans       []OrphanRef    // imports that map to no boundary
	UnmappedFiles int
}

// BuildBaseline runs G4's scan and assembles the Stage-1 report. It does not
// write anything; the caller decides (the CLI writes the ratchet and prints
// the contract additions for a human to review and paste).
func BuildBaseline(design, impl, date string) (*BaselineReport, error) {
	scan := &importScan{}
	g := checkImports(design, impl, scan)
	if !scan.Complete {
		return nil, fmt.Errorf("baseline needs a scannable design and impl: %s", strings.Join(g.Errs, "; "))
	}
	rep := &BaselineReport{
		Date:          date,
		EdgesObserved: len(scan.Edges),
		Ratchet:       &Ratchet{Date: date, Edges: map[string][]string{}},
		UnmappedFiles: len(scan.UnmappedFiles),
	}
	for _, e := range scan.Edges {
		key := e.Src + " -> " + e.Dst
		switch e.Status {
		case "undeclared", "denied":
			rep.Proposed = append(rep.Proposed, ProposedRule{Edge: key, Witness: e.Witness, More: len(e.Files) - 1})
			rep.Ratchet.Edges[key] = e.Files
		case "baselined":
			// re-snapshot: an already-baselined edge stays ratcheted at its
			// CURRENT files (this is how a shrunk baseline is tightened)
			rep.Ratchet.Edges[key] = e.Files
		}
	}
	sort.Slice(rep.Proposed, func(i, j int) bool { return rep.Proposed[i].Edge < rep.Proposed[j].Edge })

	globs := map[string]bool{}
	for _, rel := range scan.UnmappedFiles {
		if i := strings.IndexByte(rel, '/'); i > 0 {
			globs[rel[:i]+"/**"] = true
		} else {
			globs[rel] = true
		}
	}
	for gl := range globs {
		rep.IgnoreGlobs = append(rep.IgnoreGlobs, gl)
	}
	sort.Strings(rep.IgnoreGlobs)

	for ref, files := range scan.OrphanRefs {
		rep.Orphans = append(rep.Orphans, OrphanRef{Ref: ref, Files: len(setOf(files))})
	}
	sort.Slice(rep.Orphans, func(i, j int) bool { return rep.Orphans[i].Ref < rep.Orphans[j].Ref })
	return rep, nil
}
