// Package gates is the Go port of machinery_check.py: the deterministic gate
// suite (G2-c4, G3-machine, Gx-trace, G4-import). Pure static analysis over
// the design artifacts and (with --impl) the code.
package gates

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/RamXX/machinery/internal/alloy"
	"github.com/RamXX/machinery/internal/ir"
	"github.com/RamXX/machinery/internal/lint"
	"github.com/RamXX/machinery/internal/oracle"
	"github.com/RamXX/machinery/internal/pack"
	"github.com/RamXX/machinery/internal/tla"
	"github.com/RamXX/machinery/internal/version"
)

// --- Gate accumulator (mirrors machinery_check.Gate) ---

// Gate holds findings plus an explicit record of what was verified.
type Gate struct {
	Title        string
	Errs         []string
	Drift        []string
	Warns        []string
	Notes        []string
	Counts       map[string]int
	countOrder   []string // insertion order of count keys (matches Python dict)
	checkedExtra []string // preformatted checked: segments (zeros stay visible)
	// stampVersions collects the machinery versions stamped into the checked
	// committed artifacts (P-F10); VersionSkewNote surfaces any that differ
	// from the running binary. Absence of a stamp records nothing: pre-stamp
	// artifacts are not skew.
	stampVersions map[string]bool
}

// recordStamp notes the generator version stamped into a checked committed
// artifact ("" stamps, i.e. pre-stamp artifacts, record nothing).
func (g *Gate) recordStamp(text string) {
	v := version.StampOf(text)
	if v == "" {
		return
	}
	if g.stampVersions == nil {
		g.stampVersions = map[string]bool{}
	}
	g.stampVersions[v] = true
}

// VersionSkewNote returns the non-blocking INFO note `machinery check` prints
// when any checked committed artifact was generated by a machinery version
// other than the running one; "" when there is no skew. A missing stamp is a
// pre-stamp artifact, never skew. The note names the exact regeneration
// commands the design's own artifact families call for, so the reader never
// has to guess which generators apply.
func VersionSkewNote(design string, gs []*Gate) string {
	skew := map[string]bool{}
	for _, g := range gs {
		for v := range g.stampVersions {
			if v != version.Version {
				skew[v] = true
			}
		}
	}
	if len(skew) == 0 {
		return ""
	}
	var vs []string
	for v := range skew {
		vs = append(vs, v)
	}
	sort.Strings(vs)
	head := "note: artifacts generated by machinery " + strings.Join(vs, ", ") +
		", running " + version.Version + "; regenerate on upgrade"
	cmds := regenCommands(design)
	if len(cmds) > 0 {
		head += ":\n  " + strings.Join(cmds, "\n  ")
	}
	return head + "\nthe regeneration lands as its own dedicated stamp-only commit, never mixed with a design change"
}

// designSub joins a subpath onto the design path AS THE CALLER TYPED IT: the
// printed command is one a reader can paste back, so "./design" stays
// "./design" instead of being cleaned into something they did not type.
func designSub(design, sub string) string {
	return strings.TrimSuffix(design, "/") + "/" + sub
}

// regenCommands lists the regeneration commands that apply to the design, one
// per artifact family it actually carries, in the order a full regeneration
// runs them. A family the design does not have contributes no line.
func regenCommands(design string) []string {
	var cmds []string
	if len(sortedGlob(filepath.Join(design, "machines"), "*.machine.json")) > 0 {
		cmds = append(cmds, "machinery oracle "+designSub(design, "machines"))
	}
	formal := filepath.Join(design, "formal")
	if len(sortedGlob(formal, "*.relational.yaml")) > 0 {
		cmds = append(cmds, "machinery alloy "+design)
	}
	if len(sortedGlob(formal, "*.semantics.yaml")) > 0 ||
		len(sortedGlob(formal, "*.composition.yaml")) > 0 ||
		hasGeneratedTLA(formal) {
		cmds = append(cmds, "machinery verify-formal --gen-only "+design)
	}
	if pack.HasDecomposition(design) {
		cmds = append(cmds, "machinery pack generate "+design)
	}
	if _, err := os.Stat(filepath.Join(design, RatchetFile)); err == nil {
		cmds = append(cmds, "machinery baseline "+design+" --impl <dir>")
	}
	return cmds
}

// hasGeneratedTLA reports whether formal/ holds a machinery-generated .tla
// module (one carrying a version stamp). A hand-written .tla is not a
// regeneration obligation.
func hasGeneratedTLA(formal string) bool {
	for _, path := range sortedGlob(formal, "*.tla") {
		if version.StampOf(readOrEmpty(path)) != "" {
			return true
		}
	}
	return false
}

// NewGate builds an empty gate.
func NewGate(title string) *Gate {
	return &Gate{Title: title, Counts: map[string]int{}}
}

// startOrder initializes the count-order tracking (no-op; kept for clarity).
func (g *Gate) startOrder() {}

// Count increments label by n (default 1).
func (g *Gate) Count(label string, n ...int) {
	if _, ok := g.Counts[label]; !ok {
		g.countOrder = append(g.countOrder, label)
	}
	inc := 1
	if len(n) > 0 {
		inc = n[0]
	}
	g.Counts[label] += inc
}

// RequireNonzero adds an ERROR if label was never counted.
func (g *Gate) RequireNonzero(label, what string) {
	if g.Counts[label] == 0 {
		g.Errs = append(g.Errs, "nothing checked: "+what+"; an empty check is a failure, not a pass")
	}
}

// CheckedExtra appends a preformatted segment to the checked: line. Unlike
// Count, the segment is emitted verbatim even when the numbers inside are
// zero: a zero that must stay visible in every run (per-pack boundary-event
// counts) would otherwise vanish with the zero-count suppression.
func (g *Gate) CheckedExtra(segment string) {
	g.checkedExtra = append(g.checkedExtra, segment)
}

// Emit prints the gate like Python (ERRS, DRIFT, warns, notes, checked:, ok).
// Returns the number of blocking findings (errs + drift).
func (g *Gate) Emit(out io.Writer) int {
	fmt.Fprintf(out, "== %s ==\n", g.Title)
	for _, e := range g.Errs {
		fmt.Fprintf(out, "  ERROR  %s\n", e)
	}
	for _, d := range g.Drift {
		fmt.Fprintf(out, "  DRIFT  %s\n", d)
	}
	for _, w := range g.Warns {
		fmt.Fprintf(out, "  warn   %s\n", w)
	}
	for _, a := range g.Notes {
		fmt.Fprintf(out, "  note   %s\n", a)
	}
	var parts []string
	for _, k := range g.countOrder {
		v := g.Counts[k]
		if v != 0 {
			parts = append(parts, fmt.Sprintf("%d %s", v, k))
		}
	}
	parts = append(parts, g.checkedExtra...)
	checked := strings.Join(parts, ", ")
	if checked == "" {
		fmt.Fprintln(out, "  checked: nothing")
	} else {
		fmt.Fprintf(out, "  checked: %s\n", checked)
	}
	if len(g.Errs) == 0 && len(g.Drift) == 0 && len(g.Warns) == 0 {
		fmt.Fprintln(out, "  ok")
	}
	return len(g.Errs) + len(g.Drift)
}

// --- helpers ---

func readOrEmpty(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return string(data)
}

// readFileOrErr reads path for a gate. An absent file is "" (the callers'
// own existence logic owns that case), but a file that EXISTS and cannot be
// read is a hard ERROR naming the file: silently treating an unreadable
// artifact as empty produces wrong diagnoses (NG-9).
func readFileOrErr(path string, g *Gate) string {
	data, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			g.Errs = append(g.Errs, path+" is unreadable: "+err.Error())
		}
		return ""
	}
	return string(data)
}

// modeRe matches the BUILD.md template's mandatory mode declaration line.
var modeRe = regexp.MustCompile(`(?m)^Mode:\s*(full|manifest)\b`)

// headingContains reports whether any markdown heading line contains the
// (lowercase) needle.
func headingContains(text, needle string) bool {
	for _, line := range strings.Split(text, "\n") {
		if strings.HasPrefix(line, "#") && strings.Contains(strings.ToLower(line), needle) {
			return true
		}
	}
	return false
}

// isPersisted reports whether a placement-table persistence cell means the
// machine's state survives the process (and so needs a migration protocol).
func isPersisted(cell string) bool {
	c := strings.ToLower(strings.TrimSpace(cell))
	switch {
	case c == "" || c == "-" || c == "none" || c == "n/a":
		return false
	case strings.Contains(c, "in-memory") || strings.Contains(c, "in memory") || strings.Contains(c, "ephemeral"):
		return false
	}
	return true
}

// sortedGlobExt lists <dir>/*<ext> sorted; empty when dir does not exist.
func sortedGlobExt(dir, ext string) []string {
	entries, _ := os.ReadDir(dir)
	var out []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ext) {
			out = append(out, filepath.Join(dir, e.Name()))
		}
	}
	sort.Strings(out)
	return out
}

// tokenIn mirrors _token_in: whole-token containment (inv-1 must not match inv-12).
func tokenIn(token, text string) bool {
	// re.search(rf"(?<![A-Za-z0-9_-]){token}(?![A-Za-z0-9_-])", text)
	// Implement as a manual scan over token boundaries.
	idx := 0
	for {
		i := strings.Index(text[idx:], token)
		if i < 0 {
			return false
		}
		pos := idx + i
		beforeOK := pos == 0 || !isTokenChar(text[pos-1])
		afterOK := pos+len(token) == len(text) || !isTokenChar(text[pos+len(token)])
		if beforeOK && afterOK {
			return true
		}
		idx = pos + 1
	}
}

func isTokenChar(b byte) bool {
	return (b >= 'A' && b <= 'Z') || (b >= 'a' && b <= 'z') || (b >= '0' && b <= '9') || b == '-' || b == '_'
}

// --- contract (G2-c4) ---

var (
	edgeRuleRe = regexp.MustCompile(`^"?\s*([^\s"]+)\s*->\s*([^\s"#]+)`)
	dslDeclRe  = regexp.MustCompile(`^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(person|softwareSystem|container|component)\b(.*)$`)
	// dslBlockTagsRe matches the block-statement spelling of tags inside an
	// element body: `tags "Database"` / `tags "Database" "Queue"`.
	dslBlockTagsRe = regexp.MustCompile(`^\s*tags\s+(".*)$`)
	// dslQuotedRe blanks quoted strings for brace bookkeeping.
	dslQuotedRe = regexp.MustCompile(`"[^"]*"`)
	// mitigation tokens allow hyphens inside segments: external ids like
	// external.rest-of-monolith must be able to satisfy their own row
	mitTokRe = regexp.MustCompile("`([A-Za-z_][A-Za-z0-9_-]*(?:\\.[A-Za-z_][A-Za-z0-9_-]*)*)`")
	kebabRe  = regexp.MustCompile("`([a-z][a-z0-9]*(?:-[a-z0-9]+)+)`")
)

func loadContract(archPath string, g *Gate) *ir.Value {
	if _, err := os.Stat(archPath); err != nil {
		g.Errs = append(g.Errs, filepath.Base(archPath)+" does not exist")
		return nil
	}
	data, err := os.ReadFile(archPath)
	if err != nil {
		g.Errs = append(g.Errs, filepath.Base(archPath)+" is unreadable: "+err.Error())
		return nil
	}
	fence, ok := ir.ContractFence(string(data))
	if !ok {
		g.Errs = append(g.Errs, "no Architecture Contract found (need a ```yaml fence under a heading containing 'Architecture Contract', starting with contract_version)")
		return nil
	}
	c, err := ir.LoadYAML([]byte(fence))
	if err != nil {
		g.Errs = append(g.Errs, "Architecture Contract is not valid YAML: "+err.Error())
		return nil
	}
	co := c.AsObject()
	if co == nil {
		g.Errs = append(g.Errs, "Architecture Contract yaml is not a mapping (got a list or scalar)")
		return nil
	}
	if _, ok := co.Get("contract_version"); !ok {
		g.Errs = append(g.Errs, "Architecture Contract has no contract_version")
		return nil
	}
	// the version's VALUE is checked, not just its presence: v1 contracts
	// mislabeled as current used to pass silently
	if v := co.Get2("contract_version"); v == nil || v.Kind != ir.KindNumber || string(v.AsNumber()) != "2" {
		got := "?"
		if v != nil {
			got = goReprValue(v)
		}
		g.Errs = append(g.Errs, "contract_version "+got+" is not supported; this toolchain checks contract v2 (element bindings, externals, ignore)")
		return nil
	}
	if co.Get2("boundaries") == nil {
		g.Errs = append(g.Errs, "Architecture Contract declares no boundaries")
		return nil
	}
	return c
}

// contractEdges parses src->dst rules. g may be nil (a G4-only run parses the
// rules a second time and must not duplicate G2's findings): unparseable rules
// are then skipped silently here because G2 reports them.
func contractEdges(rules *ir.Object, key string, g *Gate) [][2]string {
	var out [][2]string
	v := rules.Get2(key)
	if v == nil {
		return out
	}
	for _, e := range v.AsArray() {
		s := e.AsString()
		m := edgeRuleRe.FindStringSubmatch(s)
		if m != nil {
			out = append(out, [2]string{m[1], m[2]})
		} else if g != nil {
			g.Errs = append(g.Errs, fmt.Sprintf("unparseable %s rule: %s (expected 'src -> dst')", key, ir.Repr(s)))
		}
	}
	return out
}

func dslElements(dslPath string, g *Gate) map[string]dslEl {
	return dslElementsOf(readFileOrErr(dslPath, g))
}

// dslElementsOf parses element declarations out of a workspace.dsl text.
// dslElements reads the file (and reports a read error) and delegates here, so
// a caller that already holds the text (the drawn-edge check needs the same
// text for its relationship lines) parses the model the one way.
//
// Tags come from BOTH legal Structurizr spellings: the inline argument on the
// declaration line and a `tags "..."` statement inside the element's block.
// Reading only the inline form once let a block-tagged Database/Queue element
// dodge the infra-mitigation obligations G2 keys off these tags.
func dslElementsOf(text string) map[string]dslEl {
	els := map[string]dslEl{}
	type openEl struct {
		name  string
		depth int
	}
	var stack []openEl
	depth := 0
	for _, line := range strings.Split(text, "\n") {
		if m := dslDeclRe.FindStringSubmatch(line); m != nil {
			name, kind, rest := m[1], m[2], m[3]
			args := quoteStrings(rest)
			tagIdx := 3
			if kind == "person" || kind == "softwareSystem" {
				tagIdx = 2
			}
			tags := map[string]bool{}
			if len(args) > tagIdx {
				for _, t := range strings.Split(args[tagIdx], ",") {
					tags[strings.TrimSpace(t)] = true
				}
			}
			display := name
			if len(args) > 0 {
				display = args[0]
			}
			els[name] = dslEl{Kind: kind, Tags: tags, Display: display}
			if strings.HasSuffix(strings.TrimSpace(line), "{") {
				stack = append(stack, openEl{name: name, depth: depth})
			}
		} else if m := dslBlockTagsRe.FindStringSubmatch(line); m != nil && len(stack) > 0 {
			el := els[stack[len(stack)-1].name]
			for _, q := range quoteStrings(m[1]) {
				for _, t := range strings.Split(q, ",") {
					el.Tags[strings.TrimSpace(t)] = true
				}
			}
		}
		// brace bookkeeping with quoted content blanked, so a brace inside a
		// description string does not unbalance the element stack
		bare := dslQuotedRe.ReplaceAllString(line, `""`)
		depth += strings.Count(bare, "{") - strings.Count(bare, "}")
		for len(stack) > 0 && depth <= stack[len(stack)-1].depth {
			stack = stack[:len(stack)-1]
		}
	}
	return els
}

type dslEl struct {
	Kind    string
	Tags    map[string]bool
	Display string
}

func quoteStrings(s string) []string {
	var out []string
	inQuote := false
	var cur strings.Builder
	for _, r := range s {
		if r == '"' {
			if inQuote {
				out = append(out, cur.String())
				cur.Reset()
			}
			inQuote = !inQuote
		} else if inQuote {
			cur.WriteRune(r)
		}
	}
	return out
}

// CheckC4 implements G2-c4.
func CheckC4(design string) *Gate {
	g := NewGate("G2-c4  Architecture Contract")
	g.startOrder()
	arch := filepath.Join(design, "ARCHITECTURE.md")
	c := loadContract(arch, g)
	if c == nil {
		return g
	}
	co := c.AsObject()
	boundaries := objSlice(co.Get2("boundaries"))
	externals := objSlice(co.Get2("externals"))

	var ids []string
	for _, b := range boundaries {
		bo := b.AsObject()
		if bo == nil || bo.GetString("id") == "" {
			g.Errs = append(g.Errs, "boundary without an id: "+goReprValue(b))
			continue
		}
		ids = append(ids, bo.GetString("id"))
		g.Count("boundaries")
		if bo.Get2("code") == nil {
			g.Errs = append(g.Errs, fmt.Sprintf("boundary %s declares no code globs; G4 cannot map it", ir.Repr(bo.GetString("id"))))
		}
	}
	for _, bid := range uniqueDuplicates(ids) {
		if countStr(ids, bid) > 1 {
			g.Errs = append(g.Errs, fmt.Sprintf("duplicate boundary id %s", ir.Repr(bid)))
		}
	}
	var extIDs []string
	for _, x := range externals {
		xo := x.AsObject()
		if xo == nil || xo.GetString("id") == "" {
			g.Errs = append(g.Errs, "externals entry without an id: "+goReprValue(x))
			continue
		}
		extIDs = append(extIDs, xo.GetString("id"))
		g.Count("externals")
	}
	declared := setOf(ids)
	for _, x := range extIDs {
		declared[x] = true
	}

	rules := co.GetObject("dependency_rules")
	if rules == nil {
		rules = ir.NewObject()
	}
	allow := contractEdges(rules, "allow", g)
	deny := contractEdges(rules, "deny", g)
	baseline := contractEdges(rules, "baseline", g)
	// wildcard rules resolve to no concrete node, so the graph checks below
	// (acyclicity, transitive reach) run on the concrete edges only
	allowConcrete := dropWildcardEdges(allow)
	g.Count("allow rules", len(allow))
	g.Count("transitive pairs", transitivePairs(allowConcrete))
	g.Count("deny rules", len(deny))
	g.Count("baseline rules", len(baseline))
	checkProvisions(boundaries, declared, allowConcrete, g)
	// baseline is an enumerated-edges ratchet: a wildcard rule would amnesty
	// the whole edge space (a `* -> *` once silently passed contract-DENIED
	// edges, GATE-7). Wildcards belong in allow/deny only.
	for _, e := range baseline {
		if strings.Contains(e[0], "*") || strings.Contains(e[1], "*") {
			g.Errs = append(g.Errs, fmt.Sprintf("baseline rule %s -> %s contains a wildcard; baseline: is an enumerated-edges ratchet (run 'machinery baseline' to enumerate today's edges; wildcards belong in allow/deny only)", e[0], e[1]))
		}
	}
	all := append(append(append([][2]string{}, allow...), deny...), baseline...)
	for _, e := range all {
		for _, side := range e {
			if strings.Contains(side, "*") {
				continue
			}
			if !declared[side] {
				hint := ""
				if strings.HasPrefix(side, "external") {
					hint = " (declare it under externals:)"
				}
				g.Errs = append(g.Errs, fmt.Sprintf("rule references undeclared boundary %s%s", ir.Repr(side), hint))
			}
		}
	}
	denySet := edgeSet(deny)
	for _, e := range allow { // slice order, not map order: deterministic output
		if denySet[e] {
			g.Errs = append(g.Errs, fmt.Sprintf("edge %s -> %s is both allowed and denied", e[0], e[1]))
			denySet[e] = false // report each edge once even if listed twice
		}
	}
	// allow+baseline contradicts (an allowed edge is not a violation, so there
	// is nothing to amnesty); deny+baseline is legitimate and recommended: the
	// deny records the intent, the baseline records the tolerated debt
	baseSet := edgeSet(baseline)
	for _, e := range allow {
		if baseSet[e] {
			g.Errs = append(g.Errs, fmt.Sprintf("edge %s -> %s is both allowed and baselined; baseline marks tolerated violations, an allowed edge needs no amnesty", e[0], e[1]))
			baseSet[e] = false
		}
	}
	// the allow graph must be acyclic: a dependency cycle between boundaries
	// destroys modularity and makes atomic change impossible, and a declared
	// cycle cannot be an accident, so it is a hard ERROR. A cycle that closes
	// only once baseline: edges are unioned in is the ratchet's tolerated
	// debt, warned rather than errored so the burn-down stays visible.
	_, allowAdj := depGraph(allowConcrete)
	allowCycles := cyclicSCCs(allowConcrete)
	reportedCycles := map[string]bool{}
	for _, scc := range allowCycles {
		members := strings.Join(scc, ", ")
		reportedCycles[members] = true
		if len(scc) == 1 {
			g.Errs = append(g.Errs, fmt.Sprintf("allow rule %s -> %s is a self-cycle; a boundary cannot depend on itself; remove the rule or split the boundary", scc[0], scc[0]))
			continue
		}
		g.Errs = append(g.Errs, fmt.Sprintf("dependency cycle among %s in allow rules (%s); break the cycle by extracting the shared dependency into its own boundary, or by inverting one edge", members, cyclePath(scc, allowAdj)))
	}
	unionEdges := append(append([][2]string{}, allowConcrete...), dropWildcardEdges(baseline)...)
	_, unionAdj := depGraph(unionEdges)
	for _, scc := range cyclicSCCs(unionEdges) {
		members := strings.Join(scc, ", ")
		if reportedCycles[members] {
			continue
		}
		g.Warns = append(g.Warns, fmt.Sprintf("dependency cycle among %s closes only through baseline edges (%s); this is ratchet debt to burn down, not declared intent; the cycle disappears with the baselined edge", members, cyclePath(scc, unionAdj)))
	}

	// dependency assertions: the contract states negative reachability
	// claims and this gate proves them against the same closure the
	// acyclicity check walks. A prose note ("domains never import each
	// other") is a claim nothing traverses; an assertion fails the moment
	// it stops being true. A path in the allow graph is a hard ERROR
	// (declared intent contradicts the claim); a path that closes only
	// through baseline edges is the ratchet's tolerated debt, warned like
	// baseline-closed cycles.
	asserts := objSlice(rules.Get2("assert"))
	for _, a := range asserts {
		ao := a.AsObject()
		if ao == nil {
			g.Errs = append(g.Errs, "unparseable assert rule: "+goReprValue(a)+" (expected '- no_path: src -> dst')")
			continue
		}
		for _, kind := range ao.Keys() {
			if kind == "_comment" {
				continue
			}
			if kind != "no_path" {
				g.Errs = append(g.Errs, fmt.Sprintf("unknown assertion kind %s (supported: no_path)", ir.Repr(kind)))
				continue
			}
			val := ao.GetString(kind)
			m := edgeRuleRe.FindStringSubmatch(val)
			if m == nil {
				g.Errs = append(g.Errs, fmt.Sprintf("unparseable no_path assertion: %s (expected 'src -> dst')", ir.Repr(val)))
				continue
			}
			src, dst := m[1], m[2]
			if strings.Contains(src, "*") || strings.Contains(dst, "*") {
				g.Errs = append(g.Errs, fmt.Sprintf("no_path assertion %s -> %s contains a wildcard; an assertion is a concrete claim about named boundaries", src, dst))
				continue
			}
			undeclared := false
			for _, side := range [2]string{src, dst} {
				if !declared[side] {
					g.Errs = append(g.Errs, fmt.Sprintf("no_path assertion references undeclared boundary %s", ir.Repr(side)))
					undeclared = true
				}
			}
			if undeclared {
				continue
			}
			g.Count("no_path assertions")
			if p := reachPath(allowAdj, src, dst); p != nil {
				g.Errs = append(g.Errs, fmt.Sprintf("no_path assertion %s -> %s fails: the allow graph reaches it (%s); remove an edge on the path or retract the assertion", src, dst, strings.Join(p, " -> ")))
			} else if p := reachPath(unionAdj, src, dst); p != nil {
				g.Warns = append(g.Warns, fmt.Sprintf("no_path assertion %s -> %s holds in allow rules but closes through baseline edges (%s); ratchet debt to burn down, not declared intent", src, dst, strings.Join(p, " -> ")))
			}
		}
	}

	// unused-mechanism coverage facts (notes, never findings): a zero is
	// invisible in the zero-suppressed counts, and an unengaged mechanism
	// has a way of being depended on by prose notes anyway. One line per
	// declared capacity that is zero.
	exposing := 0
	for _, b := range boundaries {
		if bo := b.AsObject(); bo != nil && len(objSlice(bo.Get2("exposes"))) > 0 {
			exposing++
		}
	}
	g.Count("boundaries with exposes", exposing)
	if exposing == 0 {
		g.Notes = append(g.Notes, "exposes: declared by no boundary; G4 constrains imports at boundary granularity only (mechanism unused)")
	}
	if len(baseline) == 0 {
		g.Notes = append(g.Notes, "baseline: no rules; the ratchet holds no tolerated debt (mechanism unused)")
	}
	if len(asserts) == 0 {
		g.Notes = append(g.Notes, "assert: no dependency assertions; negative reachability claims live only in prose (mechanism unused)")
	}

	dslPath := filepath.Join(design, "workspace.dsl")
	if _, err := os.Stat(dslPath); err != nil {
		g.Errs = append(g.Errs, "workspace.dsl does not exist; the contract has no model to bind to")
		return g
	}
	dslText := readFileOrErr(dslPath, g)
	els := dslElementsOf(dslText)
	g.Count("dsl elements", len(els))
	if len(els) == 0 {
		g.Errs = append(g.Errs, "workspace.dsl parsed but no elements found")
	}
	// the relationships the diagram DRAWS are held to the same dependency
	// rules G4 holds the code's imports to (see dsledges.go)
	checkDrawnEdges(g, dslText, els, boundaries, externals, allow, deny, baseline)

	for _, b := range boundaries {
		bo := b.AsObject()
		if bo == nil || bo.GetString("id") == "" {
			continue
		}
		el := bo.GetString("element")
		if el == "" {
			el = lastSegment(bo.GetString("id"))
		}
		if _, ok := els[el]; !ok {
			g.Errs = append(g.Errs, fmt.Sprintf("boundary %s maps to no workspace.dsl element (looked for %s; set element: explicitly if the id differs)", ir.Repr(bo.GetString("id")), ir.Repr(el)))
		} else {
			g.Count("boundaries bound to dsl")
		}
	}
	for _, x := range externals {
		xo := x.AsObject()
		if xo == nil || xo.GetString("id") == "" {
			continue
		}
		el := xo.GetString("element")
		if el != "" {
			if _, ok := els[el]; !ok {
				g.Errs = append(g.Errs, fmt.Sprintf("external %s maps to element %s not in workspace.dsl", ir.Repr(xo.GetString("id")), ir.Repr(el)))
			}
		}
	}

	// mitigation coverage
	required := map[string]string{}
	for _, x := range externals {
		xo := x.AsObject()
		if xo != nil && xo.GetString("id") != "" {
			required[xo.GetString("id")] = xo.GetString("element")
		}
	}
	infraTags := map[string]bool{"Database": true, "Queue": true, "External": true}
	infra := map[string]bool{}
	for name, e := range els {
		for t := range e.Tags {
			if infraTags[t] {
				infra[name] = true
			}
		}
	}
	text := readFileOrErr(arch, g)
	// EVERY header-matching table counts, as with the event and interface
	// contracts: a design may split its mitigation posture across sections
	// (transition-only dependencies in their own table, say), and the
	// first-match locator silently discharged every later table's rows of
	// their obligation (PACK-1 shared-locator semantics). Rows aggregate the
	// way the event scan's do: counts accumulate across tables and coverage is
	// a set, so a dependency named in either table is covered once.
	var mitRows [][]string
	for _, tbl := range ir.ParseMdTables(text) {
		hl := strings.ToLower(strings.Join(tbl.Header, " "))
		if strings.Contains(hl, "failure") && strings.Contains(hl, "mitigation") {
			mitRows = append(mitRows, tbl.Rows...)
		}
	}
	covered := map[string]bool{}
	for _, r := range mitRows {
		if len(r) == 0 {
			continue
		}
		g.Count("mitigation rows")
		for _, m := range mitTokRe.FindAllStringSubmatch(r[0], -1) {
			tok := m[1]
			if _, ok := els[tok]; ok {
				covered[tok] = true
			} else if _, ok := required[tok]; ok {
				covered[tok] = true
			} else {
				g.Errs = append(g.Errs, "mitigation row names `"+tok+"`, which is neither a workspace.dsl element nor a declared external")
			}
		}
	}
	need := map[string]bool{}
	for k := range required {
		need[k] = true
	}
	for k := range infra {
		need[k] = true
	}
	if len(need) > 0 && len(mitRows) == 0 {
		g.Errs = append(g.Errs, "no mitigation table found (header needs 'failure' and 'mitigation' columns) although the design declares infrastructure dependencies")
	}
	var needSorted []string
	for k := range need {
		needSorted = append(needSorted, k)
	}
	sort.Strings(needSorted)
	for _, dep := range needSorted {
		alt := required[dep]
		if covered[dep] || (alt != "" && covered[alt]) {
			g.Count("dependencies with mitigation rows")
		} else {
			g.Errs = append(g.Errs, "infrastructure dependency `"+dep+"` has no mitigation row (name it in the first column, backticked)")
		}
	}

	// the NFR record's shell is a three-item closed list; its content stays
	// attested (see nfr.go)
	checkNFRRecord(g, text)
	// every event-contract table states where its rows were enumerated from,
	// the same rule Gs holds the legacy surface ledger to (see eventsource.go)
	checkEventTableSources(g, text)
	// and every row answers its columns and names participants the model
	// declares; the rows were counted and never read (see eventcells.go)
	checkEventCells(g, text, els, required)
	// opt-in artifacts: the adoption-closure and action-ownership tables
	// activate on their own presence, like the declared embeds
	checkAdoptionClosure(g, text, els, required, covered)
	checkActionOwnership(g, design, text, els, declared)

	checkInterfaceContracts(g, text, allowConcrete, declared)

	// bus/queue coupling is invisible to G4-import; the event-contract table
	// is the governing artifact, so a queue-coupled design must have one
	queueCoupled := false
	for name, e := range els {
		if e.Tags["Queue"] {
			queueCoupled = true
			_ = name
		}
	}
	if queueCoupled {
		// EVERY header-matching table counts: designs legitimately split the
		// event contract into several tables, and the first-match locator
		// silently ignored the rest (PACK-1 shared-locator semantics)
		found := false
		for _, tbl := range eventContractTables(text) {
			found = true
			g.Count("event contracts", len(tbl.Rows))
		}
		if !found {
			g.Errs = append(g.Errs, "the model has a Queue-tagged element but ARCHITECTURE.md has no event-contract table (columns: producer, consumer, payload, delivery, ordering, dedupe); bus coupling is invisible to G4-import, so this table is its governing artifact")
		} else {
			// a header with zero rows governs nothing; the queue coupling is
			// then entirely unchecked
			g.RequireNonzero("event contracts", "the event-contract table has no rows although the model has a Queue-tagged element")
		}
	}

	g.RequireNonzero("boundaries", "no boundaries parsed")
	g.RequireNonzero("dsl elements", "no workspace.dsl elements parsed")
	return g
}

// --- interface contracts (G2-c4) ---

var (
	// noContractWaiverRe waives the interface contract of one edge, with its
	// reason captured. Distinct from '(no machine: ...)' and
	// '(not placed: ...)': one generic waiver token would let an answer to one
	// question silently discharge another.
	noContractWaiverRe = regexp.MustCompile(`\(no contract:\s*([^)]*)\)`)
	// ifaceEdgeRe is the whole-segment edge grammar: exactly one
	// 'from -> to' pair, ids in the contract's own vocabulary. Anchored, so a
	// chain ("a -> b -> c") or a stray word fails loudly instead of being
	// half-read.
	ifaceEdgeRe = regexp.MustCompile(`^([A-Za-z_][A-Za-z0-9_.\-]*)\s*->\s*([A-Za-z_][A-Za-z0-9_.\-]*)$`)
)

// edgeText renders an edge the way the contract writes it.
func edgeText(e [2]string) string { return e[0] + " -> " + e[1] }

// parseEdgeCell reads an interface-contract edge cell. Grammar: one or more
// 'from -> to' pairs separated by commas, ids optionally backticked,
// annotations (including the waiver) only in parentheses. Everything that is
// not an exact pair comes back as malformed rather than being skipped: a cell
// the parser half-understands is the way a table starts lying.
func parseEdgeCell(cell string) (pairs [][2]string, malformed []string) {
	s := parenAnnotationRe.ReplaceAllString(cell, " ")
	s = strings.ReplaceAll(s, "`", " ")
	for _, seg := range strings.Split(s, ",") {
		seg = strings.Join(strings.Fields(seg), " ")
		if seg == "" {
			continue
		}
		if m := ifaceEdgeRe.FindStringSubmatch(seg); m != nil {
			pairs = append(pairs, [2]string{m[1], m[2]})
			continue
		}
		malformed = append(malformed, seg)
	}
	return pairs, malformed
}

// checkInterfaceContracts holds the interface-contract table against the
// contract's own allow rules. Both directions, and both are checkable because
// the obliged set is CLOSED: dependency_rules.allow enumerates every boundary
// crossing the design permits.
//
//   - every concrete allow edge has a contract row (shape, errors,
//     idempotency, all answered) or a '(no contract: <reason>)' waiver;
//   - every edge a row names is an allow edge. A contract for an edge the
//     design denies, never declared, or only baselined is drift: the table
//     would describe an interface the architecture does not have.
//
// A wildcard allow rule names no concrete pair and so carries no obligation,
// exactly as it carries none in the acyclicity and reachability checks.
// What stays attested: whether the stated shape, error set, and idempotency
// rule are semantically RIGHT. The gate holds the row and its columns.
func checkInterfaceContracts(g *Gate, text string, allow [][2]string, declared map[string]bool) {
	contracted := map[[2]string]bool{}
	waived := map[[2]string]bool{}
	var namedOrder [][2]string
	named := map[[2]string]bool{}
	found := false
	for _, tbl := range ir.ParseMdTables(text) {
		hl := strings.ToLower(strings.Join(tbl.Header, " "))
		subject := strings.Contains(hl, "edge") || strings.Contains(hl, "crossing")
		if !subject || !strings.Contains(hl, "shape") ||
			!strings.Contains(hl, "error") || !strings.Contains(hl, "idempot") {
			continue
		}
		// EVERY header-matching table counts, as with the event contract: a
		// design may split its interfaces across sections, and a first-match
		// locator would silently ignore the rest
		found = true
		ei := colContaining(tbl.Header, "edge")
		if ei < 0 {
			ei = colContaining(tbl.Header, "crossing")
		}
		cols := map[string]int{
			"shape":       colContaining(tbl.Header, "shape"),
			"errors":      colContaining(tbl.Header, "error"),
			"idempotency": colContaining(tbl.Header, "idempot"),
		}
		for _, r := range tbl.Rows {
			if len(r) == 0 {
				continue
			}
			cell := ""
			if ei >= 0 && ei < len(r) {
				cell = r[ei]
			}
			pairs, malformed := parseEdgeCell(cell)
			for _, bad := range malformed {
				if strings.Contains(bad, "*") {
					g.Errs = append(g.Errs, "interface-contract row edge "+ir.Repr(bad)+" uses a wildcard; a contract is a concrete claim about one named pair")
				} else {
					g.Errs = append(g.Errs, "interface-contract row edge "+ir.Repr(bad)+" is not a 'from -> to' pair; the edge cell holds one or more pairs separated by commas")
				}
			}
			if len(pairs) == 0 {
				if len(malformed) == 0 {
					g.Errs = append(g.Errs, "interface-contract row names no edge; the edge column holds one or more 'from -> to' pairs")
				}
				continue
			}
			for _, p := range pairs {
				if !named[p] {
					named[p] = true
					namedOrder = append(namedOrder, p)
				}
			}
			if m := noContractWaiverRe.FindStringSubmatch(cell); m != nil {
				// the row states the crossing needs no interface contract here
				// (the child design carries it, say). There is no shape to
				// demand, so the other columns are not read. An empty reason is
				// an unanswered design question, reported once so one defect
				// never cascades into a second finding on the same edge.
				for _, p := range pairs {
					waived[p] = true
				}
				if strings.TrimSpace(m[1]) == "" {
					g.Errs = append(g.Errs, "interface-contract waiver for edge `"+edgeText(pairs[0])+"` names no reason; write '(no contract: <reason>)'")
				}
				continue
			}
			for _, col := range []string{"shape", "errors", "idempotency"} {
				i := cols[col]
				if i < 0 || i >= len(r) || strings.TrimSpace(r[i]) == "" {
					g.Errs = append(g.Errs, "interface-contract row for edge `"+edgeText(pairs[0])+"` leaves "+col+" empty; an unanswered column is not a contract")
				}
			}
			for _, p := range pairs {
				contracted[p] = true
			}
		}
	}
	if !found {
		if len(allow) > 0 {
			g.Errs = append(g.Errs, fmt.Sprintf("ARCHITECTURE.md has no interface-contract table (a header naming edge, shape, errors, and idempotency); the contract's %d allow edge(s) can be traced to no interface contract", len(allow)))
		}
		return
	}
	allowSet := edgeSet(allow)
	for _, p := range namedOrder {
		if allowSet[p] {
			continue
		}
		hint := ""
		for _, side := range p {
			if !declared[side] {
				hint = " (`" + side + "` is not a declared boundary or external)"
				break
			}
		}
		g.Errs = append(g.Errs, "interface-contract row names edge `"+edgeText(p)+"`, which no allow rule declares"+hint+"; a contract for an edge the design forbids, never declared, or only baselined describes an interface the architecture does not have")
	}
	for _, e := range allow { // slice order, not map order: deterministic output
		switch {
		case contracted[e]:
			g.Count("edges contracted")
		case waived[e]:
			g.Count("edges waived")
		default:
			g.Errs = append(g.Errs, "allow edge `"+edgeText(e)+"` has no interface-contract row and no '(no contract: <reason>)' waiver; every boundary crossing states its shape, errors, and idempotency")
		}
	}
}

// colContaining locates a column by substring, the same forgiving rule the
// table-detection header scan uses, so a header that names a column can always
// find it.
func colContaining(header []string, needle string) int {
	for i, h := range header {
		if strings.Contains(strings.ToLower(h), needle) {
			return i
		}
	}
	return -1
}

func objSlice(v *ir.Value) []*ir.Value {
	if v == nil || v.Kind != ir.KindArray {
		return nil
	}
	return v.AsArray()
}

func goReprValue(v *ir.Value) string { return ir.Repr(v) }

func edgeSet(edges [][2]string) map[[2]string]bool {
	m := map[[2]string]bool{}
	for _, e := range edges {
		m[e] = true
	}
	return m
}

// depGraph builds a deterministic adjacency view of concrete rule edges:
// sorted unique node list, sorted deduplicated successor lists. Everything
// downstream iterates these slices, never a map, so output never varies.
func depGraph(edges [][2]string) ([]string, map[string][]string) {
	nodeSet := map[string]bool{}
	for _, e := range edges {
		nodeSet[e[0]], nodeSet[e[1]] = true, true
	}
	var nodes []string
	for n := range nodeSet {
		nodes = append(nodes, n)
	}
	sort.Strings(nodes)
	adj := map[string][]string{}
	seen := map[[2]string]bool{}
	for _, e := range edges {
		if seen[e] {
			continue
		}
		seen[e] = true
		adj[e[0]] = append(adj[e[0]], e[1])
	}
	for k := range adj {
		sort.Strings(adj[k])
	}
	return nodes, adj
}

// cyclicSCCs returns the cyclic strongly connected components of the edge
// graph: every SCC of size > 1, plus every self-loop. Members are sorted and
// the components are sorted by member list, so identical input always
// produces byte-identical findings.
func cyclicSCCs(edges [][2]string) [][]string {
	nodes, adj := depGraph(edges)
	index := map[string]int{}
	low := map[string]int{}
	onStack := map[string]bool{}
	var stack []string
	next := 0
	var out [][]string
	var connect func(v string)
	connect = func(v string) {
		index[v], low[v] = next, next
		next++
		stack = append(stack, v)
		onStack[v] = true
		for _, w := range adj[v] {
			if _, visited := index[w]; !visited {
				connect(w)
				if low[w] < low[v] {
					low[v] = low[w]
				}
			} else if onStack[w] && index[w] < low[v] {
				low[v] = index[w]
			}
		}
		if low[v] != index[v] {
			return
		}
		var scc []string
		for {
			w := stack[len(stack)-1]
			stack = stack[:len(stack)-1]
			onStack[w] = false
			scc = append(scc, w)
			if w == v {
				break
			}
		}
		selfLoop := false
		for _, w := range adj[v] {
			if w == v {
				selfLoop = true
			}
		}
		if len(scc) > 1 || selfLoop {
			sort.Strings(scc)
			out = append(out, scc)
		}
	}
	for _, v := range nodes {
		if _, visited := index[v]; !visited {
			connect(v)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		return strings.Join(out[i], ", ") < strings.Join(out[j], ", ")
	})
	return out
}

// cyclePath renders one representative cycle through the SCC, starting and
// ending at its first (sorted) member. BFS restricted to the SCC with sorted
// successor order finds a shortest such cycle deterministically.
func cyclePath(scc []string, adj map[string][]string) string {
	start := scc[0]
	members := setOf(scc)
	for _, w := range adj[start] {
		if w == start {
			return start + " -> " + start
		}
	}
	parent := map[string]string{}
	visited := map[string]bool{start: true}
	queue := []string{start}
	for len(queue) > 0 {
		u := queue[0]
		queue = queue[1:]
		if u != start {
			for _, w := range adj[u] {
				if w != start {
					continue
				}
				var rev []string
				for v := u; v != start; v = parent[v] {
					rev = append(rev, v)
				}
				path := []string{start}
				for i := len(rev) - 1; i >= 0; i-- {
					path = append(path, rev[i])
				}
				return strings.Join(append(path, start), " -> ")
			}
		}
		for _, w := range adj[u] {
			if members[w] && !visited[w] {
				visited[w] = true
				parent[w] = u
				queue = append(queue, w)
			}
		}
	}
	return start // unreachable: an SCC member always closes back to start
}

// reachPath returns a shortest src -> ... -> dst path of one or more edges
// over adj, or nil when dst is unreachable from src. BFS with the sorted
// successor lists depGraph builds, so identical input always produces the
// same witness path.
func reachPath(adj map[string][]string, src, dst string) []string {
	parent := map[string]string{}
	visited := map[string]bool{}
	var queue []string
	for _, w := range adj[src] {
		if !visited[w] {
			visited[w] = true
			parent[w] = src
			queue = append(queue, w)
		}
	}
	for len(queue) > 0 {
		u := queue[0]
		queue = queue[1:]
		if u == dst {
			var rev []string
			for v := u; v != src; v = parent[v] {
				rev = append(rev, v)
			}
			path := []string{src}
			for i := len(rev) - 1; i >= 0; i-- {
				path = append(path, rev[i])
			}
			if len(path) == 1 { // src == dst through a self-loop
				path = append(path, dst)
			}
			return path
		}
		for _, w := range adj[u] {
			if !visited[w] {
				visited[w] = true
				parent[w] = u
				queue = append(queue, w)
			}
		}
	}
	return nil
}

// transitivePairs counts the ordered boundary pairs (src, dst) connected by a
// path of one or more concrete allow edges. Reported next to the declared
// allow-rule count: when the closure materially exceeds the declared rules, a
// shared boundary is laundering dependencies between boundaries the contract
// claims are independent. A reported fact, never a finding.
func transitivePairs(edges [][2]string) int {
	nodes, adj := depGraph(edges)
	n := 0
	for _, src := range nodes {
		reach := map[string]bool{}
		frontier := append([]string{}, adj[src]...)
		for len(frontier) > 0 {
			v := frontier[len(frontier)-1]
			frontier = frontier[:len(frontier)-1]
			if reach[v] {
				continue
			}
			reach[v] = true
			frontier = append(frontier, adj[v]...)
		}
		n += len(reach)
	}
	return n
}

// uniqueDuplicates returns the unique values in first-occurrence order (the
// caller filters to count>1); deterministic so error order never varies.
func uniqueDuplicates(xs []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, x := range xs {
		if !seen[x] {
			seen[x] = true
			out = append(out, x)
		}
	}
	return out
}

func countStr(xs []string, x string) int {
	n := 0
	for _, e := range xs {
		if e == x {
			n++
		}
	}
	return n
}

func setOf(xs []string) map[string]bool {
	m := map[string]bool{}
	for _, x := range xs {
		m[x] = true
	}
	return m
}

func lastSegment(s string) string {
	if i := strings.LastIndex(s, "."); i >= 0 {
		return s[i+1:]
	}
	return s
}

// --- machines (G3-machine) ---

// CheckMachines implements G3-machine.
func CheckMachines(design string) *Gate {
	g := NewGate("G3-machine  machines + oracle")
	g.startOrder()
	mdir := filepath.Join(design, "machines")
	files := sortedGlob(mdir, "*.machine.json")
	if len(files) == 0 {
		g.Errs = append(g.Errs, "no *.machine.json under "+mdir)
		return g
	}
	for _, path := range files {
		base := filepath.Base(path)
		m, err := ir.LoadMachineJSON(path)
		if err != nil {
			g.Errs = append(g.Errs, err.Error())
			continue
		}
		g.Count("machines")
		errs, warns, notes, counts := lint.LintMachine(m, base)
		g.Errs = append(g.Errs, errs...)
		g.Warns = append(g.Warns, warns...)
		g.Notes = append(g.Notes, notes...)
		g.Count("transitions", counts.Transitions)

		// S11: the structural lint and the TLA generator must admit the same
		// machine subset, so G3 runs the generator's own admissibility pass
		// (tla.Check, a thin wrapper over Generate: one validator, one
		// truth). A machine G3 passes is a machine verify-formal can
		// generate; the refusal carries the generator's own message so the
		// operator sees one vocabulary at either phase.
		if err := tla.Check(path); err != nil {
			g.Errs = append(g.Errs, base+": "+err.Error())
		} else {
			g.Count("tla-generable")
		}

		var exhaustive []string
		for _, s := range ir.WalkStates(m.AsObject().Get2("states"), "") {
			if s.Node != nil && s.Node.Kind == ir.KindObject {
				note := strings.TrimSpace(s.Node.AsObject().GetString("_exhaustive"))
				if note != "" {
					exhaustive = append(exhaustive, s.Name)
				}
			}
		}
		if len(exhaustive) > 0 {
			g.Count("states relying on unproven _exhaustive liveness", len(exhaustive))
			sort.Strings(exhaustive)
			g.Warns = append(g.Warns, base+": liveness for "+strings.Join(exhaustive, ", ")+
				" rests on an UNPROVEN _exhaustive claim (guards are erased in the TLA+ model, so TLC cannot check it); verify the guard set is provably total, or add an unguarded fallback branch so the liveness proof becomes sound")
		}

		opath := machineSibling(path, ".oracle.md")
		fresh := oracle.Render(m, path)
		if _, err := os.Stat(opath); err != nil {
			g.Errs = append(g.Errs, base+": no committed oracle ("+filepath.Base(opath)+"); run machinery oracle")
		} else if committed, err := os.ReadFile(opath); err != nil {
			g.Errs = append(g.Errs, base+": committed oracle is unreadable: "+err.Error())
		} else if g.recordStamp(string(committed)); version.Strip(string(committed)) != version.Strip(fresh) {
			// the stamp line is stripped from BOTH sides: a version-only skew
			// is surfaced by VersionSkewNote, never as DRIFT (P-F10)
			g.Drift = append(g.Drift, base+": committed oracle is stale (differs from a fresh generation); rerun machinery oracle")
		} else {
			g.Count("oracles fresh")
		}

		mpath := machineSibling(path, ".matrix.md")
		if _, err := os.Stat(mpath); err != nil {
			g.Warns = append(g.Warns, base+": no matrix file; named-unit contracts are unchecked (transitions are covered by the generated oracle)")
			continue
		}
		mtext := readFileOrErr(mpath, g)
		merrs, drift, nrows := lint.ReconcileMatrix(m, mtext, base)
		g.Errs = append(g.Errs, merrs...)
		g.Drift = append(g.Drift, drift...)
		g.Count("matrix rows reconciled", nrows)
		// S8: overlapping guards on one branch list argue about the same
		// invariant, so their order carries meaning the state must state.
		CheckBranchOrder(g, m, mtext, base)
		declared := lint.NamedUnitNames(mtext)
		guards, actions, actors := lint.MachineUnitNames(m)
		for _, pair := range []struct {
			kind  string
			names map[string]bool
		}{{"guard", guards}, {"action", actions}, {"actor", actors}} {
			var sorted []string
			for n := range pair.names {
				sorted = append(sorted, n)
			}
			sort.Strings(sorted)
			for _, name := range sorted {
				if declared[name] {
					g.Count("named units covered")
				} else {
					g.Drift = append(g.Drift, base+": "+pair.kind+" "+ir.Repr(name)+" has no named-unit contract row in "+filepath.Base(mpath))
				}
			}
		}
	}
	g.RequireNonzero("machines", "no machines parsed")
	g.RequireNonzero("transitions", "no transitions parsed")
	// S5 (v1 scope): dotted `Machine.state` references in annotation strings
	// and matrix prose must name real states, events, or units; the
	// narrative layer rots silently otherwise. Warnings only.
	CheckNameRot(g, design)
	return g
}

func sortedGlob(dir, pattern string) []string {
	entries, _ := os.ReadDir(dir)
	var out []string
	for _, e := range entries {
		if !e.IsDir() {
			matched, _ := filepath.Match(pattern, e.Name())
			if matched {
				out = append(out, filepath.Join(dir, e.Name()))
			}
		}
	}
	sort.Strings(out)
	return out
}

// machineSibling swaps a *.machine.json path's suffix for a sibling
// artifact's (".oracle.md", ".matrix.md").
func machineSibling(path, newExt string) string {
	return path[:len(path)-len(".machine.json")] + newExt
}

// --- traceability (Gx-trace) ---

func loadModelith(design string, g *Gate) *ir.Value {
	entries, _ := os.ReadDir(design)
	var paths []string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".modelith.yaml") {
			paths = append(paths, filepath.Join(design, e.Name()))
		}
	}
	if len(paths) == 0 {
		g.Errs = append(g.Errs, "no *.modelith.yaml in the design directory")
		return nil
	}
	if len(paths) > 1 {
		var names []string
		for _, p := range paths {
			names = append(names, filepath.Base(p))
		}
		sort.Strings(names)
		g.Errs = append(g.Errs, "multiple modelith models: "+strings.Join(names, ", "))
		return nil
	}
	data, err := os.ReadFile(paths[0])
	if err != nil {
		g.Errs = append(g.Errs, filepath.Base(paths[0])+": invalid YAML: "+err.Error())
		return nil
	}
	v, err := ir.LoadYAML(data)
	if err != nil {
		g.Errs = append(g.Errs, filepath.Base(paths[0])+": invalid YAML: "+err.Error())
		return nil
	}
	if v.AsObject() == nil {
		g.Errs = append(g.Errs, filepath.Base(paths[0])+": not a yaml mapping (empty file?)")
		return nil
	}
	return v
}

// CheckTraceability implements Gx-trace.
func CheckTraceability(design string) *Gate {
	g := NewGate("Gx-trace  cross-layer traceability")
	g.startOrder()
	dm := loadModelith(design, g)
	if dm == nil {
		return g
	}
	dmo := dm.AsObject()
	enums := map[string][]string{}
	if ev := dmo.Get2("enums"); ev != nil {
		for _, k := range ev.AsObject().Keys() {
			var vals []string
			for _, vv := range ev.AsObject().Get2(k).AsObject().Get2("values").AsArray() {
				vals = append(vals, vv.AsObject().GetString("name"))
			}
			enums[k] = vals
		}
	}
	entities := dmo.GetObject("entities")
	if entities.Len() == 0 {
		g.Errs = append(g.Errs, "modelith model declares no entities; an empty domain model is a failure, not a pass")
		return g
	}
	g.Count("entities", entities.Len())

	invIDs := map[string]bool{}
	for _, i := range objSlice(dmo.Get2("invariants")) {
		invIDs[i.AsObject().GetString("id")] = true
	}
	actionsByEntity := map[string]map[string]bool{}
	enumByEntity := map[string]string{}
	allActions := map[string]bool{}
	preservedIDs := map[string]bool{}
	for _, ename := range entities.Keys() {
		e := entities.Get2(ename).AsObject()
		acts := map[string]bool{}
		for _, a := range objSlice(e.Get2("actions")) {
			if a.Kind == ir.KindObject {
				acts[a.AsObject().GetString("name")] = true
				for _, pv := range listStrings(a.AsObject().Get2("preserves")) {
					preservedIDs[pv] = true
				}
			} else {
				acts[a.AsString()] = true
			}
		}
		actionsByEntity[ename] = acts
		for a := range acts {
			allActions[a] = true
		}
		for _, i := range objSlice(e.Get2("invariants")) {
			invIDs[i.AsObject().GetString("id")] = true
		}
		for _, a := range objSlice(e.Get2("attributes")) {
			ao := a.AsObject()
			if _, ok := enums[ao.GetString("type")]; ok {
				name := ao.GetString("name")
				if name == "status" || name == "stage" || name == "state" {
					enumByEntity[ename] = ao.GetString("type")
				}
			}
		}
	}

	mdir := filepath.Join(design, "machines")
	machineFiles := sortedGlob(mdir, "*.machine.json")
	if len(machineFiles) == 0 {
		g.Errs = append(g.Errs, "no machines under "+mdir+" to trace")
		return g
	}

	machineNames := map[string]bool{}
	claimed := map[string]bool{}
	for _, path := range machineFiles {
		base := filepath.Base(path)
		name := strings.TrimSuffix(base, ".machine.json")
		machineNames[name] = true
		m, err := ir.LoadMachineJSON(path)
		if err != nil {
			g.Errs = append(g.Errs, err.Error())
			continue
		}
		mo := m.AsObject()
		entity := mo.GetString("_lifecycle_of")
		if entity == "" {
			if _, ok := entities.Get(name); ok {
				entity = name
			}
		}
		role := mo.GetString("_role")
		if role == "operational" {
			entity = ""
		}
		if entity == "" && role != "operational" {
			g.Errs = append(g.Errs, base+": maps to no Modelith entity and is not declared operational (set _lifecycle_of: <Entity> or _role: operational)")
			continue
		}
		if role == "operational" {
			g.Count("operational machines")
			continue
		}
		if _, ok := entities.Get(entity); !ok {
			g.Errs = append(g.Errs, base+": _lifecycle_of "+ir.Repr(entity)+" is not a Modelith entity")
			continue
		}
		claimed[entity] = true
		enumName := enumByEntity[entity]
		if enumName == "" {
			g.Errs = append(g.Errs, base+": entity "+ir.Repr(entity)+" has no enum-typed lifecycle attribute")
			continue
		}
		vals := setOf(enums[enumName])
		var top []string
		for _, s := range ir.WalkStates(mo.Get2("states"), "") {
			if !strings.Contains(s.Path, ".") {
				top = append(top, s.Name)
			}
		}
		domainStates := map[string]bool{}
		var overlay []string
		for _, n := range top {
			if ir.IsUpperFirst(n) {
				domainStates[n] = true
			} else {
				overlay = append(overlay, n)
			}
		}
		var diff []string
		for s := range domainStates {
			if !vals[s] {
				diff = append(diff, s)
			}
		}
		sort.Strings(diff)
		for _, s := range diff {
			g.Errs = append(g.Errs, base+": domain state "+ir.Repr(s)+" is not a value of enum "+enumName+" (overlay states are lowerCamel by convention)")
		}
		var diff2 []string
		for v := range vals {
			if !domainStates[v] {
				diff2 = append(diff2, v)
			}
		}
		sort.Strings(diff2)
		for _, v := range diff2 {
			g.Errs = append(g.Errs, base+": enum "+enumName+" value "+ir.Repr(v)+" has no machine state; the lifecycle is incomplete")
		}
		if len(overlay) > 0 {
			g.Notes = append(g.Notes, name+": "+fmt.Sprintf("%d", len(overlay))+" operational-overlay states ("+strings.Join(overlay, ", ")+")")
		}
		events := map[string]bool{}
		for _, s := range ir.WalkStates(mo.Get2("states"), "") {
			if on := s.Node.AsObject().Get2("on"); on != nil {
				for _, ev := range on.AsObject().Keys() {
					events[ev] = true
				}
			}
		}
		var evSorted []string
		for ev := range events {
			evSorted = append(evSorted, ev)
		}
		sort.Strings(evSorted)
		for _, ev := range evSorted {
			if !actionsByEntity[entity][ev] {
				g.Errs = append(g.Errs, base+": event "+ir.Repr(ev)+" is not a Modelith action of "+entity)
			}
		}
		g.Count("lifecycle machines traced")
	}

	var enumEntities []string
	for ename := range enumByEntity {
		enumEntities = append(enumEntities, ename)
	}
	sort.Strings(enumEntities)
	for _, ename := range enumEntities {
		enumName := enumByEntity[ename]
		if !claimed[ename] {
			g.Errs = append(g.Errs, "entity "+ename+" has lifecycle enum "+enumName+" but no machine ("+ename+".machine.json); model the lifecycle or drop the enum")
		} else {
			g.Count("lifecycle entities with machines")
		}
	}

	// placement table
	persistedPlacements := checkPlacement(g, design, machineNames, entities)

	// residual-handler binding: opt-in on the mitigation table's "handled by"
	// column (see residual.go)
	checkResidualHandling(g, design, machineNames)

	// event-contract rows against the machines: the pack side of this check
	// runs only where a pack exists, so a design that carries one is left to
	// G5 rather than reported twice for one defect (see eventwiring.go)
	archText := readOrEmpty(filepath.Join(design, "ARCHITECTURE.md"))
	if !pack.HasPack(design) {
		checkEventWiring(g, design, archText)
	}
	// the consumer-READS completeness tier, armed by the design's own marker.
	// It runs on a packed design too: G5 reconciles boundary-event DIRECTION
	// from the generated events.md and has no notion of READS, so nothing
	// double-reports (see readscomplete.go)
	checkReadsComplete(g, design, archText)

	// invariants enforcement
	var cells, unitCells []string
	matrixFiles := globExt(mdir, ".matrix.md")
	for _, f := range matrixFiles {
		for _, tbl := range ir.ParseMdTables(readFileOrErr(f, g)) {
			mi := ir.FindCol(tbl.Header, "maps to")
			for _, r := range tbl.Rows {
				cells = append(cells, r...)
				if mi >= 0 && mi < len(r) {
					unitCells = append(unitCells, r[mi])
				}
			}
		}
	}
	build := filepath.Join(design, "BUILD.md")
	if _, err := os.Stat(build); err == nil {
		// every BUILD scan below runs fence-masked, matching Gb: a fenced
		// example "Mode:" line, heading, or table row is documentation, not a
		// declaration, and must neither satisfy the template checks nor credit
		// invariant enforcement in the traceability corpus
		buildText := maskFences(readFileOrErr(build, g))
		for _, tbl := range ir.ParseMdTables(buildText) {
			for _, r := range tbl.Rows {
				cells = append(cells, r...)
			}
		}
		// manifest mode shards contribute to the traceability corpus too
		for _, shard := range sortedGlobExt(filepath.Join(design, "BUILD"), ".md") {
			for _, tbl := range ir.ParseMdTables(maskFences(readFileOrErr(shard, g))) {
				for _, r := range tbl.Rows {
					cells = append(cells, r...)
				}
			}
			g.Count("build shards scanned")
		}
		// template conformance: deterministic structural requirements
		if modeRe.FindString(buildText) == "" {
			g.Errs = append(g.Errs, "BUILD.md declares no mode; the template requires a top 'Mode: full ...' or 'Mode: manifest ...' line")
		} else {
			g.Count("build mode declared")
		}
		if !headingContains(buildText, "toolchain") {
			g.Errs = append(g.Errs, "BUILD.md has no Toolchain heading; two implementing agents must not diverge on environment (pin language, libraries, test framework)")
		} else {
			g.Count("toolchain section present")
		}
		if persistedPlacements > 0 {
			if !headingContains(buildText, "state migration") {
				g.Errs = append(g.Errs, fmt.Sprintf("%d placement row(s) persist machine state but BUILD.md has no State migration heading (mapping table or drain rule for future state changes, or 'no persisted instances yet')", persistedPlacements))
			} else {
				g.Count("state-migration section present")
			}
		}
	} else {
		g.Warns = append(g.Warns, "BUILD.md not present; invariant enforcement is checked against the matrices only (fine before Phase 4)")
	}
	corpus := strings.Join(cells, "\n")
	unitCorpus := strings.Join(unitCells, "\n")
	if len(invIDs) == 0 {
		g.Errs = append(g.Errs, "the domain model declares no invariants; nothing constrains the design")
	}
	// the relational policy model is an enforcement artifact too: an
	// invariant compiled into Policy.als is solver-checked, which is
	// stronger than a prose reference (Gp-policy holds the annotation to
	// the domain model; here it only credits coverage)
	policyIDs := alloy.CarriedIDs(filepath.Join(design, "formal", alloy.AnnotationName))
	integrityIDs := alloy.CarriedIntegrityIDs(filepath.Join(design, "formal", alloy.IntegrityAnnotationName))
	isolationIDs := alloy.CarriedIsolationIDs(filepath.Join(design, "formal", alloy.IsolationAnnotationName))
	// an explicit waiver-with-reason (a layer residual, a checker coverage
	// residual, or the formal/waivers.yaml annex) is a recorded
	// disposition, not a gap; Gc-carrier and Gk own validating the waivers
	// themselves. A checker's coverage claim is an enforcement artifact
	// (Gk reconciles the evidence behind it).
	waivedIDs := map[string]bool{}
	for _, ann := range []string{alloy.AnnotationName, alloy.IntegrityAnnotationName, alloy.IsolationAnnotationName} {
		for iid := range alloy.ResidualIDs(filepath.Join(design, "formal", ann)) {
			waivedIDs[iid] = true
		}
	}
	for iid := range annexWaiverIDs(design) {
		waivedIDs[iid] = true
	}
	checkerIDs, checkerWaived := checkerClaims(design, invIDs)
	for iid := range checkerWaived {
		waivedIDs[iid] = true
	}
	var invSorted []string
	for iid := range invIDs {
		invSorted = append(invSorted, iid)
	}
	sort.Strings(invSorted)
	for _, iid := range invSorted {
		switch {
		case tokenIn(iid, unitCorpus):
			g.Count("invariants enforced")
			g.Count("invariants unit-backed (guard/action/actor)")
		case policyIDs[iid]:
			g.Count("invariants enforced")
			g.Count("invariants policy-checked (relational model)")
		case integrityIDs[iid]:
			g.Count("invariants enforced")
			g.Count("invariants integrity-checked (relational model)")
		case isolationIDs[iid]:
			g.Count("invariants enforced")
			g.Count("invariants isolation-checked (relational model)")
		case checkerIDs[iid]:
			g.Count("invariants enforced")
			g.Count("invariants checker-claimed (external checker)")
		case waivedIDs[iid]:
			g.Count("invariants waived with reason")
		case tokenIn(iid, corpus):
			// a prose table row is a claim, not a carrier: it satisfies a
			// reader, never a machine. Counted and warned as a residual so
			// hand-maintained rows cannot silently stand in for enforcement.
			// The two texts differ because the fixes differ: a
			// preserves-carried invariant must NOT be waived (Gc-carrier
			// would flag the waiver as stale); one carried by nothing must
			// be, or mapped.
			g.Count("invariants attested only (prose)")
			if preservedIDs[iid] {
				g.Warns = append(g.Warns, "invariant "+ir.Repr(iid)+" is carried by preserves but realized by no machine unit or relational layer; its enforcement rests on the prose tables and the tests they name (map it in a machine matrix or a relational layer)")
			} else {
				g.Warns = append(g.Warns, "invariant "+ir.Repr(iid)+" is attested only by prose table rows; map it to a machine unit or a relational layer, or waive it in formal/"+WaiverAnnexName)
			}
		default:
			g.Errs = append(g.Errs, "invariant "+ir.Repr(iid)+" is referenced by no matrix or BUILD.md table; it is enforced by nothing")
		}
	}

	// orphan references
	known := map[string]bool{}
	for iid := range invIDs {
		known[iid] = true
	}
	for a := range allActions {
		known[a] = true
	}
	for _, ename := range entities.Keys() {
		known[ename] = true
	}
	for _, vs := range enums {
		for _, v := range vs {
			known[v] = true
		}
	}
	for _, f := range matrixFiles {
		base := filepath.Base(f)
		for _, tbl := range ir.ParseMdTables(readOrEmpty(f)) { // read errors reported on the first pass above
			mi := ir.FindCol(tbl.Header, "maps to")
			if mi < 0 {
				continue
			}
			for _, r := range tbl.Rows {
				if mi >= len(r) {
					continue
				}
				for _, m := range kebabRe.FindAllStringSubmatch(r[mi], -1) {
					if !known[m[1]] {
						g.Drift = append(g.Drift, base+": maps-to references `"+m[1]+"`, which is not a declared invariant (typo or a stale reference)")
					}
				}
			}
		}
	}
	g.RequireNonzero("invariants enforced", "no invariant was traced to an enforcement artifact")
	return g
}

// checkPlacement holds the persistence-and-placement table in ARCHITECTURE.md
// and returns how many rows persist their state (the BUILD.md state-migration
// trigger). Two obligations, opposite directions:
//
//   - every ROW names a component in backticks that has a machine, or carries
//     a '(no machine: <reason>)' waiver;
//   - every ENTITY the domain model declares appears in some row's component
//     cell, or carries a '(not placed: <reason>)' waiver.
//
// The second is the completeness half. Unlike the dependency declaration,
// whose universe is open (a dependency nobody declared carries no obligation,
// so completeness there is attested), the entity list is CLOSED and
// enumerable from the model: an entity that simply never got a row is a hole
// no other gate can see, so it is checked here rather than trusted.
func checkPlacement(g *Gate, design string, machineNames map[string]bool, entities *ir.Object) int {
	persisted := 0
	arch := filepath.Join(design, "ARCHITECTURE.md")
	if _, err := os.Stat(arch); err != nil {
		return persisted
	}
	text := readFileOrErr(arch, g)
	placedEntities := map[string]bool{}
	waivedEntities := map[string]bool{}
	tableFound := false
	// EVERY header-matching table counts, as with the event, interface, and
	// mitigation tables: a design may split placement across sections (the
	// aggregates in one, the operational machines in another), and the
	// first-match locator silently excluded every later table's rows from both
	// obligations while the completeness half still demanded a row per entity.
	// Rows aggregate: the persisted count and the per-row findings accumulate,
	// and placement and waiver coverage are sets, so an entity placed in
	// either table is placed once.
	for _, tbl := range ir.ParseMdTables(text) {
		hl := strings.ToLower(strings.Join(tbl.Header, " "))
		if !strings.Contains(hl, "placement") || !strings.Contains(hl, "persistence") {
			continue
		}
		tableFound = true
		pi := ir.FindCol(tbl.Header, "persistence")
		mp := ir.FindCol(tbl.Header, "machine placement", "placement", "machine")
		for _, r := range tbl.Rows {
			if len(r) == 0 {
				continue
			}
			if pi >= 0 && pi < len(r) && isPersisted(r[pi]) {
				persisted++
			}
			// only a backticked token outside the annotation parentheses names
			// a component; a bare word is prose, and accepting it lets
			// de-backticked rows pass silently
			named := placementSubjects(r[0])
			if len(named) == 0 {
				g.Errs = append(g.Errs, "placement row names no component in backticks: "+ir.Repr(r[0]))
				continue
			}
			if m := notPlacedWaiverRe.FindStringSubmatch(r[0]); m != nil {
				// the row states the entity has no placement of its own (it
				// rides another aggregate's row, or is value-like): there is no
				// placement decision to record and so no machine to demand. An
				// empty reason is an unanswered design question, not a waiver;
				// the subjects still count as seen, so one defect never
				// cascades into a second finding against the same entity.
				for _, comp := range named {
					waivedEntities[comp] = true
				}
				if strings.TrimSpace(m[1]) == "" {
					g.Errs = append(g.Errs, "placement waiver for `"+named[0]+"` names no reason; write '(not placed: <reason>)'")
				}
				continue
			}
			for _, comp := range named {
				placedEntities[comp] = true
			}
			// the machine obligation binds the row's first component: the rest
			// are co-located subjects of the same placement decision
			comp := named[0]
			if machineNames[comp] {
				g.Count("placement rows with machines")
			} else if placementWaived(r, mp) {
				g.Count("placement rows waived")
			} else {
				g.Errs = append(g.Errs, "placement row component `"+comp+"` has no machine and no '(no machine: <reason>)' waiver in its component or machine-placement cell")
			}
		}
	}
	if !tableFound {
		g.Errs = append(g.Errs, fmt.Sprintf("ARCHITECTURE.md has no persistence-and-placement table (a header naming both placement and persistence); the model's %d entities can be traced to no placement decision", entities.Len()))
		return persisted
	}
	names := append([]string(nil), entities.Keys()...)
	sort.Strings(names)
	for _, ename := range names {
		switch {
		case placedEntities[ename]:
			g.Count("entities placed")
		case waivedEntities[ename]:
			g.Count("entities placement-waived")
		default:
			g.Errs = append(g.Errs, "entity `"+ename+"` appears in no persistence-and-placement row and carries no '(not placed: <reason>)' waiver; the placement table is incomplete")
		}
	}
	return persisted
}

// noMachineWaiverRe is the placement waiver token with its reason captured.
var noMachineWaiverRe = regexp.MustCompile(`\(no machine:\s*([^)]*)\)`)

// notPlacedWaiverRe is the placement-completeness waiver token with its reason
// captured: a declared entity that deliberately has no placement row of its
// own. Distinct from '(no machine: <reason>)', which waives the MACHINE of a
// component that is placed.
var notPlacedWaiverRe = regexp.MustCompile(`\(not placed:\s*([^)]*)\)`)

// parenAnnotationRe matches a parenthesized annotation in a placement
// component cell.
var parenAnnotationRe = regexp.MustCompile(`\([^)]*\)`)

// placementSubjects returns the components a placement row's first cell names:
// the backticked tokens OUTSIDE any parenthetical annotation. A name mentioned
// inside a waiver reason is prose about another row's component, never a
// placement of its own ("`Holding` (no machine: rows written with their
// `Portfolio`)" places Holding, not Portfolio).
func placementSubjects(cell string) []string {
	return backtickTokens(parenAnnotationRe.ReplaceAllString(cell, " "))
}

// placementWaived recognizes the '(no machine: <reason>)' waiver only in the
// cells that name what is waived: the component cell (the portfolio-engine
// shape) or the machine-placement cell (the checkout-split shape). The token
// buried anywhere else in the row is prose, and an empty reason is an
// unanswered design question, not a waiver (GATE-5).
func placementWaived(row []string, placementCol int) bool {
	cells := []string{row[0]}
	if placementCol > 0 && placementCol < len(row) {
		cells = append(cells, row[placementCol])
	}
	for _, cell := range cells {
		if m := noMachineWaiverRe.FindStringSubmatch(cell); len(m) > 1 && strings.TrimSpace(m[1]) != "" {
			return true
		}
	}
	return false
}

func backtickTokens(s string) []string {
	re := regexp.MustCompile("`([A-Za-z_][A-Za-z0-9_]*)`")
	var out []string
	for _, m := range re.FindAllStringSubmatch(s, -1) {
		out = append(out, m[1])
	}
	return out
}

func globExt(dir, ext string) []string {
	entries, _ := os.ReadDir(dir)
	var out []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ext) {
			out = append(out, filepath.Join(dir, e.Name()))
		}
	}
	sort.Strings(out)
	return out
}
