---- MODULE OrderPackRefinement ----
\* machinery-version: v0.3.5-dev
\* GENERATED by machinery pack refine. RECONCILED against the child machine
\* and the pack's contract machine; a drifted packmap fails generation.
\* Obligation: Order (child) refines OrdersContract (the contract the parent composition
\* instances). TLC checks Spec => C!Spec under the state mapping below.
EXTENDS Order

Map(s) ==
  CASE s = "Placed" -> "Open"
    [] s = "Paid" -> "Paid"
    [] s = "Shipped" -> "Done"
    [] s = "Declined" -> "Done"
    [] s = "Cancelled" -> "Done"

C == INSTANCE OrdersContract WITH st <- Map(st)
CSpecHolds == C!Spec
====
