#!/usr/bin/env python3
"""compose_gen: generate a composition spec that proves cross-aggregate invariants.

The recursion-scaling step. Some invariants (no-ship-before-pay, capture-matches-
total) span several aggregates, so no single aggregate's model can prove them. This
composes each aggregate as its abstract contract, drives them in the coordinator's
order, and checks the cross-invariants against the COMPOSED contracts, never against
the flattened implementations. Each aggregate is still verified separately against
its own contract, so the parts and the whole are both checked, at bounded cost.

Usage: compose_gen.py <composition.yaml> [out-dir]
"""
import sys, os
import yaml


def _t(s):
    return s[:1].upper() + s[1:]


def generate(comp):
    name = _t(comp["composition"])
    aggs = comp["aggregates"]        # {agg: {states, initial}}
    seq = comp["sequence"]           # [{aggregate, to}] the coordinator's forward order
    invs = comp.get("invariants", {})
    aggnames = list(aggs.keys())
    nsteps = len(seq)

    L = []
    L.append("---- MODULE %s ----" % name)
    L.append("\\* GENERATED by tools/compose_gen.py from %s.composition.yaml." % comp["composition"])
    L.append("\\* Proves cross-aggregate invariants by composing the subsystem contracts under the")
    L.append("\\* coordinator ordering. No single aggregate can prove these; the composition can.")
    L.append("")
    for a in aggnames:
        vals = ", ".join('"%s"' % s for s in aggs[a]["states"])
        L.append("%sStates == {%s}" % (_t(a), vals))
    L.append("Steps == {%s}" % ", ".join('"s%d"' % i for i in range(nsteps + 1)))
    varlist = ", ".join(["step"] + aggnames)
    L.append("VARIABLES %s" % varlist)
    L.append("vars == << %s >>" % varlist)
    L.append("")
    L.append("TypeOK == step \\in Steps" + "".join(" /\\ %s \\in %sStates" % (a, _t(a)) for a in aggnames))
    L.append('Init == step = "s0"' + "".join(' /\\ %s = "%s"' % (a, aggs[a]["initial"]) for a in aggnames))
    L.append("")
    acts = []
    for i, s in enumerate(seq):
        a, to = s["aggregate"], s["to"]
        others = [x for x in aggnames if x != a]
        unch = ("UNCHANGED << %s >>" % ", ".join(others)) if others else "TRUE"
        L.append('Step%d == step = "s%d" /\\ step\' = "s%d" /\\ %s\' = "%s" /\\ %s'
                 % (i, i, i + 1, a, to, unch))
        acts.append("Step%d" % i)
    L.append('Done == step = "s%d" /\\ UNCHANGED vars' % nsteps)
    acts.append("Done")
    L.append("Next == %s" % " \\/ ".join(acts))
    L.append("Spec == Init /\\ [][Next]_vars")
    L.append("")

    def cn(iname):
        return "Inv_" + "".join(w.capitalize() for w in iname.split("-"))

    for iname, expr in invs.items():
        L.append("%s == %s" % (cn(iname), expr))
    L.append("====")
    tla = "\n".join(L) + "\n"
    cfg = "SPECIFICATION Spec\nINVARIANT TypeOK\n" + "".join("INVARIANT %s\n" % cn(i) for i in invs)
    return name, tla, cfg


def main():
    comp = yaml.safe_load(open(sys.argv[1]))
    outdir = sys.argv[2] if len(sys.argv) > 2 else os.path.dirname(sys.argv[1])
    name, tla, cfg = generate(comp)
    open(os.path.join(outdir, name + ".tla"), "w").write(tla)
    open(os.path.join(outdir, name + ".cfg"), "w").write(cfg)
    print("generated %s.tla + %s.cfg" % (name, name))


if __name__ == "__main__":
    main()
