#!/usr/bin/env python3
"""refine_gen: generate the data-refined model, the abstract contract, and the
refinement mapping for a machine, from a declarative semantics annotation.

This industrializes Parts 1 and 3 of the correctness ladder. The machine JSON gives
the control graph; the `<M>.semantics.yaml` sidecar gives the meaning the graph omits
(guards, action effects, ordering). Together they generate a TLA+ data model that
proves the real domain invariants, plus an abstract contract and a TLC-checked
refinement, so a new subsystem needs a short annotation instead of hand-written TLA+.

Emits, for the `linear-lifecycle` pattern (ordered open stages, win/lose terminals,
reopen, and the standard persist-retry overlay):
  <M>Data.tla / .cfg          domain invariants: stage-forward, atomicity, close-date
  <M>Contract.tla             the abstract resting/busy/atomic/terminates contract
  <M>Refinement.tla / .cfg    proof that <M>Data refines <M>Contract

Usage: refine_gen.py <machine.json> <semantics.yaml> [out-dir]
"""
import sys, os, json
import yaml


def _title(s):
    return s[:1].upper() + s[1:]


def emit_lifecycle(machine, sem):
    mid = _title(sem["machine"])
    stages = sem["stages"]                      # open stages, ordered
    win, lose = sem["win_stage"], sem["lose_stage"]
    reopen_to = sem["reopen_to"]
    close_on = sem["close_date_on"]
    maxr = sem["max_retries"]
    initial = machine.get("initial", stages[0])

    terminal = [win, lose]
    domain = stages + terminal
    advanceable = stages[:-1]
    rank = {s: i for i, s in enumerate(stages)}
    rank[win] = rank[lose] = len(stages)
    nxt = {stages[i]: stages[i + 1] for i in range(len(stages) - 1)}

    def q(xs):
        return "{" + ", ".join(f'"{x}"' for x in xs) + "}"

    rankf = "[" + ", ".join(f"{s} |-> {rank[s]}" for s in domain) + "]"
    nextf = "[" + ", ".join(f'{k} |-> "{v}"' for k, v in nxt.items()) + "]"

    data = f"""---- MODULE {mid}Data ----
\\* GENERATED by tools/refine_gen.py from {sem['machine']}.machine.json + {sem['machine']}.semantics.yaml.
\\* Data-refined model: proves the real domain invariants, not just control flow.
EXTENDS Naturals

CONSTANT MaxRetries

Open == {q(stages)}
Terminal == {q(terminal)}
Domain == Open \\cup Terminal
Overlay == {{"persisting", "persistRetry", "rolledBack"}}
None == "none"
Rank == {rankf}
NextStage == {nextf}

VARIABLES st, rc, stage, pending, prior, closeSet
vars == << st, rc, stage, pending, prior, closeSet >>

TypeOK ==
  /\\ st \\in (Domain \\cup Overlay)
  /\\ rc \\in 0..MaxRetries
  /\\ stage \\in Domain
  /\\ pending \\in (Domain \\cup {{None}})
  /\\ prior \\in (Domain \\cup {{None}})
  /\\ closeSet \\in BOOLEAN

Init ==
  /\\ st = "{initial}" /\\ stage = "{initial}"
  /\\ rc = 0 /\\ pending = None /\\ prior = None /\\ closeSet = FALSE

StartAdvance ==
  /\\ st \\in {q(advanceable)}
  /\\ st' = "persisting" /\\ pending' = NextStage[st] /\\ prior' = st
  /\\ rc' = 0 /\\ stage' = stage /\\ closeSet' = closeSet

StartWin ==
  /\\ st \\in Open
  /\\ st' = "persisting" /\\ pending' = "{win}" /\\ prior' = st
  /\\ rc' = 0 /\\ stage' = stage /\\ closeSet' = closeSet

StartLose ==
  /\\ st \\in Open
  /\\ st' = "persisting" /\\ pending' = "{lose}" /\\ prior' = st
  /\\ rc' = 0 /\\ stage' = stage /\\ closeSet' = closeSet

StartReopen ==
  /\\ st \\in Terminal
  /\\ st' = "persisting" /\\ pending' = "{reopen_to}" /\\ prior' = st
  /\\ rc' = 0 /\\ stage' = stage /\\ closeSet' = closeSet

SaveDone ==
  /\\ st = "persisting"
  /\\ st' = pending /\\ stage' = pending
  /\\ closeSet' = (closeSet \\/ (pending = "{close_on}"))
  /\\ pending' = None /\\ prior' = None /\\ rc' = 0

SaveLocked ==
  /\\ st = "persisting" /\\ st' = "persistRetry"
  /\\ UNCHANGED << rc, stage, pending, prior, closeSet >>

SaveFail ==
  /\\ st = "persisting" /\\ st' = "rolledBack"
  /\\ UNCHANGED << rc, stage, pending, prior, closeSet >>

RetryExhausted ==
  /\\ st = "persistRetry" /\\ rc >= MaxRetries /\\ st' = "rolledBack"
  /\\ UNCHANGED << rc, stage, pending, prior, closeSet >>

RetryAgain ==
  /\\ st = "persistRetry" /\\ rc < MaxRetries /\\ st' = "persisting" /\\ rc' = rc + 1
  /\\ UNCHANGED << stage, pending, prior, closeSet >>

RolledBack ==
  /\\ st = "rolledBack"
  /\\ st' = prior /\\ stage' = prior
  /\\ pending' = None /\\ prior' = None /\\ rc' = 0 /\\ closeSet' = closeSet

Domain_Next == StartAdvance \\/ StartWin \\/ StartLose \\/ StartReopen
Overlay_Next == SaveDone \\/ SaveLocked \\/ SaveFail \\/ RetryExhausted \\/ RetryAgain \\/ RolledBack
Next == Domain_Next \\/ Overlay_Next

Spec == Init /\\ [][Next]_vars /\\ WF_vars(Overlay_Next)

Inv_StageValid == stage \\in Domain
Inv_Atomic == (st \\in Overlay) => (stage = prior)
Inv_DomainConsistent == (st \\in Domain) => (st = stage /\\ pending = None /\\ prior = None)
Inv_CloseDate == (stage = "{close_on}") => closeSet

StageForward ==
  [][ (stage' # stage) =>
        \\/ Rank[stage'] > Rank[stage]
        \\/ (stage \\in Terminal /\\ stage' = "{reopen_to}") ]_stage

Live_OverlayResolves == (st \\in Overlay) ~> (st \\in Domain)
====
"""

    data_cfg = ("CONSTANT MaxRetries = %d\nSPECIFICATION Spec\n"
                "INVARIANT TypeOK\nINVARIANT Inv_StageValid\nINVARIANT Inv_Atomic\n"
                "INVARIANT Inv_DomainConsistent\nINVARIANT Inv_CloseDate\n"
                "PROPERTY StageForward\nPROPERTY Live_OverlayResolves\n") % maxr

    contract = f"""---- MODULE {mid}Contract ----
\\* GENERATED. The abstract contract the big picture assumes of the {sem['machine']}
\\* aggregate: resting or busy, atomic while busy, and every busy period terminates.
VARIABLES phase, kind
cvars == << phase, kind >>

Phases == {{"resting", "busy"}}
Kinds == {{"open", "terminal"}}

CTypeOK == phase \\in Phases /\\ kind \\in Kinds
CInit == phase = "resting" /\\ kind = "open"

Begin == phase = "resting" /\\ phase' = "busy" /\\ kind' = kind
Finish == phase = "busy" /\\ phase' = "resting" /\\ kind' \\in Kinds
Churn == phase = "busy" /\\ phase' = "busy" /\\ kind' = kind
RestStutter == phase = "resting" /\\ UNCHANGED cvars

CNext == Begin \\/ Finish \\/ Churn \\/ RestStutter
CSpec == CInit /\\ [][CNext]_cvars /\\ WF_cvars(Finish)
CTermination == (phase = "busy") ~> (phase = "resting")
====
"""

    refinement = f"""---- MODULE {mid}Refinement ----
\\* GENERATED. Proof that {mid}Data refines {mid}Contract under a refinement mapping.
EXTENDS {mid}Data

phaseBar == IF st \\in Domain THEN "resting" ELSE "busy"
kindBar == IF stage \\in Terminal THEN "terminal" ELSE "open"

DC == INSTANCE {mid}Contract WITH phase <- phaseBar, kind <- kindBar

RefTypeOK == DC!CTypeOK
RefSpec == DC!CSpec
RefTermination == DC!CTermination
====
"""

    ref_cfg = ("CONSTANT MaxRetries = %d\nSPECIFICATION Spec\n"
               "INVARIANT RefTypeOK\nPROPERTY RefSpec\nPROPERTY RefTermination\n") % maxr

    return mid, {f"{mid}Data.tla": data, f"{mid}Data.cfg": data_cfg,
                 f"{mid}Contract.tla": contract,
                 f"{mid}Refinement.tla": refinement, f"{mid}Refinement.cfg": ref_cfg}


def emit_saga(machine, sem):
    """Saga pattern: forward steps each commit a side effect and carry a
    compensating obligation; one idempotent compensate step is retried, and the
    saga ends FailedDirty if it cannot complete. Proves money and stock are never
    silently lost."""
    mid = _title(sem["machine"])
    states = sem["states"]
    obl = sem["obligations"]
    maxr = sem["max_retries"]
    initial = machine.get("initial", states[0])

    flags = []
    for s in states:
        for k in ("sets", "undo"):
            v = obl.get(s, {}).get(k)
            if v and v not in flags:
                flags.append(v)
    obligations = [(obl[s]["sets"], obl[s]["undo"]) for s in states
                   if obl.get(s, {}).get("sets") and obl.get(s, {}).get("undo")]
    varlist = ", ".join(["st", "rc"] + flags)

    def unch(exclude):
        keep = [v for v in (["rc"] + flags) if v not in exclude]
        return "<< " + ", ".join(keep) + " >>"

    L = []
    L.append(f"---- MODULE {mid}Data ----")
    L.append(f"\\* GENERATED by tools/refine_gen.py (saga pattern) from {sem['machine']}.semantics.yaml.")
    L.append("\\* Proves money and stock are never silently lost: a compensated saga refunds what it")
    L.append("\\* captured and releases what it reserved, or ends FailedDirty as an explicit residual.")
    L.append("EXTENDS Naturals")
    L.append("")
    L.append("CONSTANT MaxRetries")
    L.append("Steps == {" + ", ".join(f'"{s}"' for s in states) + ', "Compensating", "compensateRetry"}')
    L.append('Final == {"Completed", "Failed", "FailedDirty"}')
    L.append(f"VARIABLES {varlist}")
    L.append(f"vars == << {varlist} >>")
    L.append("")
    L.append("TypeOK == st \\in (Steps \\cup Final) /\\ rc \\in 0..MaxRetries"
             + "".join(f" /\\ {f} \\in BOOLEAN" for f in flags))
    L.append(f'Init == st = "{initial}" /\\ rc = 0' + "".join(f" /\\ {f} = FALSE" for f in flags))
    L.append("")
    overlay = []
    for i, s in enumerate(states):
        nxt = states[i + 1] if i + 1 < len(states) else "Completed"
        sets = obl.get(s, {}).get("sets")
        eff = f" /\\ {sets}' = TRUE" if sets else ""
        L.append(f'Done_{s} == st = "{s}" /\\ st\' = "{nxt}"{eff} /\\ UNCHANGED {unch([sets] if sets else [])}')
        ft = "Failed" if i == 0 else "Compensating"
        L.append(f'Fail_{s} == st = "{s}" /\\ st\' = "{ft}" /\\ UNCHANGED {unch([])}')
        overlay += [f"Done_{s}", f"Fail_{s}"]
    comp_eff = " /\\ ".join(f"{u}' = {sv}" for sv, u in obligations)
    L.append(f'CompensateDone == st = "Compensating" /\\ st\' = "Failed" /\\ {comp_eff} /\\ UNCHANGED {unch([u for _, u in obligations])}')
    L.append(f'CompensateErr == st = "Compensating" /\\ st\' = "compensateRetry" /\\ UNCHANGED {unch([])}')
    L.append(f'RetryExhausted == st = "compensateRetry" /\\ rc >= MaxRetries /\\ st\' = "FailedDirty" /\\ UNCHANGED {unch([])}')
    L.append(f'RetryAgain == st = "compensateRetry" /\\ rc < MaxRetries /\\ st\' = "Compensating" /\\ rc\' = rc + 1 /\\ UNCHANGED {unch(["rc"])}')
    overlay += ["CompensateDone", "CompensateErr", "RetryExhausted", "RetryAgain"]
    L.append("")
    L.append("OverlayNext == " + " \\/ ".join(overlay))
    L.append("Terminated == st \\in Final /\\ UNCHANGED vars")
    L.append("Next == OverlayNext \\/ Terminated")
    L.append("Spec == Init /\\ [][Next]_vars /\\ WF_vars(OverlayNext)")
    L.append("")
    nsl = " /\\ ".join(f'(({sv} /\\ st # "Completed") => ({u} \\/ st = "FailedDirty"))' for sv, u in obligations)
    L.append(f"Inv_NoSilentLoss == (st \\in Final) => ({nsl})")
    cc = " /\\ ".join(f"({sv} => {u})" for sv, u in obligations)
    L.append(f'Inv_CleanCompensation == (st = "Failed") => ({cc})')
    L.append("Live_Terminates == (st \\notin Final) ~> (st \\in Final)")
    L.append("====")
    tla = "\n".join(L) + "\n"
    cfg = (f"CONSTANT MaxRetries = {maxr}\nSPECIFICATION Spec\nINVARIANT TypeOK\n"
           "INVARIANT Inv_NoSilentLoss\nINVARIANT Inv_CleanCompensation\n"
           "PROPERTY Live_Terminates\n")
    return mid, {f"{mid}Data.tla": tla, f"{mid}Data.cfg": cfg}


def main():
    machine = json.load(open(sys.argv[1]))
    sem = yaml.safe_load(open(sys.argv[2]))
    outdir = sys.argv[3] if len(sys.argv) > 3 else os.path.dirname(sys.argv[2])
    pat = sem.get("pattern")
    if pat == "linear-lifecycle":
        mid, files = emit_lifecycle(machine, sem)
    elif pat == "saga":
        mid, files = emit_saga(machine, sem)
    else:
        sys.exit(f"refine_gen: unsupported pattern {pat!r} (linear-lifecycle, saga)")
    for name, body in files.items():
        open(os.path.join(outdir, name), "w").write(body)
    print(f"generated {len(files)} files for {mid} ({pat})")


if __name__ == "__main__":
    main()
