#!/usr/bin/env bash
# Regenerate and TLC-model-check the whole formal suite for a design, from source:
#   - every machine's control-flow model (generated by tla_gen)      safety + liveness + deadlock
#   - the data refinement, contract, and refinement mapping          generated by refine_gen from *.semantics.yaml
#   - the assume-guarantee composition (System)                      subsystem contracts compose
# Usage: verify_formal.sh <design-dir>
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
design="${1:?usage: verify_formal.sh <design-dir>}"
mdir="$design/machines"
fdir="$design/formal"
mkdir -p "$fdir"

for mj in "$mdir"/*.machine.json; do
  python3 "$here/tla_gen.py" "$mj" "$fdir" >/dev/null
done
for sem in "$fdir"/*.semantics.yaml; do
  [ -e "$sem" ] || continue
  m="$(basename "$sem" .semantics.yaml)"
  python3 "$here/refine_gen.py" "$mdir/$m.machine.json" "$sem" "$fdir" >/dev/null
done

pass=0
fail=0
run() { # label  spec.tla
  if bash "$here/tlc.sh" "$fdir/$2" 2>&1 | grep -q "No error has been found"; then
    printf "  PASS  %s\n" "$1"; pass=$((pass + 1))
  else
    printf "  FAIL  %s\n" "$1"; fail=$((fail + 1))
  fi
}

echo "control-flow (safety: retry bounded; liveness: overlay resolves; deadlock-free):"
for m in Deal Task User Session CommandExecution; do run "$m" "$m.tla"; done
echo "data-refined domain invariants (generated from semantics):"
run "DealData: stage-forward, persist atomicity, close-date" "DealData.tla"
echo "refinement (subsystem refines its abstract contract):"
run "DealData refines DealContract" "DealRefinement.tla"
echo "assume-guarantee composition (the recursion rule):"
run "System: command completes and leaves the deal resting" "System.tla"

echo ""
echo "$pass passed, $fail failed"
[ "$fail" -eq 0 ]
