package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"testing"
)

// Canned outputs for the fake binaries. @DESIGN@ becomes the absolute path
// of the fake's private design copy, so path normalization is exercised.
const oldCanned = `== Gu-surfaces  target surface ledger ==
  checked: 3 obligated actions, 3 covered
  ok
== Gx-trace  cross-layer traceability ==
  warn   Order.matrix.md:12: row 'ship': undeclared fact reference ` + "`carrier`" + `
  note   Order: 2 operational-overlay states (persisting, persistRetry)
  checked: 4 entities, 2 lifecycle machines traced
== Gv-attest  attestation evidence ==
  DRIFT  machines/Order.oracle.json is stale; regenerate with 'machinery oracle @DESIGN@/machines'
  checked: 2 claims
note: artifacts generated by machinery v0.2.0, running v0.1.0; regenerate on upgrade:
  machinery oracle design/machines
the regeneration lands as its own dedicated stamp-only commit, never mixed with a design change

1 blocking (ERROR/DRIFT) finding(s)
`

const newCanned = `== Gu-surfaces  target surface ledger ==
  checked: 3 obligated actions, 4 covered
  ok
== Gx-trace  cross-layer traceability ==
  warn   Order.matrix.md:12: row 'ship': undeclared fact reference ` + "`carrier`" + `
  warn   Order.matrix.md:14: row 'pack': undeclared fact reference ` + "`parcel`" + `
  note   Order: 2 operational-overlay states (persisting, persistRetry)
  checked: 4 entities
== Gl-ledger  session ledgers + house style ==
  ERROR  @DESIGN@/BUILD.md:3: unknown declaration group MACHINE-WRITTEN{...}
  ERROR  BUILD.md:9: solver finished in 1.25s under machinery v0.2.0 at /tmp/machinery-alloy-123/run.als
  checked: 5 files
== Gv-attest  attestation evidence ==
  checked: 2 claims
  ok

2 blocking (ERROR/DRIFT) finding(s)
`

type fake struct {
	version string
	canned  string
	exit    int
	before  string // shell run before the output is printed
	stderr  string
}

// writeFake writes a small shell script that behaves like `machinery check`
// with canned output.
func writeFake(t *testing.T, dir, name string, f fake) string {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Skip("fake binaries are POSIX shell scripts")
	}
	canned := filepath.Join(dir, name+".out")
	if err := os.WriteFile(canned, []byte(f.canned), 0o600); err != nil {
		t.Fatal(err)
	}
	script := fmt.Sprintf(`#!/bin/sh
if [ "$1" = "--version" ]; then echo "machinery version %s"; exit 0; fi
%s
sed "s#@DESIGN@#$(pwd)/$2#g" '%s'
printf '%%s' '%s' >&2
exit %d
`, f.version, f.before, canned, f.stderr, f.exit)
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(script), 0o700); err != nil {
		t.Fatal(err)
	}
	return path
}

// fixture makes a synthetic design tree and the two standard fakes.
func fixture(t *testing.T) (design, oldBin, newBin string) {
	t.Helper()
	dir := t.TempDir()
	design = filepath.Join(dir, "design")
	writeFile(t, filepath.Join(design, "BUILD.md"), "# Build\n", 0o644)
	writeFile(t, filepath.Join(design, "machines", "Order.matrix.md"), "| row |\n", 0o644)
	oldBin = writeFake(t, dir, "old", fake{version: "v0.1.0", canned: oldCanned, exit: 1})
	newBin = writeFake(t, dir, "new", fake{version: "v0.2.0", canned: newCanned, exit: 1})
	return design, oldBin, newBin
}

func writeAllow(t *testing.T, body string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "allow.txt")
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func runTool(t *testing.T, args ...string) (int, string, string) {
	t.Helper()
	var out, errOut bytes.Buffer
	code := run(args, &out, &errOut)
	return code, out.String(), errOut.String()
}

func TestUnexplainedNewFindingsExitOne(t *testing.T) {
	design, oldBin, newBin := fixture(t)
	code, out, stderr := runTool(t, "-old", oldBin, "-new", newBin, "-design", design)
	if code != exitUnexplained {
		t.Fatalf("exit = %d, want 1\n%s%s", code, out, stderr)
	}
	for _, want := range []string{
		"consumer-diff: v0.1.0 -> v0.2.0 over " + design,
		"run      machinery check <design>",
		"1 blocking, 1 warnings, 2 notes; exit 1",
		"2 blocking, 2 warnings, 1 notes; exit 1",
		"stamps   old run: artifacts stamped by machinery v0.2.0, running v0.1.0",
		"stamps   new run: no version-stamp skew",
		"== new findings: 2 blocking, 1 warnings, 0 notes ==",
		"  Gx-trace       warn  Order.matrix.md:14: row 'pack': undeclared fact reference `parcel`",
		"  Gl-ledger      ERROR <root>/BUILD.md:3: unknown declaration group MACHINE-WRITTEN{...}",
		"  Gl-ledger      ERROR BUILD.md:9: solver finished in <duration> under machinery <version> at <tmp>",
		"== resolved findings: 1 blocking, 0 warnings, 1 notes ==",
		"  Gv-attest      DRIFT [stamp-skew] machines/Order.oracle.json is stale; regenerate with 'machinery oracle <root>/machines'",
		"  (run)          note  [stamp-skew] note: artifacts generated by machinery <version>, running <version>; regenerate on upgrade:",
		"  Gl-ledger      absent -> fail",
		"  Gv-attest      fail -> ok",
		"FAIL: 3 unexplained new finding(s): 2 blocking, 1 warnings",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("report lacks %q\n%s", want, out)
		}
	}
	if strings.Contains(out, "Order.matrix.md:12") {
		t.Errorf("a finding present in both runs must not be reported\n%s", out)
	}
	if strings.Contains(out, "Gu-surfaces") {
		t.Errorf("a changed checked: count is not a finding\n%s", out)
	}
}

func TestAllowFileThatExplainsEveryNewFindingExitsZero(t *testing.T) {
	design, oldBin, newBin := fixture(t)
	allow := writeAllow(t, `# synthetic expectations
gx warn /undeclared fact reference `+"`parcel`"+`/ the candidate reads the pack row
Gl-ledger error /MACHINE-WRITTEN/ the candidate checks the new declaration group
gl error /solver finished in <duration>/ solver timing line is now reported
`)
	code, out, stderr := runTool(t, "-old", oldBin, "-new", newBin, "-design", design, "-allow", allow)
	if code != exitOK {
		t.Fatalf("exit = %d, want 0\n%s%s", code, out, stderr)
	}
	for _, want := range []string{
		"[allowed " + allow + ":2] Order.matrix.md:14",
		"[allowed " + allow + ":3] <root>/BUILD.md:3",
		"== unused allow entries ==\n  (none)",
		"PASS: every new blocking finding and warning is explained (2 blocking, 1 warnings new)",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("report lacks %q\n%s", want, out)
		}
	}
}

func TestAllowFileThatDoesNotMatchExitsOneAndReportsUnused(t *testing.T) {
	design, oldBin, newBin := fixture(t)
	allow := writeAllow(t, "gx warn /nothing like this/ a stale expectation\n")
	code, out, _ := runTool(t, "-old", oldBin, "-new", newBin, "-design", design, "-allow", allow)
	if code != exitUnexplained {
		t.Fatalf("exit = %d, want 1\n%s", code, out)
	}
	if !strings.Contains(out, "== unused allow entries ==\n  "+allow+":1  gx warn /nothing like this/  a stale expectation") {
		t.Fatalf("unused entry not reported\n%s", out)
	}
}

func TestUnusedEntryIsReportedEvenWhenEverythingIsExplained(t *testing.T) {
	design, oldBin, newBin := fixture(t)
	allow := writeAllow(t, "* error /./ every new blocking finding is expected\n* warn /./ every new warning is expected\ngv drift /stale/ left over from an older candidate\n")
	code, out, _ := runTool(t, "-old", oldBin, "-new", newBin, "-design", design, "-allow", allow)
	if code != exitOK {
		t.Fatalf("exit = %d, want 0\n%s", code, out)
	}
	if !strings.Contains(out, allow+":3  gv drift /stale/  left over from an older candidate") {
		t.Fatalf("unused entry not reported\n%s", out)
	}
}

func TestNotesNeverGate(t *testing.T) {
	dir := t.TempDir()
	design := filepath.Join(dir, "design")
	writeFile(t, filepath.Join(design, "BUILD.md"), "x\n", 0o644)
	base := "== Gx-trace  cross-layer traceability ==\n  checked: 1 entities\n  ok\n\n0 blocking (ERROR/DRIFT) finding(s)\n"
	withNote := "== Gx-trace  cross-layer traceability ==\n  note   Order: 1 operational-overlay states (persisting)\n  checked: 1 entities\n  ok\n\n0 blocking (ERROR/DRIFT) finding(s)\n"
	oldBin := writeFake(t, dir, "old", fake{version: "v1", canned: base})
	newBin := writeFake(t, dir, "new", fake{version: "v2", canned: withNote})
	code, out, _ := runTool(t, "-old", oldBin, "-new", newBin, "-design", design)
	if code != exitOK || !strings.Contains(out, "== new findings: 0 blocking, 0 warnings, 1 notes ==") {
		t.Fatalf("exit = %d, want 0 with one new note\n%s", code, out)
	}
}

func TestJSONReport(t *testing.T) {
	design, oldBin, newBin := fixture(t)
	code, out, _ := runTool(t, "-old", oldBin, "-new", newBin, "-design", design, "-json")
	if code != exitUnexplained {
		t.Fatalf("exit = %d, want 1", code)
	}
	var rep report
	if err := json.Unmarshal([]byte(out), &rep); err != nil {
		t.Fatalf("not JSON: %v\n%s", err, out)
	}
	if rep.Exit != 1 || rep.NewTally != (tally{Blocking: 2, Warnings: 1}) || rep.Unexplained != (tally{Blocking: 2, Warnings: 1}) {
		t.Fatalf("tallies = %+v / %+v / exit %d", rep.NewTally, rep.Unexplained, rep.Exit)
	}
	if rep.Old.Skew == nil || rep.Old.Skew.Running != "v0.1.0" || rep.New.Skew != nil {
		t.Fatalf("skew = %+v / %+v", rep.Old.Skew, rep.New.Skew)
	}
	wantVerdicts := []verdictChange{{"Gl-ledger", "absent", "fail"}, {"Gv-attest", "fail", "ok"}}
	if !reflect.DeepEqual(rep.Verdicts, wantVerdicts) {
		t.Fatalf("verdicts = %+v", rep.Verdicts)
	}
	var gates []string
	for _, g := range rep.NewByGate {
		gates = append(gates, fmt.Sprintf("%s:%d/%d/%d", g.Gate, g.Blocking, g.Warnings, g.Unexplained))
	}
	if want := []string{"Gx-trace:0/1/1", "Gl-ledger:2/0/2"}; !reflect.DeepEqual(gates, want) {
		t.Fatalf("by gate = %v, want %v", gates, want)
	}
}

func TestSameFlagsReachBothBinaries(t *testing.T) {
	dir := t.TempDir()
	design := filepath.Join(dir, "design")
	impl := filepath.Join(dir, "impl")
	writeFile(t, filepath.Join(design, "BUILD.md"), "x\n", 0o644)
	writeFile(t, filepath.Join(impl, "main.go"), "package main\n", 0o644)
	canned := "== Gu-surfaces  target surface ledger ==\n  ok\n\n0 blocking (ERROR/DRIFT) finding(s)\n"
	logs := filepath.Join(dir, "args")
	record := func(name string) string {
		return writeFake(t, dir, name, fake{version: "v1", canned: canned, before: `echo "$@" > '` + logs + "." + name + `'`})
	}
	oldBin, newBin := record("old"), record("new")
	code, out, stderr := runTool(t, "-old", oldBin, "-new", newBin, "-design", design, "-impl", impl, "-commit", "abc123", "-gates", "gu,gx")
	if code != exitOK {
		t.Fatalf("exit = %d\n%s%s", code, out, stderr)
	}
	oldArgs, _ := os.ReadFile(logs + ".old")
	newArgs, _ := os.ReadFile(logs + ".new")
	pattern := "check design --impl "
	if !strings.HasPrefix(string(oldArgs), pattern) || !strings.HasSuffix(strings.TrimSpace(string(oldArgs)), "/impl --commit abc123 --gate gu,gx") {
		t.Fatalf("old args = %q", oldArgs)
	}
	strip := func(b []byte) string { // the impl copy path differs per run
		f := strings.Fields(string(b))
		f[3] = "<impl>"
		return strings.Join(f, " ")
	}
	if strip(oldArgs) != strip(newArgs) {
		t.Fatalf("flags differ: %q vs %q", oldArgs, newArgs)
	}
	if !strings.Contains(out, "run      machinery check <design> --impl <impl> --commit abc123 --gate gu,gx") {
		t.Fatalf("report does not state the flags\n%s", out)
	}
}

func TestCrashingBinaryExitsTwo(t *testing.T) {
	design, oldBin, _ := fixture(t)
	dir := t.TempDir()
	crash := writeFake(t, dir, "crash", fake{version: "v9", canned: "== Gu-surfaces  target surface ledger ==\n", exit: 2, stderr: "panic: runtime error: index out of range"})
	code, out, stderr := runTool(t, "-old", oldBin, "-new", crash, "-design", design)
	if code != exitError {
		t.Fatalf("exit = %d, want 2\n%s", code, out)
	}
	if !strings.Contains(stderr, "without the final blocking-count line") || !strings.Contains(stderr, "panic: runtime error") {
		t.Fatalf("stderr = %q", stderr)
	}
}

func TestExitCodeThatContradictsTheSummaryExitsTwo(t *testing.T) {
	design, oldBin, _ := fixture(t)
	liar := writeFake(t, t.TempDir(), "liar", fake{version: "v9", canned: "== Gu-surfaces  target surface ledger ==\n  ok\n\n0 blocking (ERROR/DRIFT) finding(s)\n", exit: 1})
	code, _, stderr := runTool(t, "-old", oldBin, "-new", liar, "-design", design)
	if code != exitError || !strings.Contains(stderr, "exited 1 but reported 0 blocking") {
		t.Fatalf("exit = %d, stderr = %q", code, stderr)
	}
}

func TestSummaryThatContradictsTheFindingsExitsTwo(t *testing.T) {
	design, oldBin, _ := fixture(t)
	odd := writeFake(t, t.TempDir(), "odd", fake{version: "v9", canned: "== Gu-surfaces  target surface ledger ==\n  ok\n\n2 blocking (ERROR/DRIFT) finding(s)\n", exit: 1})
	code, _, stderr := runTool(t, "-old", oldBin, "-new", odd, "-design", design)
	if code != exitError || !strings.Contains(stderr, "the parser found 0 ERROR/DRIFT lines") {
		t.Fatalf("exit = %d, stderr = %q", code, stderr)
	}
}

func TestUsageAndInputErrorsExitTwo(t *testing.T) {
	design, oldBin, newBin := fixture(t)
	notExec := filepath.Join(t.TempDir(), "plain")
	writeFile(t, notExec, "x", 0o644)
	cases := []struct {
		name string
		args []string
		want string
	}{
		{"missing flags", []string{"-old", oldBin}, "missing required -new, -design"},
		{"stray argument", []string{"-old", oldBin, "-new", newBin, "-design", design, "extra"}, "unexpected arguments: extra"},
		{"no design", []string{"-old", oldBin, "-new", newBin, "-design", filepath.Join(design, "nope")}, "does not exist"},
		{"design is a file", []string{"-old", oldBin, "-new", newBin, "-design", filepath.Join(design, "BUILD.md")}, "is not a directory"},
		{"no impl", []string{"-old", oldBin, "-new", newBin, "-design", design, "-impl", filepath.Join(design, "nope")}, "impl"},
		{"no binary", []string{"-old", filepath.Join(design, "nope"), "-new", newBin, "-design", design}, "-old: binary"},
		{"not executable", []string{"-old", oldBin, "-new", notExec, "-design", design}, "not an executable file"},
		{"bad allow file", []string{"-old", oldBin, "-new", newBin, "-design", design, "-allow", writeAllow(t, "gx warn /x/\n")}, "reason is mandatory"},
		{"bad flag", []string{"-bogus"}, "flag provided but not defined"},
	}
	for _, c := range cases {
		code, _, stderr := runTool(t, c.args...)
		if code != exitError || !strings.Contains(stderr, c.want) {
			t.Errorf("%s: exit = %d, stderr = %q; want 2 mentioning %q", c.name, code, stderr, c.want)
		}
	}
}

func TestTreeGuardFailsWhenTheOriginalChanges(t *testing.T) {
	design, oldBin, _ := fixture(t)
	// a candidate that escapes its copy and writes into the original design
	escape := writeFake(t, t.TempDir(), "escape", fake{version: "v9", canned: newCanned, exit: 1,
		before: `echo tampered >> '` + filepath.Join(design, "BUILD.md") + `'`})
	code, _, stderr := runTool(t, "-old", oldBin, "-new", escape, "-design", design)
	if code != exitError || !strings.Contains(stderr, "CHANGED during the comparison") || !strings.Contains(stderr, "BUILD.md") {
		t.Fatalf("exit = %d, stderr = %q", code, stderr)
	}
}

func TestWritesIntoTheCopyAreReportedAndNeverReachTheOriginal(t *testing.T) {
	design, oldBin, _ := fixture(t)
	writer := writeFake(t, t.TempDir(), "writer", fake{version: "v9", canned: newCanned, exit: 1,
		before: `echo cache > design/.check-cache`})
	code, out, stderr := runTool(t, "-old", oldBin, "-new", writer, "-design", design)
	if code != exitUnexplained {
		t.Fatalf("exit = %d\n%s%s", code, out, stderr)
	}
	if !strings.Contains(out, "note: the new binary wrote into its private copy of the tree (the original is unchanged): .check-cache") {
		t.Fatalf("copy write not reported\n%s", out)
	}
	if _, err := os.Stat(filepath.Join(design, ".check-cache")); !os.IsNotExist(err) {
		t.Fatalf("the original design gained the file: %v", err)
	}
}

func TestDesignInsideAGitWorkTreeCopiesTheWorkTree(t *testing.T) {
	dir := t.TempDir()
	repo := filepath.Join(dir, "repo")
	design := filepath.Join(repo, "docs", "design")
	writeFile(t, filepath.Join(design, "BUILD.md"), "x\n", 0o644)
	writeFile(t, filepath.Join(repo, ".git", "HEAD"), "ref: refs/heads/main\n", 0o644)
	canned := "== Gu-surfaces  target surface ledger ==\n  ok\n\n0 blocking (ERROR/DRIFT) finding(s)\n"
	// the fake proves it runs from the copied work tree root with the design relative to it
	probe := `[ -f .git/HEAD ] && [ "$2" = "docs/design" ] || { echo "not at the work tree root" >&2; exit 3; }`
	oldBin := writeFake(t, dir, "old", fake{version: "v1", canned: canned, before: probe})
	newBin := writeFake(t, dir, "new", fake{version: "v2", canned: canned, before: probe})
	code, out, stderr := runTool(t, "-old", oldBin, "-new", newBin, "-design", design)
	if code != exitOK {
		t.Fatalf("exit = %d\n%s%s", code, out, stderr)
	}
}

// TestRealBinaryOverAMutatedExampleCopy runs the machinery binary built from
// this tree on both sides; the candidate side is a wrapper that adds an
// em dash to its private copy, which the house-style gate reports.
func TestRealBinaryOverAMutatedExampleCopy(t *testing.T) {
	if testing.Short() {
		t.Skip("builds the machinery binary")
	}
	if runtime.GOOS == "windows" {
		t.Skip("the wrapper is a POSIX shell script")
	}
	dir := t.TempDir()
	real := filepath.Join(dir, "machinery")
	build := exec.CommandContext(t.Context(), "go", "build", "-o", real, "./cmd/machinery")
	build.Dir = filepath.Join("..", "..")
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build machinery: %v\n%s", err, out)
	}
	design := filepath.Join(dir, "design")
	if err := copyTree(filepath.Join("..", "..", "examples", "fulfillment", "design"), design); err != nil {
		t.Fatal(err)
	}
	before, err := hashTree(design)
	if err != nil {
		t.Fatal(err)
	}
	wrapper := filepath.Join(dir, "candidate")
	script := "#!/bin/sh\nif [ \"$1\" = check ]; then printf 'A note \\342\\200\\224 with a dash.\\n' > \"$2/NOTES.md\"; fi\nexec '" + real + "' \"$@\"\n"
	if err := os.WriteFile(wrapper, []byte(script), 0o700); err != nil {
		t.Fatal(err)
	}

	code, out, stderr := runTool(t, "-old", real, "-new", wrapper, "-design", design)
	if code != exitUnexplained {
		t.Fatalf("exit = %d, want 1\n%s%s", code, out, stderr)
	}
	for _, want := range []string{
		"== new findings: 0 blocking, 1 warnings, 0 notes ==",
		"  Gl-ledger      warn  NOTES.md:1: em dash (U+2014); house style forbids it",
		"  Gl-ledger      ok -> warn",
		"note: the new binary wrote into its private copy of the tree (the original is unchanged): NOTES.md",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("report lacks %q\n%s", want, out)
		}
	}

	allow := writeAllow(t, "gl warn /^NOTES\\.md:1: em dash/ the synthetic mutation adds exactly this line\n")
	code, out, stderr = runTool(t, "-old", real, "-new", wrapper, "-design", design, "-allow", allow)
	if code != exitOK {
		t.Fatalf("with allow: exit = %d, want 0\n%s%s", code, out, stderr)
	}

	after, err := hashTree(design)
	if err != nil {
		t.Fatal(err)
	}
	if d := diffManifests(before, after); len(d) > 0 {
		t.Fatalf("the example copy changed: %v", d)
	}
}
