// Command consumer-diff compares two machinery binaries over one real
// consumer design and fails when the candidate introduces findings nobody
// explained.
//
// It runs `machinery check` with each binary over the same design and the
// same flags, parses both outputs into findings keyed by (gate, severity,
// normalized message), and reports three sections: new findings, resolved
// findings, and changed gate verdicts. Every new blocking finding (ERROR or
// DRIFT) and every new warning must match an entry of the allow file, or the
// run fails. Notes never gate.
//
// The design is never touched. The tree that holds it (the enclosing git work
// tree, so Ga-accept still sees the repository history, or the design
// directory itself outside git) is hashed, copied once per binary into a
// temporary directory, and hashed again after both runs; any change to the
// original is an execution error. Writes a binary makes into its own copy are
// reported, not fatal.
//
// Normalization strips what differs between two runs of the same design but
// says nothing about the gates: the temporary copy paths, other temporary
// paths, durations, and version strings (so a version-skew note or a stamp
// named in a message keys the same under both binaries). The checked: lines
// are not findings, so their counts never produce a difference.
//
// Version-stamp skew (a design regenerated by another machinery version than
// the one running) is kept apart from regressions: the report states, per
// run, which versions stamped the artifacts, and tags that run's DRIFT
// findings and its skew note [stamp-skew]. Skew in the baseline run lands in
// the resolved section and can never raise the exit code; skew in the
// candidate run is a generator change consumers must regenerate for, so its
// DRIFT still gates and needs an allow entry that names the release note.
//
// Allow file, one entry per line (blank lines and # comments are ignored):
//
//	<gate> <severity> /<regexp>/ <reason>
//
// gate is a gate id as printed (Gx-trace), its short form (gx), or *;
// severity is error, drift or warn; the regexp (RE2, a literal slash written
// \/) is matched against the normalized message as the report prints it; the
// reason is mandatory. Entries that match no new finding are reported as
// unused so the list does not rot.
//
// Exit codes: 0 when every new blocking finding and warning is allowed; 1
// when at least one is not; 2 on a usage or execution error (a binary that
// crashes or prints no summary, a missing design, a design tree that changed).
// `go run` reports every nonzero exit as 1; build the binary, or use
// `make consumer-diff`, to see the distinct codes.
//
//	go run ./scripts/consumer-diff -old <bin> -new <bin> -design <dir>
//	go run ./scripts/consumer-diff -old <bin> -new <bin> -design <dir> -impl <dir> -allow allow.txt
//	go run ./scripts/consumer-diff -old <bin> -new <bin> -design <dir> -json
package main

import (
	"bytes"
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

const (
	exitOK          = 0
	exitUnexplained = 1
	exitError       = 2
)

type options struct {
	oldBin, newBin string
	design, impl   string
	commit, gates  string
	allow          string
	json           bool
	timeout        time.Duration
}

func main() { os.Exit(run(os.Args[1:], os.Stdout, os.Stderr)) }

// run is the whole command; it returns the exit code so tests can drive it.
func run(args []string, stdout, stderr io.Writer) int {
	opt, err := parseFlags(args, stderr)
	if err != nil {
		if !errors.Is(err, flag.ErrHelp) {
			fmt.Fprintf(stderr, "consumer-diff: %v\n", err)
		}
		return exitError
	}
	rep, err := compare(opt)
	if err != nil {
		fmt.Fprintf(stderr, "consumer-diff: %v\n", err)
		return exitError
	}
	if opt.json {
		if err := rep.writeJSON(stdout); err != nil {
			fmt.Fprintf(stderr, "consumer-diff: %v\n", err)
			return exitError
		}
	} else {
		rep.writeText(stdout)
	}
	return rep.Exit
}

func parseFlags(args []string, stderr io.Writer) (options, error) {
	var opt options
	fs := flag.NewFlagSet("consumer-diff", flag.ContinueOnError)
	fs.SetOutput(stderr)
	fs.StringVar(&opt.oldBin, "old", "", "baseline machinery binary (the last release)")
	fs.StringVar(&opt.newBin, "new", "", "candidate machinery binary")
	fs.StringVar(&opt.design, "design", "", "consumer design directory (never modified)")
	fs.StringVar(&opt.impl, "impl", "", "implementation directory, passed to both runs as --impl")
	fs.StringVar(&opt.commit, "commit", "", "history anchor, passed to both runs as --commit")
	fs.StringVar(&opt.gates, "gates", "", "comma list of gates, passed to both runs as --gate")
	fs.StringVar(&opt.allow, "allow", "", "allow file explaining expected new findings")
	fs.BoolVar(&opt.json, "json", false, "print the report as JSON")
	fs.DurationVar(&opt.timeout, "timeout", 30*time.Minute, "limit for each machinery check run")
	fs.Usage = func() {
		fmt.Fprintln(stderr, "usage: consumer-diff -old <binary> -new <binary> -design <dir> [-impl <dir>] [-commit <sha>] [-gates <list>] [-allow <file>] [-json]")
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		return opt, err
	}
	if fs.NArg() > 0 {
		fs.Usage()
		return opt, fmt.Errorf("unexpected arguments: %s", strings.Join(fs.Args(), " "))
	}
	var missing []string
	for _, f := range []struct{ name, val string }{{"-old", opt.oldBin}, {"-new", opt.newBin}, {"-design", opt.design}} {
		if f.val == "" {
			missing = append(missing, f.name)
		}
	}
	if len(missing) > 0 {
		fs.Usage()
		return opt, fmt.Errorf("missing required %s", strings.Join(missing, ", "))
	}
	if opt.timeout <= 0 {
		return opt, fmt.Errorf("-timeout must be positive")
	}
	return opt, nil
}

// side is one binary's run over its own copy of the tree.
type side struct {
	label   string
	binary  string
	version string
	result  *checkRun
	writes  []string // paths the binary changed inside its copy
	stderr  string
}

// layout says where the design and implementation sit inside the copied tree.
type layout struct {
	root      string // tree copied per run: git work tree or the design itself
	designRel string // design path relative to root, as passed to the binary
	impl      string // absolute original impl, "" when none
	implRel   string // impl relative to root when it lives inside it
}

func compare(opt options) (*report, error) {
	oldBin, err := resolveBinary(opt.oldBin)
	if err != nil {
		return nil, fmt.Errorf("-old: %w", err)
	}
	newBin, err := resolveBinary(opt.newBin)
	if err != nil {
		return nil, fmt.Errorf("-new: %w", err)
	}
	lay, err := resolveLayout(opt.design, opt.impl)
	if err != nil {
		return nil, err
	}
	var allows []*allowEntry
	if opt.allow != "" {
		if allows, err = parseAllowFile(opt.allow); err != nil {
			return nil, err
		}
	}

	rootBefore, err := hashTree(lay.root)
	if err != nil {
		return nil, fmt.Errorf("hash design tree: %w", err)
	}
	var implBefore manifest
	if lay.impl != "" && lay.implRel == "" {
		if implBefore, err = hashTree(lay.impl); err != nil {
			return nil, fmt.Errorf("hash impl tree: %w", err)
		}
	}

	sides := []*side{{label: "old", binary: oldBin}, {label: "new", binary: newBin}}
	for _, s := range sides {
		if err := s.execute(opt, lay, rootBefore, implBefore); err != nil {
			return nil, err
		}
	}

	if err := unchanged(lay.root, rootBefore); err != nil {
		return nil, err
	}
	if implBefore != nil {
		if err := unchanged(lay.impl, implBefore); err != nil {
			return nil, err
		}
	}

	rep := buildReport(sides[0], sides[1], allows)
	rep.Design = opt.design
	rep.Impl = opt.impl
	rep.Args = checkArgs(opt, "<design>", implArgPlaceholder(opt.impl))
	return rep, nil
}

func implArgPlaceholder(impl string) string {
	if impl == "" {
		return ""
	}
	return "<impl>"
}

// unchanged re-hashes an original tree and fails loudly when any path moved.
func unchanged(root string, before manifest) error {
	after, err := hashTree(root)
	if err != nil {
		return fmt.Errorf("re-hash %s: %w", root, err)
	}
	if changed := diffManifests(before, after); len(changed) > 0 {
		return fmt.Errorf("the original tree %s CHANGED during the comparison (%d paths: %s); the results are void", root, len(changed), preview(changed, 10))
	}
	return nil
}

func preview(paths []string, n int) string {
	if len(paths) <= n {
		return strings.Join(paths, ", ")
	}
	return strings.Join(paths[:n], ", ") + fmt.Sprintf(", and %d more", len(paths)-n)
}

func resolveBinary(path string) (string, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	fi, err := os.Stat(abs)
	if err != nil {
		return "", fmt.Errorf("binary %s: %w", path, err)
	}
	if !fi.Mode().IsRegular() || fi.Mode().Perm()&0o111 == 0 {
		return "", fmt.Errorf("binary %s is not an executable file", path)
	}
	return abs, nil
}

func resolveLayout(design, impl string) (layout, error) {
	var lay layout
	absDesign, err := filepath.Abs(design)
	if err != nil {
		return lay, err
	}
	fi, err := os.Stat(absDesign)
	if err != nil {
		return lay, fmt.Errorf("design %s does not exist", design)
	}
	if !fi.IsDir() {
		return lay, fmt.Errorf("design %s is not a directory", design)
	}
	lay.root = findCopyRoot(absDesign)
	if lay.designRel, err = filepath.Rel(lay.root, absDesign); err != nil {
		return lay, err
	}
	if impl == "" {
		return lay, nil
	}
	if lay.impl, err = filepath.Abs(impl); err != nil {
		return lay, err
	}
	fi, err = os.Stat(lay.impl)
	if err != nil {
		return lay, fmt.Errorf("impl %s does not exist", impl)
	}
	if !fi.IsDir() {
		return lay, fmt.Errorf("impl %s is not a directory", impl)
	}
	if rel, err := filepath.Rel(lay.root, lay.impl); err == nil && rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		lay.implRel = rel
	}
	return lay, nil
}

// checkArgs is the argument list both binaries receive, identical by
// construction.
func checkArgs(opt options, design, impl string) []string {
	args := []string{"check", design}
	if impl != "" {
		args = append(args, "--impl", impl)
	}
	if opt.commit != "" {
		args = append(args, "--commit", opt.commit)
	}
	if opt.gates != "" {
		args = append(args, "--gate", opt.gates)
	}
	return args
}

// execute copies the tree, runs the binary on the copy, and parses the run.
func (s *side) execute(opt options, lay layout, rootBefore, implBefore manifest) error {
	s.version = binaryVersion(s.binary)
	work, err := os.MkdirTemp("", "consumer-diff-"+s.label+"-")
	if err != nil {
		return err
	}
	defer removeTree(work)
	// The copy keeps the tree's own name, and the run starts where the
	// consumer would start it: at the work tree root with the design relative
	// to it, or beside a design outside git with the design named as given.
	root := filepath.Join(work, "tree", filepath.Base(lay.root))
	cwd, designArg := root, lay.designRel
	if lay.designRel == "." {
		cwd, designArg = filepath.Dir(root), filepath.Base(root)
	}
	if err := os.MkdirAll(filepath.Dir(root), 0o700); err != nil {
		return err
	}
	if err := copyTree(lay.root, root); err != nil {
		return fmt.Errorf("copy design tree for the %s run: %w", s.label, err)
	}
	if err := sameTree(root, rootBefore); err != nil {
		return fmt.Errorf("%s run copy: %w", s.label, err)
	}
	implArg, implCopy := "", ""
	switch {
	case lay.impl != "" && lay.implRel != "":
		implArg = filepath.Join(root, lay.implRel)
		if rel, err := filepath.Rel(cwd, implArg); err == nil {
			implArg = rel
		}
	case lay.impl != "":
		implCopy = filepath.Join(work, "impl")
		if err := copyTree(lay.impl, implCopy); err != nil {
			return fmt.Errorf("copy impl tree for the %s run: %w", s.label, err)
		}
		if err := sameTree(implCopy, implBefore); err != nil {
			return fmt.Errorf("%s run impl copy: %w", s.label, err)
		}
		implArg = implCopy
	}
	args := checkArgs(opt, designArg, implArg)

	ctx, cancel := context.WithTimeout(context.Background(), opt.timeout)
	defer cancel()
	cmd := exec.CommandContext(ctx, s.binary, args...)
	cmd.Dir = cwd
	var out, errOut bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &errOut
	runErr := cmd.Run()
	s.stderr = errOut.String()
	code := 0
	if runErr != nil {
		var exitErr *exec.ExitError
		switch {
		case ctx.Err() != nil:
			return fmt.Errorf("%s binary %s timed out after %s", s.label, s.binary, opt.timeout)
		case errors.As(runErr, &exitErr) && exitErr.Exited():
			code = exitErr.ExitCode()
		default:
			return fmt.Errorf("%s binary %s did not complete: %w%s", s.label, s.binary, runErr, tail(s.stderr))
		}
	}

	norm := newNormalizer(root, implCopy)
	res, err := parseCheck(out.String(), norm)
	if err != nil {
		return fmt.Errorf("%s binary %s: %w%s", s.label, s.binary, err, tail(s.stderr))
	}
	if !res.HasSummary {
		return fmt.Errorf("%s binary %s exited %d without the final blocking-count line (crash or usage error)%s", s.label, s.binary, code, tail(s.stderr))
	}
	if (code == 0) != (res.Summary == 0) || code > 1 {
		return fmt.Errorf("%s binary %s exited %d but reported %d blocking finding(s); a check exits 1 exactly when something blocks%s", s.label, s.binary, code, res.Summary, tail(s.stderr))
	}
	if got := res.count(sevError) + res.count(sevDrift); got != res.Summary {
		return fmt.Errorf("%s binary %s reported %d blocking finding(s) but the parser found %d ERROR/DRIFT lines; the output format is not understood", s.label, s.binary, res.Summary, got)
	}
	res.Exit = code
	s.result = res

	after, err := hashTree(root)
	if err != nil {
		return fmt.Errorf("re-hash the %s run copy: %w", s.label, err)
	}
	s.writes = diffManifests(rootBefore, after)
	if implCopy != "" {
		afterImpl, err := hashTree(implCopy)
		if err != nil {
			return fmt.Errorf("re-hash the %s run impl copy: %w", s.label, err)
		}
		for _, p := range diffManifests(implBefore, afterImpl) {
			s.writes = append(s.writes, "<impl>/"+p)
		}
	}
	return nil
}

// sameTree proves a fresh copy is byte-identical to the original manifest.
func sameTree(root string, want manifest) error {
	got, err := hashTree(root)
	if err != nil {
		return err
	}
	if d := diffManifests(want, got); len(d) > 0 {
		return fmt.Errorf("copy differs from the original at %s", preview(d, 10))
	}
	return nil
}

func tail(stderr string) string {
	stderr = strings.TrimSpace(stderr)
	if stderr == "" {
		return ""
	}
	lines := strings.Split(stderr, "\n")
	if len(lines) > 20 {
		lines = lines[len(lines)-20:]
	}
	return "; stderr:\n  " + strings.Join(lines, "\n  ")
}

// binaryVersion asks the binary for its version; "unknown" when it cannot
// say, which the report shows rather than hides.
func binaryVersion(bin string) string {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	out, err := exec.CommandContext(ctx, bin, "--version").Output()
	if err != nil {
		return "unknown"
	}
	fields := strings.Fields(string(out))
	if len(fields) == 0 {
		return "unknown"
	}
	return fields[len(fields)-1]
}
