package main

import (
	"fmt"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// Severities as `machinery check` prints them.
const (
	sevError = "ERROR"
	sevDrift = "DRIFT"
	sevWarn  = "warn"
	sevNote  = "note"
)

// runGate is the pseudo-gate for lines printed outside any gate section: the
// selection note before the gates and the version-skew note after them.
const runGate = "(run)"

// Gate verdicts: fail (ERROR or DRIFT), warn (warnings only), ok, or absent
// (the run printed no such gate).
const (
	verdictOK     = "ok"
	verdictWarn   = "warn"
	verdictFail   = "fail"
	verdictAbsent = "absent"
)

var sevRank = map[string]int{sevError: 0, sevDrift: 1, sevWarn: 2, sevNote: 3}

// finding is one normalized line (plus any continuation lines).
type finding struct {
	Gate     string
	Severity string
	Message  string
}

func (f finding) key() string { return f.Gate + "\x00" + f.Severity + "\x00" + f.Message }

func (f finding) blocking() bool { return f.Severity == sevError || f.Severity == sevDrift }

// gating findings must be explained by the allow file when they are new.
func (f finding) gating() bool { return f.blocking() || f.Severity == sevWarn }

type gateResult struct {
	ID       string
	Title    string
	Findings []finding
}

func (g *gateResult) verdict() string {
	v := verdictOK
	for _, f := range g.Findings {
		switch {
		case f.blocking():
			return verdictFail
		case f.Severity == sevWarn:
			v = verdictWarn
		}
	}
	return v
}

// checkRun is one parsed `machinery check` output.
type checkRun struct {
	Gates      []*gateResult
	RunNotes   []finding
	HasSummary bool
	Summary    int    // the binary's own blocking count
	Status     string // design-green / platform-green line, when printed
	Exit       int
	Skew       *stampSkew
}

// stampSkew is what the version-skew note says: the committed artifacts were
// generated by other machinery versions than the running one.
type stampSkew struct {
	Stamped []string `json:"stamped"`
	Running string   `json:"running"`
}

func (r *checkRun) findings() []finding {
	var all []finding
	for _, g := range r.Gates {
		all = append(all, g.Findings...)
	}
	return append(all, r.RunNotes...)
}

func (r *checkRun) count(sev string) int {
	n := 0
	for _, f := range r.findings() {
		if f.Severity == sev {
			n++
		}
	}
	return n
}

func (r *checkRun) verdicts() map[string]string {
	v := map[string]string{}
	for _, g := range r.Gates {
		v[g.ID] = g.verdict()
	}
	return v
}

var (
	headerRE  = regexp.MustCompile(`^== (\S+)\s*(.*?) ==$`)
	summaryRE = regexp.MustCompile(`^(\d+) blocking \(ERROR/DRIFT(?:/warning)?\) finding\(s\)`)
	skewRE    = regexp.MustCompile(`^note: artifacts generated by machinery (.+), running (\S+); regenerate on upgrade`)
	findingRE = regexp.MustCompile(`^  (ERROR|DRIFT|warn|note) +(.*)$`)
)

// parseCheck reads the output of `machinery check`. A line inside a gate that
// is not a finding, a checked: line, or ok continues the previous finding
// (multi-line messages and --explain derivations); with no previous finding
// it is a format this parser does not understand, which is an error rather
// than a silent drop.
func parseCheck(out string, norm *normalizer) (*checkRun, error) {
	res := &checkRun{}
	var gate *gateResult
	var last *finding // the finding a continuation line belongs to
	var lastGate *gateResult
	var lastRaw *strings.Builder
	flush := func() {
		if last != nil {
			last.Message = norm.apply(lastRaw.String())
			if lastGate != nil {
				lastGate.Findings = append(lastGate.Findings, *last)
			} else {
				res.RunNotes = append(res.RunNotes, *last)
			}
		}
		last, lastGate, lastRaw = nil, nil, nil
	}
	start := func(f finding, in *gateResult, raw string) {
		flush()
		last, lastGate, lastRaw = &f, in, &strings.Builder{}
		lastRaw.WriteString(raw)
	}
	lines := strings.Split(strings.TrimRight(out, "\n"), "\n")
	for i, line := range lines {
		line = strings.TrimRight(line, "\r")
		if m := headerRE.FindStringSubmatch(line); m != nil {
			flush()
			gate = &gateResult{ID: m[1], Title: m[2]}
			res.Gates = append(res.Gates, gate)
			continue
		}
		if line == "" {
			flush()
			gate = nil
			continue
		}
		if gate != nil && strings.HasPrefix(line, " ") {
			switch m := findingRE.FindStringSubmatch(line); {
			case m != nil:
				start(finding{Gate: gate.ID, Severity: m[1]}, gate, m[2])
			case strings.HasPrefix(line, "  checked: "), line == "  ok":
				flush()
			case last != nil:
				lastRaw.WriteString("\n" + strings.TrimSpace(line))
			default:
				return nil, fmt.Errorf("line %d: unrecognized output inside gate %s: %q", i+1, gate.ID, line)
			}
			continue
		}
		// outside a gate section
		gate = nil
		if m := summaryRE.FindStringSubmatch(line); m != nil {
			flush()
			n, err := strconv.Atoi(m[1])
			if err != nil {
				return nil, fmt.Errorf("line %d: %w", i+1, err)
			}
			res.HasSummary, res.Summary = true, n
			continue
		}
		if strings.HasPrefix(line, "design-green:") || strings.HasPrefix(line, "platform-green:") {
			flush()
			res.Status = strings.SplitN(line, ":", 2)[0]
			continue
		}
		if last != nil && lastGate == nil {
			lastRaw.WriteString("\n" + strings.TrimSpace(line))
			continue
		}
		if m := skewRE.FindStringSubmatch(line); m != nil {
			stamped := strings.Split(m[1], ", ")
			sort.Strings(stamped)
			res.Skew = &stampSkew{Stamped: stamped, Running: m[2]}
		}
		start(finding{Gate: runGate, Severity: sevNote}, nil, strings.TrimSpace(line))
	}
	flush()
	return res, nil
}

// normalizer rewrites the parts of a message that differ between two runs of
// the same design but say nothing about the gates.
type normalizer struct {
	paths []pathSub
}

type pathSub struct{ from, to string }

var (
	tempPathRE = regexp.MustCompile(`(?:/private)?/(?:var/folders|tmp)/[^\s'"(),;]+`)
	durationRE = regexp.MustCompile(`\b\d+(?:\.\d+)?(?:ns|µs|us|ms|s)\b|\b\d+h(?:\d+m)?(?:\d+(?:\.\d+)?s)?\b|\b\d+m\d+(?:\.\d+)?s\b`)
	versionRE  = regexp.MustCompile(`\bv\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?\b`)
	bareVerRE  = regexp.MustCompile(`\bmachinery \d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?\b`)
)

// newNormalizer maps the run's copy root to <root> and a separately copied
// implementation to <impl>, under the path as given and as resolved (macOS
// reaches /var through the /private/var symlink).
func newNormalizer(root, impl string) *normalizer {
	n := &normalizer{}
	add := func(p, to string) {
		if p == "" {
			return
		}
		n.paths = append(n.paths, pathSub{p, to})
		if strings.HasPrefix(p, "/var/") || strings.HasPrefix(p, "/tmp/") {
			n.paths = append(n.paths, pathSub{"/private" + p, to})
		}
		if real, err := filepath.EvalSymlinks(p); err == nil && real != p {
			n.paths = append(n.paths, pathSub{real, to})
		}
	}
	add(impl, "<impl>")
	add(root, "<root>")
	// longest first, so a path never loses to its own prefix
	sort.SliceStable(n.paths, func(i, j int) bool { return len(n.paths[i].from) > len(n.paths[j].from) })
	return n
}

func (n *normalizer) apply(s string) string {
	for _, p := range n.paths {
		s = strings.ReplaceAll(s, p.from, p.to)
	}
	s = tempPathRE.ReplaceAllString(s, "<tmp>")
	s = durationRE.ReplaceAllString(s, "<duration>")
	s = versionRE.ReplaceAllString(s, "<version>")
	return bareVerRE.ReplaceAllString(s, "machinery <version>")
}
