package main

import (
	"reflect"
	"strings"
	"testing"
)

// Synthetic `machinery check` output: every line shape the parser meets.
const parseFixture = `note: decomposed parent with no machines/; running gu,gx
== Gu-surfaces  target surface ledger ==
  checked: 3 obligated actions, 3 covered
  ok
== Gx-trace  cross-layer traceability ==
  ERROR  /work/tree/design/Order.matrix.md:4: unknown group
         derivation: rule 3 over fact order_state
  ERROR  /work/tree/design/Order.matrix.md:4: unknown group
  warn   Order.matrix.md:12: undeclared fact reference ` + "`carrier`" + `
  note   Order: 2 operational-overlay states (persisting, persistRetry)
  checked: 4 entities
== Gv-attest  attestation evidence ==
  DRIFT  oracle stale, generated by machinery v0.2.0 in 1.5s at /tmp/alloy-123/run.als
  checked: 2 claims
note: artifacts generated by machinery v0.2.0, v0.1.9, running v0.1.0; regenerate on upgrade:
  machinery oracle design/machines
the regeneration lands as its own dedicated stamp-only commit, never mixed with a design change

3 blocking (ERROR/DRIFT) finding(s)
`

func TestParseCheckReadsEveryLineShape(t *testing.T) {
	res, err := parseCheck(parseFixture, newNormalizer("/work/tree", ""))
	if err != nil {
		t.Fatal(err)
	}
	if !res.HasSummary || res.Summary != 3 {
		t.Fatalf("summary = %v/%d, want true/3", res.HasSummary, res.Summary)
	}
	var ids []string
	for _, g := range res.Gates {
		ids = append(ids, g.ID+"="+g.verdict())
	}
	if want := []string{"Gu-surfaces=ok", "Gx-trace=fail", "Gv-attest=fail"}; !reflect.DeepEqual(ids, want) {
		t.Fatalf("gates = %v, want %v", ids, want)
	}
	gx := res.Gates[1]
	if gx.Title != "cross-layer traceability" {
		t.Fatalf("title = %q", gx.Title)
	}
	want := []finding{
		{"Gx-trace", sevError, "<root>/design/Order.matrix.md:4: unknown group\nderivation: rule 3 over fact order_state"},
		{"Gx-trace", sevError, "<root>/design/Order.matrix.md:4: unknown group"},
		{"Gx-trace", sevWarn, "Order.matrix.md:12: undeclared fact reference `carrier`"},
		{"Gx-trace", sevNote, "Order: 2 operational-overlay states (persisting, persistRetry)"},
	}
	if !reflect.DeepEqual(gx.Findings, want) {
		t.Fatalf("Gx findings:\n got %#v\nwant %#v", gx.Findings, want)
	}
	drift := res.Gates[2].Findings[0]
	if drift.Message != "oracle stale, generated by machinery <version> in <duration> at <tmp>" {
		t.Fatalf("drift message = %q", drift.Message)
	}
	if len(res.RunNotes) != 2 {
		t.Fatalf("run notes = %#v, want the selection note and the skew note", res.RunNotes)
	}
	if res.RunNotes[0].Gate != runGate || !strings.HasPrefix(res.RunNotes[0].Message, "note: decomposed parent") {
		t.Fatalf("selection note = %#v", res.RunNotes[0])
	}
	skew := res.RunNotes[1].Message
	if !strings.HasPrefix(skew, "note: artifacts generated by machinery <version>, <version>, running <version>") ||
		!strings.Contains(skew, "\nmachinery oracle design/machines\nthe regeneration lands") {
		t.Fatalf("skew note = %q", skew)
	}
	if res.Skew == nil || !reflect.DeepEqual(res.Skew.Stamped, []string{"v0.1.9", "v0.2.0"}) || res.Skew.Running != "v0.1.0" {
		t.Fatalf("skew = %#v", res.Skew)
	}
	if got := res.count(sevError) + res.count(sevDrift); got != 3 {
		t.Fatalf("blocking = %d, want 3", got)
	}
}

func TestParseCheckStatusAndWarningsAsErrorsSummary(t *testing.T) {
	out := "== Gu-surfaces  target surface ledger ==\n  checked: 1 obligated actions\n  ok\n\n0 blocking (ERROR/DRIFT/warning) finding(s); warnings are errors\ndesign-green: all applicable design gates green\n"
	res, err := parseCheck(out, newNormalizer("/x", ""))
	if err != nil {
		t.Fatal(err)
	}
	if !res.HasSummary || res.Summary != 0 || res.Status != "design-green" {
		t.Fatalf("got %#v", res)
	}
}

func TestParseCheckRejectsAnUnknownLineShape(t *testing.T) {
	out := "== Gu-surfaces  target surface ledger ==\n  surprise: a line nobody understands\n  ok\n"
	if _, err := parseCheck(out, newNormalizer("/x", "")); err == nil || !strings.Contains(err.Error(), "unrecognized output inside gate Gu-surfaces") {
		t.Fatalf("err = %v, want an unrecognized-line error", err)
	}
}

func TestParseCheckWithoutSummary(t *testing.T) {
	res, err := parseCheck("== Gu-surfaces  target surface ledger ==\n  ok\n", newNormalizer("/x", ""))
	if err != nil {
		t.Fatal(err)
	}
	if res.HasSummary {
		t.Fatal("a run without the blocking-count line must not count as summarized")
	}
}

func TestNormalizerStripsVolatileParts(t *testing.T) {
	n := newNormalizer("/var/folders/ab/T/consumer-diff-new-1/tree", "/var/folders/ab/T/consumer-diff-new-1/impl")
	cases := map[string]string{
		"/var/folders/ab/T/consumer-diff-new-1/tree/design/BUILD.md:3: x":         "<root>/design/BUILD.md:3: x",
		"/private/var/folders/ab/T/consumer-diff-new-1/tree/design/BUILD.md: x":   "<root>/design/BUILD.md: x",
		"reads /var/folders/ab/T/consumer-diff-new-1/impl/lib/a.ex":               "reads <impl>/lib/a.ex",
		"scratch at /tmp/machinery-alloy-99/out.als, retried":                     "scratch at <tmp>, retried",
		"solver took 12ms, then 1.25s, then 2m3.5s, then 1h2m":                    "solver took <duration>, then <duration>, then <duration>, then <duration>",
		"generated by machinery v0.10.0 and v1.2.3-rc.1, not machinery 0.9.0":     "generated by machinery <version> and <version>, not machinery <version>",
		"sha256:3bbcb8cd1e3a72c8b1255d9ac7ae40e613132d443cd34c29fad817c10d2486ee": "sha256:3bbcb8cd1e3a72c8b1255d9ac7ae40e613132d443cd34c29fad817c10d2486ee",
		"section 5.1.2 and 71 operational-overlay states":                         "section 5.1.2 and 71 operational-overlay states",
	}
	for in, want := range cases {
		if got := n.apply(in); got != want {
			t.Errorf("apply(%q) = %q, want %q", in, got, want)
		}
	}
}
