package main

// RED phase (MAC-2n83): the `machinery recover` command battery, written
// against the DESIGNED contract. On unmodified production every test below
// except the fail-closed control fails with cobra's unknown-command error
// instead of the contracted report. The crash fixtures use real subprocess
// death (os.Exit(9)) at meaningful publication boundaries over a real
// filesystem; no in-process simulation stands in for a crash.

import (
	"bytes"
	"context"
	"crypto/sha256"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/RamXX/machinery/internal/designlock"
)

const recoverFixtureWriter = "recover-fixture"
const recoverFixtureRecovery = "rerun `machinery example-writer` with the same arguments"

func recoverSeedFixture(t *testing.T, design string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(design, "source.md"), []byte("design inputs must survive every recovery path\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(design, "stale.txt"), []byte("obsolete output\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(design, "generated.txt"), []byte("obsolete output\n"), 0o644); err != nil {
		t.Fatal(err)
	}
}

func recoverFixtureExpected(design string) ([]designlock.OutputExpectation, error) {
	tree, err := designlock.ExpectTree(filepath.Join(design, "generated-tree"), map[string][]byte{"nested/report.txt": []byte("tree output body\n")}, 0o755, 0o644)
	if err != nil {
		return nil, err
	}
	return []designlock.OutputExpectation{
		designlock.ExpectFile(filepath.Join(design, "generated.txt"), []byte("generated by the interrupted writer\n"), 0o644),
		tree,
		designlock.ExpectAbsent(filepath.Join(design, "stale.txt")),
	}, nil
}

func recoverWriteExact(path string, body []byte, mode os.FileMode) error {
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err := os.WriteFile(path, body, mode); err != nil {
		return err
	}
	return os.Chmod(path, mode)
}

func recoverFixtureWriteAll(design string) error {
	if err := recoverWriteExact(filepath.Join(design, "generated.txt"), []byte("generated by the interrupted writer\n"), 0o644); err != nil {
		return err
	}
	treeDir := filepath.Join(design, "generated-tree", "nested")
	if err := os.MkdirAll(treeDir, 0o755); err != nil {
		return err
	}
	if err := os.Chmod(filepath.Join(design, "generated-tree"), 0o755); err != nil {
		return err
	}
	if err := os.Chmod(treeDir, 0o755); err != nil {
		return err
	}
	if err := recoverWriteExact(filepath.Join(treeDir, "report.txt"), []byte("tree output body\n"), 0o644); err != nil {
		return err
	}
	return os.Remove(filepath.Join(design, "stale.txt"))
}

// TestRecoverCrashHelper is the subprocess fixture driver for the CLI
// battery. Modes:
//
//	complete  every declared output reaches its exact content and mode, then
//	          the process dies before the publication proves and clears
//	partial   only the first output is written, then the process dies
//	hold      acquires and holds the design lock so a concurrent writer is
//          genuinely live while the parent asserts refusal
func TestRecoverCrashHelper(t *testing.T) {
	design := os.Getenv("MACHINERY_RECOVER_CRASH_DESIGN")
	mode := os.Getenv("MACHINERY_RECOVER_CRASH_MODE")
	if design == "" || mode == "" {
		return
	}
	die := func() { os.Exit(9) }
	lock, err := designlock.Acquire(design)
	if err != nil {
		fmt.Fprintf(os.Stderr, "fixture acquire: %v\n", err)
		os.Exit(3)
	}
	switch mode {
	case "hold":
		marker := os.Getenv("MACHINERY_RECOVER_HOLD_MARKER")
		if err := os.WriteFile(marker, []byte("held\n"), 0o600); err != nil {
			os.Exit(3)
		}
		time.Sleep(2 * time.Minute)
		os.Exit(0)
	case "complete", "partial":
	default:
		fmt.Fprintf(os.Stderr, "unknown recover crash mode %q\n", mode)
		os.Exit(3)
	}
	expected, err := recoverFixtureExpected(design)
	if err != nil {
		fmt.Fprintf(os.Stderr, "fixture expectations: %v\n", err)
		os.Exit(3)
	}
	callbackErr := lock.PublishExpectedRooted(recoverFixtureWriter, recoverFixtureRecovery, expected, func(*designlock.OutputScope) error {
		if mode == "partial" {
			if err := recoverWriteExact(filepath.Join(design, "generated.txt"), []byte("generated by the interrupted writer\n"), 0o644); err != nil {
				return err
			}
			die()
		}
		if err := recoverFixtureWriteAll(design); err != nil {
			return err
		}
		die()
		return nil
	})
	fmt.Fprintf(os.Stderr, "recover crash helper completed without dying: callback=%v\n", callbackErr)
	os.Exit(3)
}

func recoverCrashFixture(t *testing.T, mode string) string {
	t.Helper()
	design := t.TempDir()
	recoverSeedFixture(t, design)
	executable, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()
	cmd := exec.CommandContext(ctx, executable, "-test.run=^TestRecoverCrashHelper$")
	cmd.Env = append(os.Environ(), "MACHINERY_RECOVER_CRASH_DESIGN="+design, "MACHINERY_RECOVER_CRASH_MODE="+mode)
	out, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("recover crash fixture %s completed without crashing: %s", mode, out)
	}
	var exit *exec.ExitError
	if !errors.As(err, &exit) || exit.ExitCode() != 9 {
		t.Fatalf("recover crash fixture %s did not die by process death: %v %s", mode, err, out)
	}
	return design
}

func recoverHoldDesign(t *testing.T, design string) {
	t.Helper()
	marker := filepath.Join(t.TempDir(), "hold-marker")
	executable, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}
	// Plain exec.Command: an exec.CommandContext cancellation (including a
	// deferred one firing when this helper returns) would kill the holder the
	// instant the marker appears and silently void the concurrency fixture.
	// The holder is terminated explicitly by the test cleanup instead.
	cmd := exec.Command(executable, "-test.run=^TestRecoverCrashHelper$")
	cmd.Env = append(os.Environ(), "MACHINERY_RECOVER_CRASH_DESIGN="+design, "MACHINERY_RECOVER_CRASH_MODE=hold", "MACHINERY_RECOVER_HOLD_MARKER="+marker)
	if err := cmd.Start(); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_ = cmd.Process.Kill()
		_, _ = cmd.Process.Wait()
	})
	deadline := time.Now().Add(30 * time.Second)
	for time.Now().Before(deadline) {
		if _, err := os.Stat(marker); err == nil {
			return
		}
		time.Sleep(20 * time.Millisecond)
	}
	t.Fatal("concurrent writer fixture never became live")
}

func runRecoverCommand(t *testing.T, args ...string) (string, string, []int) {
	t.Helper()
	out, errB, codes := withCapturedIO(t)
	cmd := newRootCmd()
	cmd.SetArgs(append([]string{"recover"}, args...))
	_ = executeCaptured(cmd.Execute())
	return out.String(), errB.String(), *codes
}

func recoverSentinelPath(design string) string {
	return filepath.Join(design, ".machinery-design-publish.json")
}

// recoverTreeFingerprint witnesses every regular file and directory below
// root (path, mode, sha256) so tests can prove nothing was mutated.
func recoverTreeFingerprint(t *testing.T, root string) map[string]string {
	t.Helper()
	out := map[string]string{}
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		if info.IsDir() {
			out[filepath.ToSlash(rel)+"/"] = fmt.Sprintf("dir:%o", info.Mode().Perm())
			return nil
		}
		body, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		out[filepath.ToSlash(rel)] = fmt.Sprintf("file:%o:%x", info.Mode().Perm(), sha256Sum(body))
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return out
}

func sha256Sum(body []byte) string {
	digest := sha256.Sum256(body)
	return fmt.Sprintf("%x", digest[:])
}

// TestRecoverInspectReportsInterruptedPublication: default mode is a
// read-only report that names the writer, the recovery instruction, every
// expected output with its declared identity and current status, the
// journal inventory, the live-writer state, the verified input inventory,
// and the actionable decision.
func TestRecoverInspectReportsInterruptedPublication(t *testing.T) {
	design := recoverCrashFixture(t, "complete")
	out, errB, codes := runRecoverCommand(t, design)
	if len(codes) != 0 || errB != "" {
		t.Fatalf("inspection failed: codes=%v stderr=%q", codes, errB)
	}
	for _, want := range []string{
		"design root: " + design,
		"writer: " + recoverFixtureWriter,
		"recovery: " + recoverFixtureRecovery,
		"live writer: no",
		"input inventory: verified",
		"generated.txt",
		"generated-tree",
		"stale.txt",
		"match",
		".machinery-design-publish.json",
		"publish-sentinel",
		"action: finalize",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("inspection report missing %q:\n%s", want, out)
		}
	}
}

// TestRecoverInspectIsReadOnlyAndPreservesEvidence: inspection deletes no
// evidence and changes no artifact; the publication still blocks readers.
func TestRecoverInspectIsReadOnlyAndPreservesEvidence(t *testing.T) {
	design := recoverCrashFixture(t, "complete")
	before := recoverTreeFingerprint(t, design)
	out, errB, codes := runRecoverCommand(t, design)
	if len(codes) != 0 || errB != "" {
		t.Fatalf("inspection failed: codes=%v stderr=%q", codes, errB)
	}
	after := recoverTreeFingerprint(t, design)
	if len(before) != len(after) {
		t.Fatalf("inspection changed the design inventory: %d -> %d entries", len(before), len(after))
	}
	for key, value := range before {
		if after[key] != value {
			t.Fatalf("inspection mutated %s: %s -> %s", key, value, after[key])
		}
	}
	if _, err := os.Stat(recoverSentinelPath(design)); err != nil {
		t.Fatalf("inspection removed the publication sentinel: %v", err)
	}
	if reader, err := designlock.AcquireReader(design); err == nil {
		_ = reader.Release()
		t.Fatal("publication stopped blocking readers after a read-only inspection")
	}
	if !strings.Contains(out, "action: finalize") {
		t.Fatalf("inspection did not report its decision:\n%s", out)
	}
}

// TestRecoverApplyCompletesFullyPublishedTransactionIdempotently: --apply
// finalizes a content-and-mode complete transaction on a fresh process
// identity, leaves consistent artifacts, unblocks readers, and a second
// recovery is a harmless no-op.
func TestRecoverApplyCompletesFullyPublishedTransactionIdempotently(t *testing.T) {
	design := recoverCrashFixture(t, "complete")
	out, errB, codes := runRecoverCommand(t, design, "--apply")
	if len(codes) != 0 || errB != "" {
		t.Fatalf("apply failed: codes=%v stderr=%q stdout=\n%s", codes, errB, out)
	}
	if !strings.Contains(out, "completed") {
		t.Fatalf("apply did not report completion:\n%s", out)
	}
	if _, err := os.Stat(recoverSentinelPath(design)); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("publication sentinel survived a successful apply: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(design, "generated.txt"))
	if err != nil || string(body) != "generated by the interrupted writer\n" {
		t.Fatalf("recovered output wrong: %v %q", err, body)
	}
	info, err := os.Stat(filepath.Join(design, "generated-tree", "nested", "report.txt"))
	if err != nil || info.Mode().Perm() != 0o644 {
		t.Fatalf("recovered tree member wrong: %v %v", err, info)
	}
	if _, err := os.Stat(filepath.Join(design, "stale.txt")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("declared-absent output survived apply: %v", err)
	}
	if source, err := os.ReadFile(filepath.Join(design, "source.md")); err != nil || string(source) != "design inputs must survive every recovery path\n" {
		t.Fatalf("design input damaged by apply: %v %q", err, source)
	}
	reader, err := designlock.AcquireReader(design)
	if err != nil {
		t.Fatalf("reader remained blocked after apply: %v", err)
	}
	if err := reader.Release(); err != nil {
		t.Fatal(err)
	}
	out2, errB2, codes2 := runRecoverCommand(t, design, "--apply")
	if len(codes2) != 0 || errB2 != "" {
		t.Fatalf("idempotent second apply failed: codes=%v stderr=%q", codes2, errB2)
	}
	if !strings.Contains(out2, "no interrupted publication") {
		t.Fatalf("idempotent second apply did not report a clean design:\n%s", out2)
	}
}

// TestRecoverInspectReportsCleanDesign: a design without interruption
// reports action none and exits successfully.
func TestRecoverInspectReportsCleanDesign(t *testing.T) {
	design := t.TempDir()
	if err := os.WriteFile(filepath.Join(design, "source.md"), []byte("plain\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	out, errB, codes := runRecoverCommand(t, design)
	if len(codes) != 0 || errB != "" {
		t.Fatalf("clean inspection failed: codes=%v stderr=%q", codes, errB)
	}
	if !strings.Contains(out, "action: none") || !strings.Contains(out, "no interrupted publication") {
		t.Fatalf("clean design not reported:\n%s", out)
	}
}

// TestRecoverRejectsNonDirectoryArgument: the command refuses paths that are
// not existing real directories.
func TestRecoverRejectsNonDirectoryArgument(t *testing.T) {
	file := filepath.Join(t.TempDir(), "design.txt")
	if err := os.WriteFile(file, []byte("nope\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	for _, arg := range []string{file, filepath.Join(t.TempDir(), "absent")} {
		_, errB, codes := runRecoverCommand(t, arg)
		if len(codes) == 0 || codes[0] != 1 {
			t.Fatalf("non-directory argument %s accepted: codes=%v", arg, codes)
		}
		if !strings.Contains(errB, "must be an existing directory") {
			t.Fatalf("non-directory diagnostic wrong for %s: %q", arg, errB)
		}
	}
}

// TestRecoverApplyRefusalPreservesEvidenceTable: every refusal mode exits 1,
// explains the exact conflict, and preserves the journal and user files.
func TestRecoverApplyRefusalPreservesEvidenceTable(t *testing.T) {
	cases := []struct {
		name     string
		fixture  func(t *testing.T) string
		mutate   func(t *testing.T, design string)
		keywords []string
	}{
		{
			name:    "partial publication lacks complete proof",
			fixture: func(t *testing.T) string { return recoverCrashFixture(t, "partial") },
			keywords: []string{"generated-tree", "missing"},
		},
		{
			// A value substitution that keeps the sentinel byte-canonical and
			// internally consistent is indistinguishable from a legitimate
			// record and content-safe to finalize (the writer label is not
			// part of any inventory proof), so the tamper battery uses a
			// detectable non-canonical body instead: trailing bytes after the
			// canonical JSON document.
			name:    "tampered sentinel body",
			fixture: func(t *testing.T) string { return recoverCrashFixture(t, "complete") },
			mutate: func(t *testing.T, design string) {
				body, err := os.ReadFile(recoverSentinelPath(design))
				if err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(recoverSentinelPath(design), append(body, '\n', '\n'), 0o600); err != nil {
					t.Fatal(err)
				}
			},
			keywords: []string{"sentinel", "invalid"},
		},
		{
			name:    "tampered sentinel permissions",
			fixture: func(t *testing.T) string { return recoverCrashFixture(t, "complete") },
			mutate: func(t *testing.T, design string) {
				if err := os.Chmod(recoverSentinelPath(design), 0o644); err != nil {
					t.Fatal(err)
				}
			},
			keywords: []string{"sentinel", "private"},
		},
		{
			name:    "design input changed after interruption",
			fixture: func(t *testing.T) string { return recoverCrashFixture(t, "complete") },
			mutate: func(t *testing.T, design string) {
				if err := os.WriteFile(filepath.Join(design, "source.md"), []byte("edited after the crash\n"), 0o644); err != nil {
					t.Fatal(err)
				}
			},
			keywords: []string{"input inventory does not match"},
		},
		{
			name:    "swapped output content",
			fixture: func(t *testing.T) string { return recoverCrashFixture(t, "complete") },
			mutate: func(t *testing.T, design string) {
				if err := os.WriteFile(filepath.Join(design, "generated.txt"), []byte("swapped bytes\n"), 0o644); err != nil {
					t.Fatal(err)
				}
			},
			keywords: []string{"generated.txt", "digest"},
		},
		{
			name:    "output mode mismatch",
			fixture: func(t *testing.T) string { return recoverCrashFixture(t, "complete") },
			mutate: func(t *testing.T, design string) {
				if err := os.Chmod(filepath.Join(design, "generated.txt"), 0o600); err != nil {
					t.Fatal(err)
				}
			},
			keywords: []string{"mode"},
		},
		{
			name:    "symlink escape replaces an output",
			fixture: func(t *testing.T) string { return recoverCrashFixture(t, "complete") },
			mutate: func(t *testing.T, design string) {
				outside := filepath.Join(t.TempDir(), "secret.txt")
				if err := os.WriteFile(outside, []byte("generated by the interrupted writer\n"), 0o644); err != nil {
					t.Fatal(err)
				}
				if err := os.Remove(filepath.Join(design, "generated.txt")); err != nil {
					t.Fatal(err)
				}
				if err := os.Symlink(outside, filepath.Join(design, "generated.txt")); err != nil {
					t.Fatal(err)
				}
			},
			keywords: []string{"symlink"},
		},
		{
			name:    "unexpected tree member",
			fixture: func(t *testing.T) string { return recoverCrashFixture(t, "complete") },
			mutate: func(t *testing.T, design string) {
				if err := os.WriteFile(filepath.Join(design, "generated-tree", "nested", "extra.txt"), []byte("unexpected\n"), 0o644); err != nil {
					t.Fatal(err)
				}
			},
			keywords: []string{"generated-tree", "unexpected"},
		},
		{
			name:    "declared-absent output reappeared",
			fixture: func(t *testing.T) string { return recoverCrashFixture(t, "complete") },
			mutate: func(t *testing.T, design string) {
				if err := os.WriteFile(filepath.Join(design, "stale.txt"), []byte("resurrected\n"), 0o644); err != nil {
					t.Fatal(err)
				}
			},
			keywords: []string{"stale.txt", "declared deleted"},
		},
		{
			name:    "concurrent writer holds the design lock",
			fixture: func(t *testing.T) string { design := recoverCrashFixture(t, "complete"); recoverHoldDesign(t, design); return design },
			keywords: []string{"another process holds the design snapshot lock"},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			design := tc.fixture(t)
			if tc.mutate != nil {
				tc.mutate(t, design)
			}
			// The user's view of their inputs at refusal time (possibly the
			// very bytes an intentional edit left behind): recovery must
			// preserve exactly this state, never roll it back.
			sourceBefore, err := os.ReadFile(filepath.Join(design, "source.md"))
			if err != nil {
				t.Fatal(err)
			}
			before := recoverTreeFingerprint(t, design)
			out, errB, codes := runRecoverCommand(t, design, "--apply")
			if len(codes) == 0 || codes[0] != 1 {
				t.Fatalf("refusal must exit 1: codes=%v stdout=\n%s", codes, out)
			}
			for _, keyword := range tc.keywords {
				if !strings.Contains(errB, keyword) && !strings.Contains(out, keyword) {
					t.Fatalf("refusal diagnostic missing %q; stderr=%q stdout=\n%s", keyword, errB, out)
				}
			}
			if !strings.Contains(errB, "nothing was modified") {
				t.Fatalf("refusal must state that nothing was modified: %q", errB)
			}
			after := recoverTreeFingerprint(t, design)
			if len(before) != len(after) {
				t.Fatalf("refusal changed the design inventory: %d -> %d entries", len(before), len(after))
			}
			for key, value := range before {
				if after[key] != value {
					t.Fatalf("refusal mutated %s: %s -> %s", key, value, after[key])
				}
			}
			if _, err := os.Stat(recoverSentinelPath(design)); err != nil {
				t.Fatalf("refusal deleted the publication sentinel: %v", err)
			}
			if source, err := os.ReadFile(filepath.Join(design, "source.md")); err != nil || !bytes.Equal(source, sourceBefore) {
				t.Fatalf("refusal damaged design inputs: %v %q", err, source)
			}
		})
	}
}

// TestRecoverControlInterruptedPublicationStillBlocksReaders is the passing
// control on unmodified production: the crash fixtures above leave real
// interruption residue that the hardened reader contract rejects.
func TestRecoverControlInterruptedPublicationStillBlocksReaders(t *testing.T) {
	for _, mode := range []string{"complete", "partial"} {
		design := recoverCrashFixture(t, mode)
		if reader, err := designlock.AcquireReader(design); err == nil {
			_ = reader.Release()
			t.Fatalf("reader acquired across %s interruption residue", mode)
		}
	}
}
